// Code generated by ent, DO NOT EDIT.

package position

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the position type in the database.
	Label = "position"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldPositionType holds the string denoting the position_type field in the database.
	FieldPositionType = "position_type"
	// FieldJobProfileID holds the string denoting the job_profile_id field in the database.
	FieldJobProfileID = "job_profile_id"
	// FieldDepartmentID holds the string denoting the department_id field in the database.
	FieldDepartmentID = "department_id"
	// FieldManagerPositionID holds the string denoting the manager_position_id field in the database.
	FieldManagerPositionID = "manager_position_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBudgetedFte holds the string denoting the budgeted_fte field in the database.
	FieldBudgetedFte = "budgeted_fte"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeManager holds the string denoting the manager edge name in mutations.
	EdgeManager = "manager"
	// EdgeDirectReports holds the string denoting the direct_reports edge name in mutations.
	EdgeDirectReports = "direct_reports"
	// EdgeDepartment holds the string denoting the department edge name in mutations.
	EdgeDepartment = "department"
	// EdgeCurrentIncumbents holds the string denoting the current_incumbents edge name in mutations.
	EdgeCurrentIncumbents = "current_incumbents"
	// EdgeOccupancyHistory holds the string denoting the occupancy_history edge name in mutations.
	EdgeOccupancyHistory = "occupancy_history"
	// EdgeAttributeHistory holds the string denoting the attribute_history edge name in mutations.
	EdgeAttributeHistory = "attribute_history"
	// Table holds the table name of the position in the database.
	Table = "positions"
	// ManagerTable is the table that holds the manager relation/edge.
	ManagerTable = "positions"
	// ManagerColumn is the table column denoting the manager relation/edge.
	ManagerColumn = "manager_position_id"
	// DirectReportsTable is the table that holds the direct_reports relation/edge.
	DirectReportsTable = "positions"
	// DirectReportsColumn is the table column denoting the direct_reports relation/edge.
	DirectReportsColumn = "manager_position_id"
	// DepartmentTable is the table that holds the department relation/edge.
	DepartmentTable = "positions"
	// DepartmentInverseTable is the table name for the OrganizationUnit entity.
	// It exists in this package in order to avoid circular dependency with the "organizationunit" package.
	DepartmentInverseTable = "organization_units"
	// DepartmentColumn is the table column denoting the department relation/edge.
	DepartmentColumn = "department_id"
	// CurrentIncumbentsTable is the table that holds the current_incumbents relation/edge.
	CurrentIncumbentsTable = "employees"
	// CurrentIncumbentsInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	CurrentIncumbentsInverseTable = "employees"
	// CurrentIncumbentsColumn is the table column denoting the current_incumbents relation/edge.
	CurrentIncumbentsColumn = "current_position_id"
	// OccupancyHistoryTable is the table that holds the occupancy_history relation/edge.
	OccupancyHistoryTable = "position_occupancy_histories"
	// OccupancyHistoryInverseTable is the table name for the PositionOccupancyHistory entity.
	// It exists in this package in order to avoid circular dependency with the "positionoccupancyhistory" package.
	OccupancyHistoryInverseTable = "position_occupancy_histories"
	// OccupancyHistoryColumn is the table column denoting the occupancy_history relation/edge.
	OccupancyHistoryColumn = "position_id"
	// AttributeHistoryTable is the table that holds the attribute_history relation/edge.
	AttributeHistoryTable = "position_attribute_histories"
	// AttributeHistoryInverseTable is the table name for the PositionAttributeHistory entity.
	// It exists in this package in order to avoid circular dependency with the "positionattributehistory" package.
	AttributeHistoryInverseTable = "position_attribute_histories"
	// AttributeHistoryColumn is the table column denoting the attribute_history relation/edge.
	AttributeHistoryColumn = "position_id"
)

// Columns holds all SQL columns for position fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldPositionType,
	FieldJobProfileID,
	FieldDepartmentID,
	FieldManagerPositionID,
	FieldStatus,
	FieldBudgetedFte,
	FieldDetails,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBudgetedFte holds the default value on creation for the "budgeted_fte" field.
	DefaultBudgetedFte float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PositionType defines the type for the "position_type" enum field.
type PositionType string

// PositionType values.
const (
	PositionTypeFULL_TIME         PositionType = "FULL_TIME"
	PositionTypePART_TIME         PositionType = "PART_TIME"
	PositionTypeCONTINGENT_WORKER PositionType = "CONTINGENT_WORKER"
	PositionTypeINTERN            PositionType = "INTERN"
)

func (pt PositionType) String() string {
	return string(pt)
}

// PositionTypeValidator is a validator for the "position_type" field enum values. It is called by the builders before save.
func PositionTypeValidator(pt PositionType) error {
	switch pt {
	case PositionTypeFULL_TIME, PositionTypePART_TIME, PositionTypeCONTINGENT_WORKER, PositionTypeINTERN:
		return nil
	default:
		return fmt.Errorf("position: invalid enum value for position_type field: %q", pt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusOPEN is the default value of the Status enum.
const DefaultStatus = StatusOPEN

// Status values.
const (
	StatusOPEN                Status = "OPEN"
	StatusFILLED              Status = "FILLED"
	StatusFROZEN              Status = "FROZEN"
	StatusPENDING_ELIMINATION Status = "PENDING_ELIMINATION"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusOPEN, StatusFILLED, StatusFROZEN, StatusPENDING_ELIMINATION:
		return nil
	default:
		return fmt.Errorf("position: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Position queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByPositionType orders the results by the position_type field.
func ByPositionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionType, opts...).ToFunc()
}

// ByJobProfileID orders the results by the job_profile_id field.
func ByJobProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobProfileID, opts...).ToFunc()
}

// ByDepartmentID orders the results by the department_id field.
func ByDepartmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartmentID, opts...).ToFunc()
}

// ByManagerPositionID orders the results by the manager_position_id field.
func ByManagerPositionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagerPositionID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBudgetedFte orders the results by the budgeted_fte field.
func ByBudgetedFte(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBudgetedFte, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByManagerField orders the results by manager field.
func ByManagerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagerStep(), sql.OrderByField(field, opts...))
	}
}

// ByDirectReportsCount orders the results by direct_reports count.
func ByDirectReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDirectReportsStep(), opts...)
	}
}

// ByDirectReports orders the results by direct_reports terms.
func ByDirectReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDirectReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDepartmentField orders the results by department field.
func ByDepartmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDepartmentStep(), sql.OrderByField(field, opts...))
	}
}

// ByCurrentIncumbentsCount orders the results by current_incumbents count.
func ByCurrentIncumbentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCurrentIncumbentsStep(), opts...)
	}
}

// ByCurrentIncumbents orders the results by current_incumbents terms.
func ByCurrentIncumbents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCurrentIncumbentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOccupancyHistoryCount orders the results by occupancy_history count.
func ByOccupancyHistoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOccupancyHistoryStep(), opts...)
	}
}

// ByOccupancyHistory orders the results by occupancy_history terms.
func ByOccupancyHistory(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOccupancyHistoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAttributeHistoryCount orders the results by attribute_history count.
func ByAttributeHistoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttributeHistoryStep(), opts...)
	}
}

// ByAttributeHistory orders the results by attribute_history terms.
func ByAttributeHistory(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttributeHistoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newManagerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ManagerTable, ManagerColumn),
	)
}
func newDirectReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DirectReportsTable, DirectReportsColumn),
	)
}
func newDepartmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DepartmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DepartmentTable, DepartmentColumn),
	)
}
func newCurrentIncumbentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CurrentIncumbentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CurrentIncumbentsTable, CurrentIncumbentsColumn),
	)
}
func newOccupancyHistoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OccupancyHistoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OccupancyHistoryTable, OccupancyHistoryColumn),
	)
}
func newAttributeHistoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttributeHistoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttributeHistoryTable, AttributeHistoryColumn),
	)
}
