run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - depguard
    - importas
    - revive
    - govet

linters-settings:
  depguard:
    rules:
      command-service-boundary:
        list-type: blacklist
        packages:
          - cube-castle/cmd/hrms-server/query/internal
          - cube-castle/cmd/hrms-server/query/internal/...
        files:
          - cmd/hrms-server/command/internal/...
        message: "命令服务不得依赖查询服务内部实现"
      query-service-boundary:
        list-type: blacklist
        packages:
          - cube-castle/cmd/hrms-server/command/internal
          - cube-castle/cmd/hrms-server/command/internal/...
        files:
          - cmd/hrms-server/query/internal/...
        message: "查询服务不得依赖命令服务内部实现"
  importas:
    alias:
      - pkg: cube-castle/internal/graphql
        alias: schemaLoader
      - pkg: cube-castle/internal/middleware
        alias: requestMiddleware

issues:
  exclude-use-default: false
