run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - depguard
    - importas
    - revive
    - govet
    - tagliatelle

linters-settings:
  depguard:
    rules:
      command-service-boundary:
        list-type: blacklist
        packages:
          - cube-castle/cmd/hrms-server/query/internal
          - cube-castle/cmd/hrms-server/query/internal/...
        files:
          - cmd/hrms-server/command/internal/...
        message: "命令服务不得依赖查询服务内部实现"
      query-service-boundary:
        list-type: blacklist
        packages:
          - cube-castle/cmd/hrms-server/command/internal
          - cube-castle/cmd/hrms-server/command/internal/...
        files:
          - cmd/hrms-server/query/internal/...
        message: "查询服务不得依赖命令服务内部实现"
  importas:
    alias:
      - pkg: cube-castle/internal/graphql
        alias: schemaLoader
      - pkg: cube-castle/internal/middleware
        alias: requestMiddleware
  tagliatelle:
    case:
      json: camel

issues:
  exclude-use-default: false
  exclude-rules:
    # 允许 OAuth/OIDC/JWT 标准字段的 snake_case json tag（仅限认证相关路径，且仅允许列举字段）
    - linters:
        - tagliatelle
      path: internal/auth/.*
      source: 'json:"(access_token|refresh_token|token_type|id_token|expires_in|authorization_endpoint|token_endpoint|end_session_endpoint|jwks_uri|tenant_id)"'
    - linters:
        - tagliatelle
      path: cmd/hrms-server/.*/internal/auth/.*
      source: 'json:"(access_token|refresh_token|token_type|id_token|expires_in|authorization_endpoint|token_endpoint|end_session_endpoint|jwks_uri|tenant_id)"'
    - linters:
        - tagliatelle
      path: cmd/hrms-server/.*/internal/authbff/oidc\.go
      source: 'json:"(access_token|refresh_token|token_type|id_token|expires_in|authorization_endpoint|token_endpoint|end_session_endpoint|jwks_uri|tenant_id)"'
    # 缓存/内部状态对象不作为对外响应的约束目标（避免误报）
    - linters:
        - tagliatelle
      path: internal/cache/.*
