run:
  timeout: 5m
  issues-exit-code: 1
  # TODO-TEMPORARY(2025-11-16): soften package loading to avoid go1.24 typecheck noise on generated/third_party
  skip-dirs:
    - third_party
    - tools
  skip-files:
    # TODO-TEMPORARY(2025-11-16): generated GraphQL contains constructs that trip go1.24 loader
    - cmd/hrms-server/query/internal/graphql/generated.go
    # TODO-TEMPORARY(2025-11-16): infra/dev helpers not part of boundary/naming gate
    - scripts/cmd/.*
    # TODO-TEMPORARY(2025-11-16): known local types under refactor
    - internal/types/date.go
    - internal/monitoring/health/health.go
    - internal/config/scheduler.go
    - internal/organization/middleware/performance.go
    - cmd/hrms-server/command/internal/authbff/.*\.go
    - cmd/hrms-server/query/publicgraphql/.*\.go

linters:
  enable:
    - depguard
    - importas
    - revive
    - govet
    - tagliatelle

linters-settings:
  depguard:
    rules:
      command-service-boundary:
        # Deny query service internals from command service files
        deny:
          - pkg: cube-castle/cmd/hrms-server/query/internal
            desc: "命令服务不得依赖查询服务内部实现"
          - pkg: cube-castle/cmd/hrms-server/query/internal/...
            desc: "命令服务不得依赖查询服务内部实现"
        files:
          - cmd/hrms-server/command/internal/...
      query-service-boundary:
        # Deny command service internals from query service files
        deny:
          - pkg: cube-castle/cmd/hrms-server/command/internal
            desc: "查询服务不得依赖命令服务内部实现"
          - pkg: cube-castle/cmd/hrms-server/command/internal/...
            desc: "查询服务不得依赖命令服务内部实现"
        files:
          - cmd/hrms-server/query/internal/...
  importas:
    alias:
      - pkg: cube-castle/internal/graphql
        alias: schemaLoader
      - pkg: cube-castle/internal/middleware
        alias: requestMiddleware
  tagliatelle:
    case:
      json: camel

issues:
  exclude-use-default: false
  exclude-rules:
    # 允许 OAuth/OIDC/JWT 标准字段的 snake_case json tag（仅限认证相关路径，且仅允许列举字段）
    - linters:
        - tagliatelle
      path: internal/auth/.*
      source: 'json:"(access_token|refresh_token|token_type|id_token|expires_in|authorization_endpoint|token_endpoint|end_session_endpoint|jwks_uri|tenant_id)"'
    - linters:
        - tagliatelle
      path: cmd/hrms-server/.*/internal/auth/.*
      source: 'json:"(access_token|refresh_token|token_type|id_token|expires_in|authorization_endpoint|token_endpoint|end_session_endpoint|jwks_uri|tenant_id)"'
    - linters:
        - tagliatelle
      path: cmd/hrms-server/.*/internal/authbff/oidc\.go
      source: 'json:"(access_token|refresh_token|token_type|id_token|expires_in|authorization_endpoint|token_endpoint|end_session_endpoint|jwks_uri|tenant_id)"'
    # 缓存/内部状态对象不作为对外响应的约束目标（避免误报）
    - linters:
        - tagliatelle
      path: internal/cache/.*
