// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID              uuid.UUID       `json:"id"`
	TenantID        uuid.UUID       `json:"tenant_id"`
	EventType       string          `json:"event_type"`
	ResourceType    string          `json:"resource_type"`
	ResourceID      sql.NullString  `json:"resource_id"`
	ActorID         sql.NullString  `json:"actor_id"`
	ActorType       sql.NullString  `json:"actor_type"`
	ActionName      sql.NullString  `json:"action_name"`
	RequestID       sql.NullString  `json:"request_id"`
	OperationReason sql.NullString  `json:"operation_reason"`
	Timestamp       time.Time       `json:"timestamp"`
	Success         bool            `json:"success"`
	ErrorCode       sql.NullString  `json:"error_code"`
	ErrorMessage    sql.NullString  `json:"error_message"`
	RequestData     json.RawMessage `json:"request_data"`
	ResponseData    json.RawMessage `json:"response_data"`
	ModifiedFields  json.RawMessage `json:"modified_fields"`
	Changes         json.RawMessage `json:"changes"`
	// 组织单元时态版本的唯一标识，用于精确审计查询
	RecordID        uuid.NullUUID   `json:"record_id"`
	BusinessContext json.RawMessage `json:"business_context"`
}

type GooseDbVersion struct {
	ID        int32     `json:"id"`
	VersionID int64     `json:"version_id"`
	IsApplied bool      `json:"is_applied"`
	Tstamp    time.Time `json:"tstamp"`
}

type JobFamily struct {
	RecordID        uuid.UUID      `json:"record_id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	FamilyCode      string         `json:"family_code"`
	FamilyGroupCode string         `json:"family_group_code"`
	ParentRecordID  uuid.UUID      `json:"parent_record_id"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Status          string         `json:"status"`
	EffectiveDate   time.Time      `json:"effective_date"`
	EndDate         sql.NullTime   `json:"end_date"`
	IsCurrent       bool           `json:"is_current"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type JobFamilyGroup struct {
	RecordID        uuid.UUID      `json:"record_id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	FamilyGroupCode string         `json:"family_group_code"`
	Name            string         `json:"name"`
	Description     sql.NullString `json:"description"`
	Status          string         `json:"status"`
	EffectiveDate   time.Time      `json:"effective_date"`
	EndDate         sql.NullTime   `json:"end_date"`
	IsCurrent       bool           `json:"is_current"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type JobLevel struct {
	RecordID       uuid.UUID             `json:"record_id"`
	TenantID       uuid.UUID             `json:"tenant_id"`
	LevelCode      string                `json:"level_code"`
	RoleCode       string                `json:"role_code"`
	ParentRecordID uuid.UUID             `json:"parent_record_id"`
	LevelRank      string                `json:"level_rank"`
	Name           string                `json:"name"`
	Description    sql.NullString        `json:"description"`
	SalaryBand     pqtype.NullRawMessage `json:"salary_band"`
	Status         string                `json:"status"`
	EffectiveDate  time.Time             `json:"effective_date"`
	EndDate        sql.NullTime          `json:"end_date"`
	IsCurrent      bool                  `json:"is_current"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type JobRole struct {
	RecordID        uuid.UUID             `json:"record_id"`
	TenantID        uuid.UUID             `json:"tenant_id"`
	RoleCode        string                `json:"role_code"`
	FamilyCode      string                `json:"family_code"`
	ParentRecordID  uuid.UUID             `json:"parent_record_id"`
	Name            string                `json:"name"`
	Description     sql.NullString        `json:"description"`
	CompetencyModel pqtype.NullRawMessage `json:"competency_model"`
	Status          string                `json:"status"`
	EffectiveDate   time.Time             `json:"effective_date"`
	EndDate         sql.NullTime          `json:"end_date"`
	IsCurrent       bool                  `json:"is_current"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
}

type OrganizationCurrent struct {
	TenantID      uuid.UUID       `json:"tenant_id"`
	Code          string          `json:"code"`
	ParentCode    sql.NullString  `json:"parent_code"`
	Name          string          `json:"name"`
	UnitType      string          `json:"unit_type"`
	Status        string          `json:"status"`
	Level         int32           `json:"level"`
	CodePath      string          `json:"code_path"`
	NamePath      string          `json:"name_path"`
	SortOrder     int32           `json:"sort_order"`
	Description   sql.NullString  `json:"description"`
	Profile       json.RawMessage `json:"profile"`
	EffectiveDate time.Time       `json:"effective_date"`
	EndDate       sql.NullTime    `json:"end_date"`
	IsCurrent     bool            `json:"is_current"`
	ChangeReason  sql.NullString  `json:"change_reason"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type OrganizationStatsView struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	UnitType        string    `json:"unit_type"`
	Count           int64     `json:"count"`
	CurrentCount    int64     `json:"current_count"`
	HistoricalCount int64     `json:"historical_count"`
}

type OrganizationTemporalCurrent struct {
	RecordID         uuid.UUID       `json:"record_id"`
	TenantID         uuid.UUID       `json:"tenant_id"`
	Code             string          `json:"code"`
	ParentCode       sql.NullString  `json:"parent_code"`
	Name             string          `json:"name"`
	UnitType         string          `json:"unit_type"`
	Status           string          `json:"status"`
	Level            int32           `json:"level"`
	HierarchyDepth   int32           `json:"hierarchy_depth"`
	CodePath         string          `json:"code_path"`
	NamePath         string          `json:"name_path"`
	SortOrder        int32           `json:"sort_order"`
	Description      sql.NullString  `json:"description"`
	Profile          json.RawMessage `json:"profile"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	EffectiveDate    time.Time       `json:"effective_date"`
	EndDate          sql.NullTime    `json:"end_date"`
	ChangeReason     sql.NullString  `json:"change_reason"`
	IsCurrent        bool            `json:"is_current"`
	DeletedAt        sql.NullTime    `json:"deleted_at"`
	DeletedBy        uuid.NullUUID   `json:"deleted_by"`
	DeletionReason   sql.NullString  `json:"deletion_reason"`
	SuspendedAt      sql.NullTime    `json:"suspended_at"`
	SuspendedBy      uuid.NullUUID   `json:"suspended_by"`
	SuspensionReason sql.NullString  `json:"suspension_reason"`
	OperatedByID     uuid.NullUUID   `json:"operated_by_id"`
	OperatedByName   sql.NullString  `json:"operated_by_name"`
	Metadata         json.RawMessage `json:"metadata"`
	EffectiveFrom    sql.NullTime    `json:"effective_from"`
	EffectiveTo      sql.NullTime    `json:"effective_to"`
	ChangedBy        uuid.NullUUID   `json:"changed_by"`
	ApprovedBy       uuid.NullUUID   `json:"approved_by"`
}

type OrganizationUnit struct {
	RecordID         uuid.UUID       `json:"record_id"`
	TenantID         uuid.UUID       `json:"tenant_id"`
	Code             string          `json:"code"`
	ParentCode       sql.NullString  `json:"parent_code"`
	Name             string          `json:"name"`
	UnitType         string          `json:"unit_type"`
	Status           string          `json:"status"`
	Level            int32           `json:"level"`
	HierarchyDepth   int32           `json:"hierarchy_depth"`
	CodePath         string          `json:"code_path"`
	NamePath         string          `json:"name_path"`
	SortOrder        int32           `json:"sort_order"`
	Description      sql.NullString  `json:"description"`
	Profile          json.RawMessage `json:"profile"`
	Metadata         json.RawMessage `json:"metadata"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	EffectiveDate    time.Time       `json:"effective_date"`
	EndDate          sql.NullTime    `json:"end_date"`
	ChangeReason     sql.NullString  `json:"change_reason"`
	IsCurrent        bool            `json:"is_current"`
	DeletedAt        sql.NullTime    `json:"deleted_at"`
	DeletedBy        uuid.NullUUID   `json:"deleted_by"`
	DeletionReason   sql.NullString  `json:"deletion_reason"`
	SuspendedAt      sql.NullTime    `json:"suspended_at"`
	SuspendedBy      uuid.NullUUID   `json:"suspended_by"`
	SuspensionReason sql.NullString  `json:"suspension_reason"`
	OperatedByID     uuid.NullUUID   `json:"operated_by_id"`
	OperatedByName   sql.NullString  `json:"operated_by_name"`
	OperationType    sql.NullString  `json:"operation_type"`
	EffectiveFrom    sql.NullTime    `json:"effective_from"`
	EffectiveTo      sql.NullTime    `json:"effective_to"`
	ChangedBy        uuid.NullUUID   `json:"changed_by"`
	ApprovedBy       uuid.NullUUID   `json:"approved_by"`
}

type OrganizationUnitsBackupTemporal struct {
	RecordID         uuid.NullUUID         `json:"record_id"`
	TenantID         uuid.NullUUID         `json:"tenant_id"`
	Code             sql.NullString        `json:"code"`
	ParentCode       sql.NullString        `json:"parent_code"`
	Name             sql.NullString        `json:"name"`
	UnitType         sql.NullString        `json:"unit_type"`
	Status           sql.NullString        `json:"status"`
	Level            sql.NullInt32         `json:"level"`
	HierarchyDepth   sql.NullInt32         `json:"hierarchy_depth"`
	CodePath         sql.NullString        `json:"code_path"`
	NamePath         sql.NullString        `json:"name_path"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Description      sql.NullString        `json:"description"`
	Profile          pqtype.NullRawMessage `json:"profile"`
	Metadata         pqtype.NullRawMessage `json:"metadata"`
	CreatedAt        sql.NullTime          `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
	EffectiveDate    sql.NullTime          `json:"effective_date"`
	EndDate          sql.NullTime          `json:"end_date"`
	ChangeReason     sql.NullString        `json:"change_reason"`
	IsCurrent        sql.NullBool          `json:"is_current"`
	DeletedAt        sql.NullTime          `json:"deleted_at"`
	DeletedBy        uuid.NullUUID         `json:"deleted_by"`
	DeletionReason   sql.NullString        `json:"deletion_reason"`
	SuspendedAt      sql.NullTime          `json:"suspended_at"`
	SuspendedBy      uuid.NullUUID         `json:"suspended_by"`
	SuspensionReason sql.NullString        `json:"suspension_reason"`
	OperatedByID     uuid.NullUUID         `json:"operated_by_id"`
	OperatedByName   sql.NullString        `json:"operated_by_name"`
	OperationType    sql.NullString        `json:"operation_type"`
	EffectiveFrom    sql.NullTime          `json:"effective_from"`
	EffectiveTo      sql.NullTime          `json:"effective_to"`
	ChangedBy        uuid.NullUUID         `json:"changed_by"`
	ApprovedBy       uuid.NullUUID         `json:"approved_by"`
	IsTemporal       sql.NullBool          `json:"is_temporal"`
}

type OrganizationUnitsUnittypeBackup struct {
	RecordID         uuid.NullUUID         `json:"record_id"`
	TenantID         uuid.NullUUID         `json:"tenant_id"`
	Code             sql.NullString        `json:"code"`
	ParentCode       sql.NullString        `json:"parent_code"`
	Name             sql.NullString        `json:"name"`
	UnitType         sql.NullString        `json:"unit_type"`
	Status           sql.NullString        `json:"status"`
	Level            sql.NullInt32         `json:"level"`
	HierarchyDepth   sql.NullInt32         `json:"hierarchy_depth"`
	CodePath         sql.NullString        `json:"code_path"`
	NamePath         sql.NullString        `json:"name_path"`
	SortOrder        sql.NullInt32         `json:"sort_order"`
	Description      sql.NullString        `json:"description"`
	Profile          pqtype.NullRawMessage `json:"profile"`
	Metadata         pqtype.NullRawMessage `json:"metadata"`
	CreatedAt        sql.NullTime          `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
	EffectiveDate    sql.NullTime          `json:"effective_date"`
	EndDate          sql.NullTime          `json:"end_date"`
	ChangeReason     sql.NullString        `json:"change_reason"`
	IsCurrent        sql.NullBool          `json:"is_current"`
	DeletedAt        sql.NullTime          `json:"deleted_at"`
	DeletedBy        uuid.NullUUID         `json:"deleted_by"`
	DeletionReason   sql.NullString        `json:"deletion_reason"`
	SuspendedAt      sql.NullTime          `json:"suspended_at"`
	SuspendedBy      uuid.NullUUID         `json:"suspended_by"`
	SuspensionReason sql.NullString        `json:"suspension_reason"`
	OperatedByID     uuid.NullUUID         `json:"operated_by_id"`
	OperatedByName   sql.NullString        `json:"operated_by_name"`
	OperationType    sql.NullString        `json:"operation_type"`
	EffectiveFrom    sql.NullTime          `json:"effective_from"`
	EffectiveTo      sql.NullTime          `json:"effective_to"`
	ChangedBy        uuid.NullUUID         `json:"changed_by"`
	ApprovedBy       uuid.NullUUID         `json:"approved_by"`
	IsTemporal       sql.NullBool          `json:"is_temporal"`
}

type Position struct {
	RecordID               uuid.UUID       `json:"record_id"`
	TenantID               uuid.UUID       `json:"tenant_id"`
	Code                   string          `json:"code"`
	Title                  string          `json:"title"`
	JobProfileCode         sql.NullString  `json:"job_profile_code"`
	JobProfileName         sql.NullString  `json:"job_profile_name"`
	JobFamilyGroupCode     string          `json:"job_family_group_code"`
	JobFamilyGroupName     string          `json:"job_family_group_name"`
	JobFamilyGroupRecordID uuid.UUID       `json:"job_family_group_record_id"`
	JobFamilyCode          string          `json:"job_family_code"`
	JobFamilyName          string          `json:"job_family_name"`
	JobFamilyRecordID      uuid.UUID       `json:"job_family_record_id"`
	JobRoleCode            string          `json:"job_role_code"`
	JobRoleName            string          `json:"job_role_name"`
	JobRoleRecordID        uuid.UUID       `json:"job_role_record_id"`
	JobLevelCode           string          `json:"job_level_code"`
	JobLevelName           string          `json:"job_level_name"`
	JobLevelRecordID       uuid.UUID       `json:"job_level_record_id"`
	OrganizationCode       string          `json:"organization_code"`
	OrganizationName       sql.NullString  `json:"organization_name"`
	PositionType           string          `json:"position_type"`
	Status                 string          `json:"status"`
	EmploymentType         string          `json:"employment_type"`
	HeadcountCapacity      string          `json:"headcount_capacity"`
	HeadcountInUse         string          `json:"headcount_in_use"`
	GradeLevel             sql.NullString  `json:"grade_level"`
	CostCenterCode         sql.NullString  `json:"cost_center_code"`
	ReportsToPositionCode  sql.NullString  `json:"reports_to_position_code"`
	Profile                json.RawMessage `json:"profile"`
	EffectiveDate          time.Time       `json:"effective_date"`
	EndDate                sql.NullTime    `json:"end_date"`
	IsCurrent              bool            `json:"is_current"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              time.Time       `json:"updated_at"`
	DeletedAt              sql.NullTime    `json:"deleted_at"`
	OperationType          string          `json:"operation_type"`
	OperatedByID           uuid.UUID       `json:"operated_by_id"`
	OperatedByName         string          `json:"operated_by_name"`
	OperationReason        sql.NullString  `json:"operation_reason"`
}

type PositionAssignment struct {
	AssignmentID     uuid.UUID      `json:"assignment_id"`
	TenantID         uuid.UUID      `json:"tenant_id"`
	PositionCode     string         `json:"position_code"`
	PositionRecordID uuid.UUID      `json:"position_record_id"`
	EmployeeID       uuid.UUID      `json:"employee_id"`
	EmployeeName     string         `json:"employee_name"`
	EmployeeNumber   sql.NullString `json:"employee_number"`
	AssignmentType   string         `json:"assignment_type"`
	AssignmentStatus string         `json:"assignment_status"`
	Fte              string         `json:"fte"`
	EffectiveDate    time.Time      `json:"effective_date"`
	EndDate          sql.NullTime   `json:"end_date"`
	IsCurrent        bool           `json:"is_current"`
	Notes            sql.NullString `json:"notes"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	ActingUntil      sql.NullTime   `json:"acting_until"`
	AutoRevert       bool           `json:"auto_revert"`
	ReminderSentAt   sql.NullTime   `json:"reminder_sent_at"`
}

type StandardObject struct {
	ID                 uuid.UUID       `json:"id"`
	ObjectType         string          `json:"object_type"`
	Code               string          `json:"code"`
	TenantCode         string          `json:"tenant_code"`
	DisplayName        string          `json:"display_name"`
	Status             string          `json:"status"`
	Labels             json.RawMessage `json:"labels"`
	SchemaVersion      string          `json:"schema_version"`
	DataClassification string          `json:"data_classification"`
	RetentionPolicy    string          `json:"retention_policy"`
	CreatedBy          uuid.NullUUID   `json:"created_by"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type StandardObjectAttachment struct {
	ID             uuid.UUID       `json:"id"`
	ObjectID       uuid.UUID       `json:"object_id"`
	TenantCode     string          `json:"tenant_code"`
	AttachmentType string          `json:"attachment_type"`
	Uri            string          `json:"uri"`
	Labels         json.RawMessage `json:"labels"`
	Metadata       json.RawMessage `json:"metadata"`
	CreatedBy      uuid.NullUUID   `json:"created_by"`
	CreatedAt      time.Time       `json:"created_at"`
}

type StandardObjectHierarchySnapshot struct {
	SnapshotID         uuid.UUID       `json:"snapshot_id"`
	TenantCode         string          `json:"tenant_code"`
	ObjectType         string          `json:"object_type"`
	AsOfValid          time.Time       `json:"as_of_valid"`
	AsOfTransaction    time.Time       `json:"as_of_transaction"`
	AncestorObjectID   uuid.UUID       `json:"ancestor_object_id"`
	DescendantObjectID uuid.UUID       `json:"descendant_object_id"`
	Depth              int32           `json:"depth"`
	CodePath           string          `json:"code_path"`
	NamePath           sql.NullString  `json:"name_path"`
	Metadata           json.RawMessage `json:"metadata"`
	RefreshedAt        time.Time       `json:"refreshed_at"`
}

type StandardObjectLink struct {
	ID               uuid.UUID       `json:"id"`
	LinkType         string          `json:"link_type"`
	SourceObjectID   uuid.UUID       `json:"source_object_id"`
	TargetObjectID   uuid.UUID       `json:"target_object_id"`
	TenantCode       string          `json:"tenant_code"`
	ValidityRange    string          `json:"validity_range"`
	TransactionRange string          `json:"transaction_range"`
	Attributes       json.RawMessage `json:"attributes"`
	CreatedBy        uuid.NullUUID   `json:"created_by"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedBy        uuid.NullUUID   `json:"updated_by"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type StandardObjectMetadatum struct {
	ID         uuid.UUID       `json:"id"`
	ObjectID   uuid.UUID       `json:"object_id"`
	TenantCode string          `json:"tenant_code"`
	MetaKey    string          `json:"meta_key"`
	MetaValue  json.RawMessage `json:"meta_value"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type StandardObjectMetric struct {
	ID          uuid.UUID       `json:"id"`
	ObjectID    uuid.NullUUID   `json:"object_id"`
	MetricType  string          `json:"metric_type"`
	MetricValue string          `json:"metric_value"`
	Labels      json.RawMessage `json:"labels"`
	TenantCode  string          `json:"tenant_code"`
	RecordedAt  time.Time       `json:"recorded_at"`
}

type StandardObjectSchema struct {
	ID                uuid.UUID       `json:"id"`
	ObjectType        string          `json:"object_type"`
	SchemaVersion     string          `json:"schema_version"`
	SchemaHash        string          `json:"schema_hash"`
	Definition        json.RawMessage `json:"definition"`
	DecBindings       json.RawMessage `json:"dec_bindings"`
	OclGuards         json.RawMessage `json:"ocl_guards"`
	GlossaryUrl       sql.NullString  `json:"glossary_url"`
	TimeConstraint    string          `json:"time_constraint"`
	TransactionPolicy string          `json:"transaction_policy"`
	PublishedAt       time.Time       `json:"published_at"`
	RollbackVersion   sql.NullString  `json:"rollback_version"`
	Maintainer        sql.NullString  `json:"maintainer"`
}

type StandardObjectTranslation struct {
	ID          uuid.UUID       `json:"id"`
	ObjectID    uuid.UUID       `json:"object_id"`
	TenantCode  string          `json:"tenant_code"`
	Locale      string          `json:"locale"`
	DisplayName sql.NullString  `json:"display_name"`
	Description sql.NullString  `json:"description"`
	Metadata    json.RawMessage `json:"metadata"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type StandardObjectVersion struct {
	ID               uuid.UUID       `json:"id"`
	ObjectID         uuid.UUID       `json:"object_id"`
	VersionCode      string          `json:"version_code"`
	EffectiveDate    time.Time       `json:"effective_date"`
	EndDate          sql.NullTime    `json:"end_date"`
	ValidityRange    string          `json:"validity_range"`
	TransactionRange string          `json:"transaction_range"`
	IsCurrent        bool            `json:"is_current"`
	Payload          json.RawMessage `json:"payload"`
	Audit            json.RawMessage `json:"audit"`
	Checksum         sql.NullString  `json:"checksum"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}
