// Code generated by ent, DO NOT EDIT.

package assignmenthistory

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the assignmenthistory type in the database.
	Label = "assignment_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAssignmentID holds the string denoting the assignment_id field in the database.
	FieldAssignmentID = "assignment_id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldEventDate holds the string denoting the event_date field in the database.
	FieldEventDate = "event_date"
	// FieldPreviousValues holds the string denoting the previous_values field in the database.
	FieldPreviousValues = "previous_values"
	// FieldNewValues holds the string denoting the new_values field in the database.
	FieldNewValues = "new_values"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldChangedBy holds the string denoting the changed_by field in the database.
	FieldChangedBy = "changed_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAssignment holds the string denoting the assignment edge name in mutations.
	EdgeAssignment = "assignment"
	// Table holds the table name of the assignmenthistory in the database.
	Table = "assignment_histories"
	// AssignmentTable is the table that holds the assignment relation/edge.
	AssignmentTable = "assignment_histories"
	// AssignmentInverseTable is the table name for the PositionAssignment entity.
	// It exists in this package in order to avoid circular dependency with the "positionassignment" package.
	AssignmentInverseTable = "position_assignments"
	// AssignmentColumn is the table column denoting the assignment relation/edge.
	AssignmentColumn = "assignment_id"
)

// Columns holds all SQL columns for assignmenthistory fields.
var Columns = []string{
	FieldID,
	FieldAssignmentID,
	FieldTenantID,
	FieldEventType,
	FieldEventDate,
	FieldPreviousValues,
	FieldNewValues,
	FieldReason,
	FieldChangedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// EventType defines the type for the "event_type" enum field.
type EventType string

// EventType values.
const (
	EventTypeCREATED  EventType = "CREATED"
	EventTypeUPDATED  EventType = "UPDATED"
	EventTypeENDED    EventType = "ENDED"
	EventTypeEXTENDED EventType = "EXTENDED"
)

func (et EventType) String() string {
	return string(et)
}

// EventTypeValidator is a validator for the "event_type" field enum values. It is called by the builders before save.
func EventTypeValidator(et EventType) error {
	switch et {
	case EventTypeCREATED, EventTypeUPDATED, EventTypeENDED, EventTypeEXTENDED:
		return nil
	default:
		return fmt.Errorf("assignmenthistory: invalid enum value for event_type field: %q", et)
	}
}

// OrderOption defines the ordering options for the AssignmentHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAssignmentID orders the results by the assignment_id field.
func ByAssignmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignmentID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByEventDate orders the results by the event_date field.
func ByEventDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventDate, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByChangedBy orders the results by the changed_by field.
func ByChangedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAssignmentField orders the results by assignment field.
func ByAssignmentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssignmentStep(), sql.OrderByField(field, opts...))
	}
}
func newAssignmentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssignmentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssignmentTable, AssignmentColumn),
	)
}
