// Code generated by ent, DO NOT EDIT.

package assignmenthistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gaogu/cube-castle/go-app/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLTE(FieldID, id))
}

// AssignmentID applies equality check predicate on the "assignment_id" field. It's identical to AssignmentIDEQ.
func AssignmentID(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldAssignmentID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldTenantID, v))
}

// EventDate applies equality check predicate on the "event_date" field. It's identical to EventDateEQ.
func EventDate(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldEventDate, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldReason, v))
}

// ChangedBy applies equality check predicate on the "changed_by" field. It's identical to ChangedByEQ.
func ChangedBy(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldChangedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// AssignmentIDEQ applies the EQ predicate on the "assignment_id" field.
func AssignmentIDEQ(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldAssignmentID, v))
}

// AssignmentIDNEQ applies the NEQ predicate on the "assignment_id" field.
func AssignmentIDNEQ(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNEQ(FieldAssignmentID, v))
}

// AssignmentIDIn applies the In predicate on the "assignment_id" field.
func AssignmentIDIn(vs ...uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIn(FieldAssignmentID, vs...))
}

// AssignmentIDNotIn applies the NotIn predicate on the "assignment_id" field.
func AssignmentIDNotIn(vs ...uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotIn(FieldAssignmentID, vs...))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLTE(FieldTenantID, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v EventType) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v EventType) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...EventType) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...EventType) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotIn(FieldEventType, vs...))
}

// EventDateEQ applies the EQ predicate on the "event_date" field.
func EventDateEQ(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldEventDate, v))
}

// EventDateNEQ applies the NEQ predicate on the "event_date" field.
func EventDateNEQ(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNEQ(FieldEventDate, v))
}

// EventDateIn applies the In predicate on the "event_date" field.
func EventDateIn(vs ...time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIn(FieldEventDate, vs...))
}

// EventDateNotIn applies the NotIn predicate on the "event_date" field.
func EventDateNotIn(vs ...time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotIn(FieldEventDate, vs...))
}

// EventDateGT applies the GT predicate on the "event_date" field.
func EventDateGT(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGT(FieldEventDate, v))
}

// EventDateGTE applies the GTE predicate on the "event_date" field.
func EventDateGTE(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGTE(FieldEventDate, v))
}

// EventDateLT applies the LT predicate on the "event_date" field.
func EventDateLT(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLT(FieldEventDate, v))
}

// EventDateLTE applies the LTE predicate on the "event_date" field.
func EventDateLTE(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLTE(FieldEventDate, v))
}

// PreviousValuesIsNil applies the IsNil predicate on the "previous_values" field.
func PreviousValuesIsNil() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIsNull(FieldPreviousValues))
}

// PreviousValuesNotNil applies the NotNil predicate on the "previous_values" field.
func PreviousValuesNotNil() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotNull(FieldPreviousValues))
}

// NewValuesIsNil applies the IsNil predicate on the "new_values" field.
func NewValuesIsNil() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIsNull(FieldNewValues))
}

// NewValuesNotNil applies the NotNil predicate on the "new_values" field.
func NewValuesNotNil() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotNull(FieldNewValues))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldContainsFold(FieldReason, v))
}

// ChangedByEQ applies the EQ predicate on the "changed_by" field.
func ChangedByEQ(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangedByNEQ applies the NEQ predicate on the "changed_by" field.
func ChangedByNEQ(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNEQ(FieldChangedBy, v))
}

// ChangedByIn applies the In predicate on the "changed_by" field.
func ChangedByIn(vs ...uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIn(FieldChangedBy, vs...))
}

// ChangedByNotIn applies the NotIn predicate on the "changed_by" field.
func ChangedByNotIn(vs ...uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotIn(FieldChangedBy, vs...))
}

// ChangedByGT applies the GT predicate on the "changed_by" field.
func ChangedByGT(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGT(FieldChangedBy, v))
}

// ChangedByGTE applies the GTE predicate on the "changed_by" field.
func ChangedByGTE(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGTE(FieldChangedBy, v))
}

// ChangedByLT applies the LT predicate on the "changed_by" field.
func ChangedByLT(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLT(FieldChangedBy, v))
}

// ChangedByLTE applies the LTE predicate on the "changed_by" field.
func ChangedByLTE(v uuid.UUID) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLTE(FieldChangedBy, v))
}

// ChangedByIsNil applies the IsNil predicate on the "changed_by" field.
func ChangedByIsNil() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIsNull(FieldChangedBy))
}

// ChangedByNotNil applies the NotNil predicate on the "changed_by" field.
func ChangedByNotNil() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotNull(FieldChangedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAssignment applies the HasEdge predicate on the "assignment" edge.
func HasAssignment() predicate.AssignmentHistory {
	return predicate.AssignmentHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignmentTable, AssignmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignmentWith applies the HasEdge predicate on the "assignment" edge with a given conditions (other predicates).
func HasAssignmentWith(preds ...predicate.PositionAssignment) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(func(s *sql.Selector) {
		step := newAssignmentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AssignmentHistory) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AssignmentHistory) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AssignmentHistory) predicate.AssignmentHistory {
	return predicate.AssignmentHistory(sql.NotPredicates(p))
}
