# golangci-lint configuration for Go Meta-Contract Editor Backend
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - testdata
    - bin
    - coverage
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gocyclo:
    min-complexity: 15
  
  maligned:
    suggest-new: true
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 120
  
  goimports:
    local-prefixes: github.com/gaogu/cube-castle
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  
  funlen:
    lines: 80
    statements: 40
  
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  
  depguard:
    list-type: blacklist
    packages:
      - log
    packages-with-error-message:
      - log: "logging is allowed only by our internal/logging package"
  
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
      - TODO
      - BUG
      - FIXME
  
  revive:
    min-confidence: 0
    rules:
      - name: atomic
      - name: line-length-limit
        arguments: [120]
      - name: argument-limit
        arguments: [8]
      - name: cyclomatic
        arguments: [15]
      - name: max-public-structs
        arguments: [10]

linters:
  disable-all: true
  enable:
    # Enable specific linters for code quality
    - errcheck          # Check for unhandled errors
    - gosimple          # Simplify code
    - govet             # Vet examines Go source code
    - ineffassign       # Detect ineffectual assignments
    - staticcheck       # Static analysis
    - typecheck         # Type checking
    - unused            # Check for unused code
    - bodyclose         # Check HTTP response body is closed
    - contextcheck      # Check context usage
    - cyclop            # Check cyclomatic complexity
    - dupl              # Check for duplicate code
    - errname           # Check error naming
    - errorlint         # Check error wrapping
    - exhaustive        # Check exhaustiveness of enum switch statements
    - exportloopref     # Check for loop variable references
    - forcetypeassert   # Find forced type assertions
    - funlen            # Check function length
    - gochecknoinits    # Check for init functions
    - gocognit          # Check cognitive complexity
    - goconst           # Find repeated strings that could be constants
    - gocritic          # Comprehensive Go linter
    - gocyclo           # Check cyclomatic complexity
    - godot             # Check comments end with period
    - gofmt             # Check if code is gofmt-ed
    - gofumpt           # Check if code is gofumpt-ed
    - goheader          # Check file headers
    - goimports         # Check import grouping and ordering
    - gomnd             # Check magic numbers
    - gomoddirectives   # Check go.mod directives
    - gomodguard        # Check module imports
    - goprintffuncname  # Check printf-like function names
    - gosec             # Security checker
    - lll               # Check line length
    - makezero          # Check slice initialization
    - misspell          # Check for misspellings
    - nakedret          # Check naked returns
    - nestif            # Check nested if statements
    - nilerr            # Check returning nil error
    - nilnil            # Check returning nil values
    - noctx             # Check HTTP requests use context
    - nolintlint        # Check nolint directives
    - prealloc          # Check slice preallocation
    - predeclared       # Check for shadowing predeclared identifiers
    - revive            # Fast, configurable, extensible linter
    - rowserrcheck      # Check SQL rows.Err()
    - sqlclosecheck     # Check SQL Close()
    - thelper           # Check test helpers
    - tparallel         # Check t.Parallel() usage
    - unconvert         # Check unnecessary type conversions
    - unparam           # Check unused function parameters
    - wastedassign      # Check wasted assignments
    - whitespace        # Check for trailing whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - goconst
        - dupl
    
    # Exclude some linters from running on mock files
    - path: mock.*\.go
      linters:
        - gomnd
        - govet
        - unparam
    
    # Exclude some linters from running on generated files
    - path: .*\.pb\.go
      linters:
        - all
    
    # Exclude specific issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    - text: "ST1003:"
      linters:
        - stylecheck
    
    # Allow complex main functions
    - path: cmd/
      text: "cyclomatic complexity"
      linters:
        - gocyclo
        - cyclop
        - gocognit
    
    # Allow long lines in comments
    - source: "//.*"
      linters:
        - lll
    
    # Allow magic numbers in test files
    - path: _test\.go
      text: "mnd:"
      linters:
        - gomnd

  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
        - goconst
        - gocritic
        - gomnd
        - misspell
      severity: warning
    
    - linters:
        - errcheck
        - gosec
        - govet
        - staticcheck
      severity: error