// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gaogu/cube-castle/go-app/ent/assignmenthistory"
	"github.com/gaogu/cube-castle/go-app/ent/positionassignment"
	"github.com/gaogu/cube-castle/go-app/ent/predicate"
	"github.com/google/uuid"
)

// AssignmentHistoryUpdate is the builder for updating AssignmentHistory entities.
type AssignmentHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *AssignmentHistoryMutation
}

// Where appends a list predicates to the AssignmentHistoryUpdate builder.
func (ahu *AssignmentHistoryUpdate) Where(ps ...predicate.AssignmentHistory) *AssignmentHistoryUpdate {
	ahu.mutation.Where(ps...)
	return ahu
}

// SetAssignmentID sets the "assignment_id" field.
func (ahu *AssignmentHistoryUpdate) SetAssignmentID(u uuid.UUID) *AssignmentHistoryUpdate {
	ahu.mutation.SetAssignmentID(u)
	return ahu
}

// SetNillableAssignmentID sets the "assignment_id" field if the given value is not nil.
func (ahu *AssignmentHistoryUpdate) SetNillableAssignmentID(u *uuid.UUID) *AssignmentHistoryUpdate {
	if u != nil {
		ahu.SetAssignmentID(*u)
	}
	return ahu
}

// SetTenantID sets the "tenant_id" field.
func (ahu *AssignmentHistoryUpdate) SetTenantID(u uuid.UUID) *AssignmentHistoryUpdate {
	ahu.mutation.SetTenantID(u)
	return ahu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (ahu *AssignmentHistoryUpdate) SetNillableTenantID(u *uuid.UUID) *AssignmentHistoryUpdate {
	if u != nil {
		ahu.SetTenantID(*u)
	}
	return ahu
}

// SetEventType sets the "event_type" field.
func (ahu *AssignmentHistoryUpdate) SetEventType(at assignmenthistory.EventType) *AssignmentHistoryUpdate {
	ahu.mutation.SetEventType(at)
	return ahu
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (ahu *AssignmentHistoryUpdate) SetNillableEventType(at *assignmenthistory.EventType) *AssignmentHistoryUpdate {
	if at != nil {
		ahu.SetEventType(*at)
	}
	return ahu
}

// SetEventDate sets the "event_date" field.
func (ahu *AssignmentHistoryUpdate) SetEventDate(t time.Time) *AssignmentHistoryUpdate {
	ahu.mutation.SetEventDate(t)
	return ahu
}

// SetNillableEventDate sets the "event_date" field if the given value is not nil.
func (ahu *AssignmentHistoryUpdate) SetNillableEventDate(t *time.Time) *AssignmentHistoryUpdate {
	if t != nil {
		ahu.SetEventDate(*t)
	}
	return ahu
}

// SetPreviousValues sets the "previous_values" field.
func (ahu *AssignmentHistoryUpdate) SetPreviousValues(m map[string]interface{}) *AssignmentHistoryUpdate {
	ahu.mutation.SetPreviousValues(m)
	return ahu
}

// ClearPreviousValues clears the value of the "previous_values" field.
func (ahu *AssignmentHistoryUpdate) ClearPreviousValues() *AssignmentHistoryUpdate {
	ahu.mutation.ClearPreviousValues()
	return ahu
}

// SetNewValues sets the "new_values" field.
func (ahu *AssignmentHistoryUpdate) SetNewValues(m map[string]interface{}) *AssignmentHistoryUpdate {
	ahu.mutation.SetNewValues(m)
	return ahu
}

// ClearNewValues clears the value of the "new_values" field.
func (ahu *AssignmentHistoryUpdate) ClearNewValues() *AssignmentHistoryUpdate {
	ahu.mutation.ClearNewValues()
	return ahu
}

// SetReason sets the "reason" field.
func (ahu *AssignmentHistoryUpdate) SetReason(s string) *AssignmentHistoryUpdate {
	ahu.mutation.SetReason(s)
	return ahu
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (ahu *AssignmentHistoryUpdate) SetNillableReason(s *string) *AssignmentHistoryUpdate {
	if s != nil {
		ahu.SetReason(*s)
	}
	return ahu
}

// ClearReason clears the value of the "reason" field.
func (ahu *AssignmentHistoryUpdate) ClearReason() *AssignmentHistoryUpdate {
	ahu.mutation.ClearReason()
	return ahu
}

// SetChangedBy sets the "changed_by" field.
func (ahu *AssignmentHistoryUpdate) SetChangedBy(u uuid.UUID) *AssignmentHistoryUpdate {
	ahu.mutation.SetChangedBy(u)
	return ahu
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (ahu *AssignmentHistoryUpdate) SetNillableChangedBy(u *uuid.UUID) *AssignmentHistoryUpdate {
	if u != nil {
		ahu.SetChangedBy(*u)
	}
	return ahu
}

// ClearChangedBy clears the value of the "changed_by" field.
func (ahu *AssignmentHistoryUpdate) ClearChangedBy() *AssignmentHistoryUpdate {
	ahu.mutation.ClearChangedBy()
	return ahu
}

// SetCreatedAt sets the "created_at" field.
func (ahu *AssignmentHistoryUpdate) SetCreatedAt(t time.Time) *AssignmentHistoryUpdate {
	ahu.mutation.SetCreatedAt(t)
	return ahu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ahu *AssignmentHistoryUpdate) SetNillableCreatedAt(t *time.Time) *AssignmentHistoryUpdate {
	if t != nil {
		ahu.SetCreatedAt(*t)
	}
	return ahu
}

// SetAssignment sets the "assignment" edge to the PositionAssignment entity.
func (ahu *AssignmentHistoryUpdate) SetAssignment(p *PositionAssignment) *AssignmentHistoryUpdate {
	return ahu.SetAssignmentID(p.ID)
}

// Mutation returns the AssignmentHistoryMutation object of the builder.
func (ahu *AssignmentHistoryUpdate) Mutation() *AssignmentHistoryMutation {
	return ahu.mutation
}

// ClearAssignment clears the "assignment" edge to the PositionAssignment entity.
func (ahu *AssignmentHistoryUpdate) ClearAssignment() *AssignmentHistoryUpdate {
	ahu.mutation.ClearAssignment()
	return ahu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ahu *AssignmentHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ahu.sqlSave, ahu.mutation, ahu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ahu *AssignmentHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := ahu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ahu *AssignmentHistoryUpdate) Exec(ctx context.Context) error {
	_, err := ahu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ahu *AssignmentHistoryUpdate) ExecX(ctx context.Context) {
	if err := ahu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ahu *AssignmentHistoryUpdate) check() error {
	if v, ok := ahu.mutation.EventType(); ok {
		if err := assignmenthistory.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AssignmentHistory.event_type": %w`, err)}
		}
	}
	if v, ok := ahu.mutation.Reason(); ok {
		if err := assignmenthistory.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AssignmentHistory.reason": %w`, err)}
		}
	}
	if ahu.mutation.AssignmentCleared() && len(ahu.mutation.AssignmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AssignmentHistory.assignment"`)
	}
	return nil
}

func (ahu *AssignmentHistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ahu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(assignmenthistory.Table, assignmenthistory.Columns, sqlgraph.NewFieldSpec(assignmenthistory.FieldID, field.TypeUUID))
	if ps := ahu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ahu.mutation.TenantID(); ok {
		_spec.SetField(assignmenthistory.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := ahu.mutation.EventType(); ok {
		_spec.SetField(assignmenthistory.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := ahu.mutation.EventDate(); ok {
		_spec.SetField(assignmenthistory.FieldEventDate, field.TypeTime, value)
	}
	if value, ok := ahu.mutation.PreviousValues(); ok {
		_spec.SetField(assignmenthistory.FieldPreviousValues, field.TypeJSON, value)
	}
	if ahu.mutation.PreviousValuesCleared() {
		_spec.ClearField(assignmenthistory.FieldPreviousValues, field.TypeJSON)
	}
	if value, ok := ahu.mutation.NewValues(); ok {
		_spec.SetField(assignmenthistory.FieldNewValues, field.TypeJSON, value)
	}
	if ahu.mutation.NewValuesCleared() {
		_spec.ClearField(assignmenthistory.FieldNewValues, field.TypeJSON)
	}
	if value, ok := ahu.mutation.Reason(); ok {
		_spec.SetField(assignmenthistory.FieldReason, field.TypeString, value)
	}
	if ahu.mutation.ReasonCleared() {
		_spec.ClearField(assignmenthistory.FieldReason, field.TypeString)
	}
	if value, ok := ahu.mutation.ChangedBy(); ok {
		_spec.SetField(assignmenthistory.FieldChangedBy, field.TypeUUID, value)
	}
	if ahu.mutation.ChangedByCleared() {
		_spec.ClearField(assignmenthistory.FieldChangedBy, field.TypeUUID)
	}
	if value, ok := ahu.mutation.CreatedAt(); ok {
		_spec.SetField(assignmenthistory.FieldCreatedAt, field.TypeTime, value)
	}
	if ahu.mutation.AssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmenthistory.AssignmentTable,
			Columns: []string{assignmenthistory.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ahu.mutation.AssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmenthistory.AssignmentTable,
			Columns: []string{assignmenthistory.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ahu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignmenthistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ahu.mutation.done = true
	return n, nil
}

// AssignmentHistoryUpdateOne is the builder for updating a single AssignmentHistory entity.
type AssignmentHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssignmentHistoryMutation
}

// SetAssignmentID sets the "assignment_id" field.
func (ahuo *AssignmentHistoryUpdateOne) SetAssignmentID(u uuid.UUID) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetAssignmentID(u)
	return ahuo
}

// SetNillableAssignmentID sets the "assignment_id" field if the given value is not nil.
func (ahuo *AssignmentHistoryUpdateOne) SetNillableAssignmentID(u *uuid.UUID) *AssignmentHistoryUpdateOne {
	if u != nil {
		ahuo.SetAssignmentID(*u)
	}
	return ahuo
}

// SetTenantID sets the "tenant_id" field.
func (ahuo *AssignmentHistoryUpdateOne) SetTenantID(u uuid.UUID) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetTenantID(u)
	return ahuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (ahuo *AssignmentHistoryUpdateOne) SetNillableTenantID(u *uuid.UUID) *AssignmentHistoryUpdateOne {
	if u != nil {
		ahuo.SetTenantID(*u)
	}
	return ahuo
}

// SetEventType sets the "event_type" field.
func (ahuo *AssignmentHistoryUpdateOne) SetEventType(at assignmenthistory.EventType) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetEventType(at)
	return ahuo
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (ahuo *AssignmentHistoryUpdateOne) SetNillableEventType(at *assignmenthistory.EventType) *AssignmentHistoryUpdateOne {
	if at != nil {
		ahuo.SetEventType(*at)
	}
	return ahuo
}

// SetEventDate sets the "event_date" field.
func (ahuo *AssignmentHistoryUpdateOne) SetEventDate(t time.Time) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetEventDate(t)
	return ahuo
}

// SetNillableEventDate sets the "event_date" field if the given value is not nil.
func (ahuo *AssignmentHistoryUpdateOne) SetNillableEventDate(t *time.Time) *AssignmentHistoryUpdateOne {
	if t != nil {
		ahuo.SetEventDate(*t)
	}
	return ahuo
}

// SetPreviousValues sets the "previous_values" field.
func (ahuo *AssignmentHistoryUpdateOne) SetPreviousValues(m map[string]interface{}) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetPreviousValues(m)
	return ahuo
}

// ClearPreviousValues clears the value of the "previous_values" field.
func (ahuo *AssignmentHistoryUpdateOne) ClearPreviousValues() *AssignmentHistoryUpdateOne {
	ahuo.mutation.ClearPreviousValues()
	return ahuo
}

// SetNewValues sets the "new_values" field.
func (ahuo *AssignmentHistoryUpdateOne) SetNewValues(m map[string]interface{}) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetNewValues(m)
	return ahuo
}

// ClearNewValues clears the value of the "new_values" field.
func (ahuo *AssignmentHistoryUpdateOne) ClearNewValues() *AssignmentHistoryUpdateOne {
	ahuo.mutation.ClearNewValues()
	return ahuo
}

// SetReason sets the "reason" field.
func (ahuo *AssignmentHistoryUpdateOne) SetReason(s string) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetReason(s)
	return ahuo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (ahuo *AssignmentHistoryUpdateOne) SetNillableReason(s *string) *AssignmentHistoryUpdateOne {
	if s != nil {
		ahuo.SetReason(*s)
	}
	return ahuo
}

// ClearReason clears the value of the "reason" field.
func (ahuo *AssignmentHistoryUpdateOne) ClearReason() *AssignmentHistoryUpdateOne {
	ahuo.mutation.ClearReason()
	return ahuo
}

// SetChangedBy sets the "changed_by" field.
func (ahuo *AssignmentHistoryUpdateOne) SetChangedBy(u uuid.UUID) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetChangedBy(u)
	return ahuo
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (ahuo *AssignmentHistoryUpdateOne) SetNillableChangedBy(u *uuid.UUID) *AssignmentHistoryUpdateOne {
	if u != nil {
		ahuo.SetChangedBy(*u)
	}
	return ahuo
}

// ClearChangedBy clears the value of the "changed_by" field.
func (ahuo *AssignmentHistoryUpdateOne) ClearChangedBy() *AssignmentHistoryUpdateOne {
	ahuo.mutation.ClearChangedBy()
	return ahuo
}

// SetCreatedAt sets the "created_at" field.
func (ahuo *AssignmentHistoryUpdateOne) SetCreatedAt(t time.Time) *AssignmentHistoryUpdateOne {
	ahuo.mutation.SetCreatedAt(t)
	return ahuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ahuo *AssignmentHistoryUpdateOne) SetNillableCreatedAt(t *time.Time) *AssignmentHistoryUpdateOne {
	if t != nil {
		ahuo.SetCreatedAt(*t)
	}
	return ahuo
}

// SetAssignment sets the "assignment" edge to the PositionAssignment entity.
func (ahuo *AssignmentHistoryUpdateOne) SetAssignment(p *PositionAssignment) *AssignmentHistoryUpdateOne {
	return ahuo.SetAssignmentID(p.ID)
}

// Mutation returns the AssignmentHistoryMutation object of the builder.
func (ahuo *AssignmentHistoryUpdateOne) Mutation() *AssignmentHistoryMutation {
	return ahuo.mutation
}

// ClearAssignment clears the "assignment" edge to the PositionAssignment entity.
func (ahuo *AssignmentHistoryUpdateOne) ClearAssignment() *AssignmentHistoryUpdateOne {
	ahuo.mutation.ClearAssignment()
	return ahuo
}

// Where appends a list predicates to the AssignmentHistoryUpdate builder.
func (ahuo *AssignmentHistoryUpdateOne) Where(ps ...predicate.AssignmentHistory) *AssignmentHistoryUpdateOne {
	ahuo.mutation.Where(ps...)
	return ahuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ahuo *AssignmentHistoryUpdateOne) Select(field string, fields ...string) *AssignmentHistoryUpdateOne {
	ahuo.fields = append([]string{field}, fields...)
	return ahuo
}

// Save executes the query and returns the updated AssignmentHistory entity.
func (ahuo *AssignmentHistoryUpdateOne) Save(ctx context.Context) (*AssignmentHistory, error) {
	return withHooks(ctx, ahuo.sqlSave, ahuo.mutation, ahuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ahuo *AssignmentHistoryUpdateOne) SaveX(ctx context.Context) *AssignmentHistory {
	node, err := ahuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ahuo *AssignmentHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := ahuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ahuo *AssignmentHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := ahuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ahuo *AssignmentHistoryUpdateOne) check() error {
	if v, ok := ahuo.mutation.EventType(); ok {
		if err := assignmenthistory.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AssignmentHistory.event_type": %w`, err)}
		}
	}
	if v, ok := ahuo.mutation.Reason(); ok {
		if err := assignmenthistory.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AssignmentHistory.reason": %w`, err)}
		}
	}
	if ahuo.mutation.AssignmentCleared() && len(ahuo.mutation.AssignmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AssignmentHistory.assignment"`)
	}
	return nil
}

func (ahuo *AssignmentHistoryUpdateOne) sqlSave(ctx context.Context) (_node *AssignmentHistory, err error) {
	if err := ahuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(assignmenthistory.Table, assignmenthistory.Columns, sqlgraph.NewFieldSpec(assignmenthistory.FieldID, field.TypeUUID))
	id, ok := ahuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AssignmentHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ahuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assignmenthistory.FieldID)
		for _, f := range fields {
			if !assignmenthistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assignmenthistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ahuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ahuo.mutation.TenantID(); ok {
		_spec.SetField(assignmenthistory.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := ahuo.mutation.EventType(); ok {
		_spec.SetField(assignmenthistory.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := ahuo.mutation.EventDate(); ok {
		_spec.SetField(assignmenthistory.FieldEventDate, field.TypeTime, value)
	}
	if value, ok := ahuo.mutation.PreviousValues(); ok {
		_spec.SetField(assignmenthistory.FieldPreviousValues, field.TypeJSON, value)
	}
	if ahuo.mutation.PreviousValuesCleared() {
		_spec.ClearField(assignmenthistory.FieldPreviousValues, field.TypeJSON)
	}
	if value, ok := ahuo.mutation.NewValues(); ok {
		_spec.SetField(assignmenthistory.FieldNewValues, field.TypeJSON, value)
	}
	if ahuo.mutation.NewValuesCleared() {
		_spec.ClearField(assignmenthistory.FieldNewValues, field.TypeJSON)
	}
	if value, ok := ahuo.mutation.Reason(); ok {
		_spec.SetField(assignmenthistory.FieldReason, field.TypeString, value)
	}
	if ahuo.mutation.ReasonCleared() {
		_spec.ClearField(assignmenthistory.FieldReason, field.TypeString)
	}
	if value, ok := ahuo.mutation.ChangedBy(); ok {
		_spec.SetField(assignmenthistory.FieldChangedBy, field.TypeUUID, value)
	}
	if ahuo.mutation.ChangedByCleared() {
		_spec.ClearField(assignmenthistory.FieldChangedBy, field.TypeUUID)
	}
	if value, ok := ahuo.mutation.CreatedAt(); ok {
		_spec.SetField(assignmenthistory.FieldCreatedAt, field.TypeTime, value)
	}
	if ahuo.mutation.AssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmenthistory.AssignmentTable,
			Columns: []string{assignmenthistory.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ahuo.mutation.AssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmenthistory.AssignmentTable,
			Columns: []string{assignmenthistory.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AssignmentHistory{config: ahuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ahuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignmenthistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ahuo.mutation.done = true
	return _node, nil
}
