// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gaogu/cube-castle/go-app/ent/organizationunit"
	"github.com/gaogu/cube-castle/go-app/ent/position"
	"github.com/gaogu/cube-castle/go-app/ent/predicate"
	"github.com/google/uuid"
)

// OrganizationUnitUpdate is the builder for updating OrganizationUnit entities.
type OrganizationUnitUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationUnitMutation
}

// Where appends a list predicates to the OrganizationUnitUpdate builder.
func (ouu *OrganizationUnitUpdate) Where(ps ...predicate.OrganizationUnit) *OrganizationUnitUpdate {
	ouu.mutation.Where(ps...)
	return ouu
}

// SetUnitType sets the "unit_type" field.
func (ouu *OrganizationUnitUpdate) SetUnitType(ot organizationunit.UnitType) *OrganizationUnitUpdate {
	ouu.mutation.SetUnitType(ot)
	return ouu
}

// SetNillableUnitType sets the "unit_type" field if the given value is not nil.
func (ouu *OrganizationUnitUpdate) SetNillableUnitType(ot *organizationunit.UnitType) *OrganizationUnitUpdate {
	if ot != nil {
		ouu.SetUnitType(*ot)
	}
	return ouu
}

// SetName sets the "name" field.
func (ouu *OrganizationUnitUpdate) SetName(s string) *OrganizationUnitUpdate {
	ouu.mutation.SetName(s)
	return ouu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ouu *OrganizationUnitUpdate) SetNillableName(s *string) *OrganizationUnitUpdate {
	if s != nil {
		ouu.SetName(*s)
	}
	return ouu
}

// SetDescription sets the "description" field.
func (ouu *OrganizationUnitUpdate) SetDescription(s string) *OrganizationUnitUpdate {
	ouu.mutation.SetDescription(s)
	return ouu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ouu *OrganizationUnitUpdate) SetNillableDescription(s *string) *OrganizationUnitUpdate {
	if s != nil {
		ouu.SetDescription(*s)
	}
	return ouu
}

// ClearDescription clears the value of the "description" field.
func (ouu *OrganizationUnitUpdate) ClearDescription() *OrganizationUnitUpdate {
	ouu.mutation.ClearDescription()
	return ouu
}

// SetParentUnitID sets the "parent_unit_id" field.
func (ouu *OrganizationUnitUpdate) SetParentUnitID(u uuid.UUID) *OrganizationUnitUpdate {
	ouu.mutation.SetParentUnitID(u)
	return ouu
}

// SetNillableParentUnitID sets the "parent_unit_id" field if the given value is not nil.
func (ouu *OrganizationUnitUpdate) SetNillableParentUnitID(u *uuid.UUID) *OrganizationUnitUpdate {
	if u != nil {
		ouu.SetParentUnitID(*u)
	}
	return ouu
}

// ClearParentUnitID clears the value of the "parent_unit_id" field.
func (ouu *OrganizationUnitUpdate) ClearParentUnitID() *OrganizationUnitUpdate {
	ouu.mutation.ClearParentUnitID()
	return ouu
}

// SetLevel sets the "level" field.
func (ouu *OrganizationUnitUpdate) SetLevel(i int) *OrganizationUnitUpdate {
	ouu.mutation.ResetLevel()
	ouu.mutation.SetLevel(i)
	return ouu
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (ouu *OrganizationUnitUpdate) SetNillableLevel(i *int) *OrganizationUnitUpdate {
	if i != nil {
		ouu.SetLevel(*i)
	}
	return ouu
}

// AddLevel adds i to the "level" field.
func (ouu *OrganizationUnitUpdate) AddLevel(i int) *OrganizationUnitUpdate {
	ouu.mutation.AddLevel(i)
	return ouu
}

// SetStatus sets the "status" field.
func (ouu *OrganizationUnitUpdate) SetStatus(o organizationunit.Status) *OrganizationUnitUpdate {
	ouu.mutation.SetStatus(o)
	return ouu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ouu *OrganizationUnitUpdate) SetNillableStatus(o *organizationunit.Status) *OrganizationUnitUpdate {
	if o != nil {
		ouu.SetStatus(*o)
	}
	return ouu
}

// SetProfile sets the "profile" field.
func (ouu *OrganizationUnitUpdate) SetProfile(m map[string]interface{}) *OrganizationUnitUpdate {
	ouu.mutation.SetProfile(m)
	return ouu
}

// ClearProfile clears the value of the "profile" field.
func (ouu *OrganizationUnitUpdate) ClearProfile() *OrganizationUnitUpdate {
	ouu.mutation.ClearProfile()
	return ouu
}

// SetUpdatedAt sets the "updated_at" field.
func (ouu *OrganizationUnitUpdate) SetUpdatedAt(t time.Time) *OrganizationUnitUpdate {
	ouu.mutation.SetUpdatedAt(t)
	return ouu
}

// SetParentID sets the "parent" edge to the OrganizationUnit entity by ID.
func (ouu *OrganizationUnitUpdate) SetParentID(id uuid.UUID) *OrganizationUnitUpdate {
	ouu.mutation.SetParentID(id)
	return ouu
}

// SetNillableParentID sets the "parent" edge to the OrganizationUnit entity by ID if the given value is not nil.
func (ouu *OrganizationUnitUpdate) SetNillableParentID(id *uuid.UUID) *OrganizationUnitUpdate {
	if id != nil {
		ouu = ouu.SetParentID(*id)
	}
	return ouu
}

// SetParent sets the "parent" edge to the OrganizationUnit entity.
func (ouu *OrganizationUnitUpdate) SetParent(o *OrganizationUnit) *OrganizationUnitUpdate {
	return ouu.SetParentID(o.ID)
}

// AddChildIDs adds the "children" edge to the OrganizationUnit entity by IDs.
func (ouu *OrganizationUnitUpdate) AddChildIDs(ids ...uuid.UUID) *OrganizationUnitUpdate {
	ouu.mutation.AddChildIDs(ids...)
	return ouu
}

// AddChildren adds the "children" edges to the OrganizationUnit entity.
func (ouu *OrganizationUnitUpdate) AddChildren(o ...*OrganizationUnit) *OrganizationUnitUpdate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouu.AddChildIDs(ids...)
}

// AddPositionIDs adds the "positions" edge to the Position entity by IDs.
func (ouu *OrganizationUnitUpdate) AddPositionIDs(ids ...uuid.UUID) *OrganizationUnitUpdate {
	ouu.mutation.AddPositionIDs(ids...)
	return ouu
}

// AddPositions adds the "positions" edges to the Position entity.
func (ouu *OrganizationUnitUpdate) AddPositions(p ...*Position) *OrganizationUnitUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ouu.AddPositionIDs(ids...)
}

// Mutation returns the OrganizationUnitMutation object of the builder.
func (ouu *OrganizationUnitUpdate) Mutation() *OrganizationUnitMutation {
	return ouu.mutation
}

// ClearParent clears the "parent" edge to the OrganizationUnit entity.
func (ouu *OrganizationUnitUpdate) ClearParent() *OrganizationUnitUpdate {
	ouu.mutation.ClearParent()
	return ouu
}

// ClearChildren clears all "children" edges to the OrganizationUnit entity.
func (ouu *OrganizationUnitUpdate) ClearChildren() *OrganizationUnitUpdate {
	ouu.mutation.ClearChildren()
	return ouu
}

// RemoveChildIDs removes the "children" edge to OrganizationUnit entities by IDs.
func (ouu *OrganizationUnitUpdate) RemoveChildIDs(ids ...uuid.UUID) *OrganizationUnitUpdate {
	ouu.mutation.RemoveChildIDs(ids...)
	return ouu
}

// RemoveChildren removes "children" edges to OrganizationUnit entities.
func (ouu *OrganizationUnitUpdate) RemoveChildren(o ...*OrganizationUnit) *OrganizationUnitUpdate {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouu.RemoveChildIDs(ids...)
}

// ClearPositions clears all "positions" edges to the Position entity.
func (ouu *OrganizationUnitUpdate) ClearPositions() *OrganizationUnitUpdate {
	ouu.mutation.ClearPositions()
	return ouu
}

// RemovePositionIDs removes the "positions" edge to Position entities by IDs.
func (ouu *OrganizationUnitUpdate) RemovePositionIDs(ids ...uuid.UUID) *OrganizationUnitUpdate {
	ouu.mutation.RemovePositionIDs(ids...)
	return ouu
}

// RemovePositions removes "positions" edges to Position entities.
func (ouu *OrganizationUnitUpdate) RemovePositions(p ...*Position) *OrganizationUnitUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ouu.RemovePositionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ouu *OrganizationUnitUpdate) Save(ctx context.Context) (int, error) {
	ouu.defaults()
	return withHooks(ctx, ouu.sqlSave, ouu.mutation, ouu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouu *OrganizationUnitUpdate) SaveX(ctx context.Context) int {
	affected, err := ouu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ouu *OrganizationUnitUpdate) Exec(ctx context.Context) error {
	_, err := ouu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouu *OrganizationUnitUpdate) ExecX(ctx context.Context) {
	if err := ouu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouu *OrganizationUnitUpdate) defaults() {
	if _, ok := ouu.mutation.UpdatedAt(); !ok {
		v := organizationunit.UpdateDefaultUpdatedAt()
		ouu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouu *OrganizationUnitUpdate) check() error {
	if v, ok := ouu.mutation.UnitType(); ok {
		if err := organizationunit.UnitTypeValidator(v); err != nil {
			return &ValidationError{Name: "unit_type", err: fmt.Errorf(`ent: validator failed for field "OrganizationUnit.unit_type": %w`, err)}
		}
	}
	if v, ok := ouu.mutation.Name(); ok {
		if err := organizationunit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrganizationUnit.name": %w`, err)}
		}
	}
	if v, ok := ouu.mutation.Description(); ok {
		if err := organizationunit.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "OrganizationUnit.description": %w`, err)}
		}
	}
	if v, ok := ouu.mutation.Status(); ok {
		if err := organizationunit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrganizationUnit.status": %w`, err)}
		}
	}
	return nil
}

func (ouu *OrganizationUnitUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ouu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationunit.Table, organizationunit.Columns, sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID))
	if ps := ouu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouu.mutation.UnitType(); ok {
		_spec.SetField(organizationunit.FieldUnitType, field.TypeEnum, value)
	}
	if value, ok := ouu.mutation.Name(); ok {
		_spec.SetField(organizationunit.FieldName, field.TypeString, value)
	}
	if value, ok := ouu.mutation.Description(); ok {
		_spec.SetField(organizationunit.FieldDescription, field.TypeString, value)
	}
	if ouu.mutation.DescriptionCleared() {
		_spec.ClearField(organizationunit.FieldDescription, field.TypeString)
	}
	if value, ok := ouu.mutation.Level(); ok {
		_spec.SetField(organizationunit.FieldLevel, field.TypeInt, value)
	}
	if value, ok := ouu.mutation.AddedLevel(); ok {
		_spec.AddField(organizationunit.FieldLevel, field.TypeInt, value)
	}
	if value, ok := ouu.mutation.Status(); ok {
		_spec.SetField(organizationunit.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ouu.mutation.Profile(); ok {
		_spec.SetField(organizationunit.FieldProfile, field.TypeJSON, value)
	}
	if ouu.mutation.ProfileCleared() {
		_spec.ClearField(organizationunit.FieldProfile, field.TypeJSON)
	}
	if value, ok := ouu.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationunit.FieldUpdatedAt, field.TypeTime, value)
	}
	if ouu.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organizationunit.ParentTable,
			Columns: []string{organizationunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouu.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organizationunit.ParentTable,
			Columns: []string{organizationunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.ChildrenTable,
			Columns: []string{organizationunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouu.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !ouu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.ChildrenTable,
			Columns: []string{organizationunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouu.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.ChildrenTable,
			Columns: []string{organizationunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouu.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.PositionsTable,
			Columns: []string{organizationunit.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouu.mutation.RemovedPositionsIDs(); len(nodes) > 0 && !ouu.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.PositionsTable,
			Columns: []string{organizationunit.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouu.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.PositionsTable,
			Columns: []string{organizationunit.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ouu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationunit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ouu.mutation.done = true
	return n, nil
}

// OrganizationUnitUpdateOne is the builder for updating a single OrganizationUnit entity.
type OrganizationUnitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationUnitMutation
}

// SetUnitType sets the "unit_type" field.
func (ouuo *OrganizationUnitUpdateOne) SetUnitType(ot organizationunit.UnitType) *OrganizationUnitUpdateOne {
	ouuo.mutation.SetUnitType(ot)
	return ouuo
}

// SetNillableUnitType sets the "unit_type" field if the given value is not nil.
func (ouuo *OrganizationUnitUpdateOne) SetNillableUnitType(ot *organizationunit.UnitType) *OrganizationUnitUpdateOne {
	if ot != nil {
		ouuo.SetUnitType(*ot)
	}
	return ouuo
}

// SetName sets the "name" field.
func (ouuo *OrganizationUnitUpdateOne) SetName(s string) *OrganizationUnitUpdateOne {
	ouuo.mutation.SetName(s)
	return ouuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ouuo *OrganizationUnitUpdateOne) SetNillableName(s *string) *OrganizationUnitUpdateOne {
	if s != nil {
		ouuo.SetName(*s)
	}
	return ouuo
}

// SetDescription sets the "description" field.
func (ouuo *OrganizationUnitUpdateOne) SetDescription(s string) *OrganizationUnitUpdateOne {
	ouuo.mutation.SetDescription(s)
	return ouuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ouuo *OrganizationUnitUpdateOne) SetNillableDescription(s *string) *OrganizationUnitUpdateOne {
	if s != nil {
		ouuo.SetDescription(*s)
	}
	return ouuo
}

// ClearDescription clears the value of the "description" field.
func (ouuo *OrganizationUnitUpdateOne) ClearDescription() *OrganizationUnitUpdateOne {
	ouuo.mutation.ClearDescription()
	return ouuo
}

// SetParentUnitID sets the "parent_unit_id" field.
func (ouuo *OrganizationUnitUpdateOne) SetParentUnitID(u uuid.UUID) *OrganizationUnitUpdateOne {
	ouuo.mutation.SetParentUnitID(u)
	return ouuo
}

// SetNillableParentUnitID sets the "parent_unit_id" field if the given value is not nil.
func (ouuo *OrganizationUnitUpdateOne) SetNillableParentUnitID(u *uuid.UUID) *OrganizationUnitUpdateOne {
	if u != nil {
		ouuo.SetParentUnitID(*u)
	}
	return ouuo
}

// ClearParentUnitID clears the value of the "parent_unit_id" field.
func (ouuo *OrganizationUnitUpdateOne) ClearParentUnitID() *OrganizationUnitUpdateOne {
	ouuo.mutation.ClearParentUnitID()
	return ouuo
}

// SetLevel sets the "level" field.
func (ouuo *OrganizationUnitUpdateOne) SetLevel(i int) *OrganizationUnitUpdateOne {
	ouuo.mutation.ResetLevel()
	ouuo.mutation.SetLevel(i)
	return ouuo
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (ouuo *OrganizationUnitUpdateOne) SetNillableLevel(i *int) *OrganizationUnitUpdateOne {
	if i != nil {
		ouuo.SetLevel(*i)
	}
	return ouuo
}

// AddLevel adds i to the "level" field.
func (ouuo *OrganizationUnitUpdateOne) AddLevel(i int) *OrganizationUnitUpdateOne {
	ouuo.mutation.AddLevel(i)
	return ouuo
}

// SetStatus sets the "status" field.
func (ouuo *OrganizationUnitUpdateOne) SetStatus(o organizationunit.Status) *OrganizationUnitUpdateOne {
	ouuo.mutation.SetStatus(o)
	return ouuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ouuo *OrganizationUnitUpdateOne) SetNillableStatus(o *organizationunit.Status) *OrganizationUnitUpdateOne {
	if o != nil {
		ouuo.SetStatus(*o)
	}
	return ouuo
}

// SetProfile sets the "profile" field.
func (ouuo *OrganizationUnitUpdateOne) SetProfile(m map[string]interface{}) *OrganizationUnitUpdateOne {
	ouuo.mutation.SetProfile(m)
	return ouuo
}

// ClearProfile clears the value of the "profile" field.
func (ouuo *OrganizationUnitUpdateOne) ClearProfile() *OrganizationUnitUpdateOne {
	ouuo.mutation.ClearProfile()
	return ouuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ouuo *OrganizationUnitUpdateOne) SetUpdatedAt(t time.Time) *OrganizationUnitUpdateOne {
	ouuo.mutation.SetUpdatedAt(t)
	return ouuo
}

// SetParentID sets the "parent" edge to the OrganizationUnit entity by ID.
func (ouuo *OrganizationUnitUpdateOne) SetParentID(id uuid.UUID) *OrganizationUnitUpdateOne {
	ouuo.mutation.SetParentID(id)
	return ouuo
}

// SetNillableParentID sets the "parent" edge to the OrganizationUnit entity by ID if the given value is not nil.
func (ouuo *OrganizationUnitUpdateOne) SetNillableParentID(id *uuid.UUID) *OrganizationUnitUpdateOne {
	if id != nil {
		ouuo = ouuo.SetParentID(*id)
	}
	return ouuo
}

// SetParent sets the "parent" edge to the OrganizationUnit entity.
func (ouuo *OrganizationUnitUpdateOne) SetParent(o *OrganizationUnit) *OrganizationUnitUpdateOne {
	return ouuo.SetParentID(o.ID)
}

// AddChildIDs adds the "children" edge to the OrganizationUnit entity by IDs.
func (ouuo *OrganizationUnitUpdateOne) AddChildIDs(ids ...uuid.UUID) *OrganizationUnitUpdateOne {
	ouuo.mutation.AddChildIDs(ids...)
	return ouuo
}

// AddChildren adds the "children" edges to the OrganizationUnit entity.
func (ouuo *OrganizationUnitUpdateOne) AddChildren(o ...*OrganizationUnit) *OrganizationUnitUpdateOne {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouuo.AddChildIDs(ids...)
}

// AddPositionIDs adds the "positions" edge to the Position entity by IDs.
func (ouuo *OrganizationUnitUpdateOne) AddPositionIDs(ids ...uuid.UUID) *OrganizationUnitUpdateOne {
	ouuo.mutation.AddPositionIDs(ids...)
	return ouuo
}

// AddPositions adds the "positions" edges to the Position entity.
func (ouuo *OrganizationUnitUpdateOne) AddPositions(p ...*Position) *OrganizationUnitUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ouuo.AddPositionIDs(ids...)
}

// Mutation returns the OrganizationUnitMutation object of the builder.
func (ouuo *OrganizationUnitUpdateOne) Mutation() *OrganizationUnitMutation {
	return ouuo.mutation
}

// ClearParent clears the "parent" edge to the OrganizationUnit entity.
func (ouuo *OrganizationUnitUpdateOne) ClearParent() *OrganizationUnitUpdateOne {
	ouuo.mutation.ClearParent()
	return ouuo
}

// ClearChildren clears all "children" edges to the OrganizationUnit entity.
func (ouuo *OrganizationUnitUpdateOne) ClearChildren() *OrganizationUnitUpdateOne {
	ouuo.mutation.ClearChildren()
	return ouuo
}

// RemoveChildIDs removes the "children" edge to OrganizationUnit entities by IDs.
func (ouuo *OrganizationUnitUpdateOne) RemoveChildIDs(ids ...uuid.UUID) *OrganizationUnitUpdateOne {
	ouuo.mutation.RemoveChildIDs(ids...)
	return ouuo
}

// RemoveChildren removes "children" edges to OrganizationUnit entities.
func (ouuo *OrganizationUnitUpdateOne) RemoveChildren(o ...*OrganizationUnit) *OrganizationUnitUpdateOne {
	ids := make([]uuid.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return ouuo.RemoveChildIDs(ids...)
}

// ClearPositions clears all "positions" edges to the Position entity.
func (ouuo *OrganizationUnitUpdateOne) ClearPositions() *OrganizationUnitUpdateOne {
	ouuo.mutation.ClearPositions()
	return ouuo
}

// RemovePositionIDs removes the "positions" edge to Position entities by IDs.
func (ouuo *OrganizationUnitUpdateOne) RemovePositionIDs(ids ...uuid.UUID) *OrganizationUnitUpdateOne {
	ouuo.mutation.RemovePositionIDs(ids...)
	return ouuo
}

// RemovePositions removes "positions" edges to Position entities.
func (ouuo *OrganizationUnitUpdateOne) RemovePositions(p ...*Position) *OrganizationUnitUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return ouuo.RemovePositionIDs(ids...)
}

// Where appends a list predicates to the OrganizationUnitUpdate builder.
func (ouuo *OrganizationUnitUpdateOne) Where(ps ...predicate.OrganizationUnit) *OrganizationUnitUpdateOne {
	ouuo.mutation.Where(ps...)
	return ouuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouuo *OrganizationUnitUpdateOne) Select(field string, fields ...string) *OrganizationUnitUpdateOne {
	ouuo.fields = append([]string{field}, fields...)
	return ouuo
}

// Save executes the query and returns the updated OrganizationUnit entity.
func (ouuo *OrganizationUnitUpdateOne) Save(ctx context.Context) (*OrganizationUnit, error) {
	ouuo.defaults()
	return withHooks(ctx, ouuo.sqlSave, ouuo.mutation, ouuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouuo *OrganizationUnitUpdateOne) SaveX(ctx context.Context) *OrganizationUnit {
	node, err := ouuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouuo *OrganizationUnitUpdateOne) Exec(ctx context.Context) error {
	_, err := ouuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouuo *OrganizationUnitUpdateOne) ExecX(ctx context.Context) {
	if err := ouuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouuo *OrganizationUnitUpdateOne) defaults() {
	if _, ok := ouuo.mutation.UpdatedAt(); !ok {
		v := organizationunit.UpdateDefaultUpdatedAt()
		ouuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouuo *OrganizationUnitUpdateOne) check() error {
	if v, ok := ouuo.mutation.UnitType(); ok {
		if err := organizationunit.UnitTypeValidator(v); err != nil {
			return &ValidationError{Name: "unit_type", err: fmt.Errorf(`ent: validator failed for field "OrganizationUnit.unit_type": %w`, err)}
		}
	}
	if v, ok := ouuo.mutation.Name(); ok {
		if err := organizationunit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OrganizationUnit.name": %w`, err)}
		}
	}
	if v, ok := ouuo.mutation.Description(); ok {
		if err := organizationunit.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "OrganizationUnit.description": %w`, err)}
		}
	}
	if v, ok := ouuo.mutation.Status(); ok {
		if err := organizationunit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrganizationUnit.status": %w`, err)}
		}
	}
	return nil
}

func (ouuo *OrganizationUnitUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationUnit, err error) {
	if err := ouuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationunit.Table, organizationunit.Columns, sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID))
	id, ok := ouuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrganizationUnit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationunit.FieldID)
		for _, f := range fields {
			if !organizationunit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organizationunit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouuo.mutation.UnitType(); ok {
		_spec.SetField(organizationunit.FieldUnitType, field.TypeEnum, value)
	}
	if value, ok := ouuo.mutation.Name(); ok {
		_spec.SetField(organizationunit.FieldName, field.TypeString, value)
	}
	if value, ok := ouuo.mutation.Description(); ok {
		_spec.SetField(organizationunit.FieldDescription, field.TypeString, value)
	}
	if ouuo.mutation.DescriptionCleared() {
		_spec.ClearField(organizationunit.FieldDescription, field.TypeString)
	}
	if value, ok := ouuo.mutation.Level(); ok {
		_spec.SetField(organizationunit.FieldLevel, field.TypeInt, value)
	}
	if value, ok := ouuo.mutation.AddedLevel(); ok {
		_spec.AddField(organizationunit.FieldLevel, field.TypeInt, value)
	}
	if value, ok := ouuo.mutation.Status(); ok {
		_spec.SetField(organizationunit.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ouuo.mutation.Profile(); ok {
		_spec.SetField(organizationunit.FieldProfile, field.TypeJSON, value)
	}
	if ouuo.mutation.ProfileCleared() {
		_spec.ClearField(organizationunit.FieldProfile, field.TypeJSON)
	}
	if value, ok := ouuo.mutation.UpdatedAt(); ok {
		_spec.SetField(organizationunit.FieldUpdatedAt, field.TypeTime, value)
	}
	if ouuo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organizationunit.ParentTable,
			Columns: []string{organizationunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouuo.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   organizationunit.ParentTable,
			Columns: []string{organizationunit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.ChildrenTable,
			Columns: []string{organizationunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouuo.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !ouuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.ChildrenTable,
			Columns: []string{organizationunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouuo.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.ChildrenTable,
			Columns: []string{organizationunit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ouuo.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.PositionsTable,
			Columns: []string{organizationunit.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouuo.mutation.RemovedPositionsIDs(); len(nodes) > 0 && !ouuo.mutation.PositionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.PositionsTable,
			Columns: []string{organizationunit.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouuo.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organizationunit.PositionsTable,
			Columns: []string{organizationunit.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrganizationUnit{config: ouuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationunit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouuo.mutation.done = true
	return _node, nil
}
