// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gaogu/cube-castle/go-app/ent/organizationunit"
	"github.com/gaogu/cube-castle/go-app/ent/predicate"
)

// OrganizationUnitDelete is the builder for deleting a OrganizationUnit entity.
type OrganizationUnitDelete struct {
	config
	hooks    []Hook
	mutation *OrganizationUnitMutation
}

// Where appends a list predicates to the OrganizationUnitDelete builder.
func (oud *OrganizationUnitDelete) Where(ps ...predicate.OrganizationUnit) *OrganizationUnitDelete {
	oud.mutation.Where(ps...)
	return oud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oud *OrganizationUnitDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, oud.sqlExec, oud.mutation, oud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (oud *OrganizationUnitDelete) ExecX(ctx context.Context) int {
	n, err := oud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oud *OrganizationUnitDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(organizationunit.Table, sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID))
	if ps := oud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, oud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	oud.mutation.done = true
	return affected, err
}

// OrganizationUnitDeleteOne is the builder for deleting a single OrganizationUnit entity.
type OrganizationUnitDeleteOne struct {
	oud *OrganizationUnitDelete
}

// Where appends a list predicates to the OrganizationUnitDelete builder.
func (oudo *OrganizationUnitDeleteOne) Where(ps ...predicate.OrganizationUnit) *OrganizationUnitDeleteOne {
	oudo.oud.mutation.Where(ps...)
	return oudo
}

// Exec executes the deletion query.
func (oudo *OrganizationUnitDeleteOne) Exec(ctx context.Context) error {
	n, err := oudo.oud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{organizationunit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oudo *OrganizationUnitDeleteOne) ExecX(ctx context.Context) {
	if err := oudo.Exec(ctx); err != nil {
		panic(err)
	}
}
