// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gaogu/cube-castle/go-app/ent/assignmentdetails"
	"github.com/gaogu/cube-castle/go-app/ent/assignmenthistory"
	"github.com/gaogu/cube-castle/go-app/ent/employee"
	"github.com/gaogu/cube-castle/go-app/ent/position"
	"github.com/gaogu/cube-castle/go-app/ent/positionassignment"
	"github.com/google/uuid"
)

// PositionAssignmentCreate is the builder for creating a PositionAssignment entity.
type PositionAssignmentCreate struct {
	config
	mutation *PositionAssignmentMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (pac *PositionAssignmentCreate) SetTenantID(u uuid.UUID) *PositionAssignmentCreate {
	pac.mutation.SetTenantID(u)
	return pac
}

// SetPositionID sets the "position_id" field.
func (pac *PositionAssignmentCreate) SetPositionID(u uuid.UUID) *PositionAssignmentCreate {
	pac.mutation.SetPositionID(u)
	return pac
}

// SetEmployeeID sets the "employee_id" field.
func (pac *PositionAssignmentCreate) SetEmployeeID(u uuid.UUID) *PositionAssignmentCreate {
	pac.mutation.SetEmployeeID(u)
	return pac
}

// SetStartDate sets the "start_date" field.
func (pac *PositionAssignmentCreate) SetStartDate(t time.Time) *PositionAssignmentCreate {
	pac.mutation.SetStartDate(t)
	return pac
}

// SetEndDate sets the "end_date" field.
func (pac *PositionAssignmentCreate) SetEndDate(t time.Time) *PositionAssignmentCreate {
	pac.mutation.SetEndDate(t)
	return pac
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (pac *PositionAssignmentCreate) SetNillableEndDate(t *time.Time) *PositionAssignmentCreate {
	if t != nil {
		pac.SetEndDate(*t)
	}
	return pac
}

// SetIsCurrent sets the "is_current" field.
func (pac *PositionAssignmentCreate) SetIsCurrent(b bool) *PositionAssignmentCreate {
	pac.mutation.SetIsCurrent(b)
	return pac
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (pac *PositionAssignmentCreate) SetNillableIsCurrent(b *bool) *PositionAssignmentCreate {
	if b != nil {
		pac.SetIsCurrent(*b)
	}
	return pac
}

// SetFte sets the "fte" field.
func (pac *PositionAssignmentCreate) SetFte(f float64) *PositionAssignmentCreate {
	pac.mutation.SetFte(f)
	return pac
}

// SetNillableFte sets the "fte" field if the given value is not nil.
func (pac *PositionAssignmentCreate) SetNillableFte(f *float64) *PositionAssignmentCreate {
	if f != nil {
		pac.SetFte(*f)
	}
	return pac
}

// SetAssignmentType sets the "assignment_type" field.
func (pac *PositionAssignmentCreate) SetAssignmentType(pt positionassignment.AssignmentType) *PositionAssignmentCreate {
	pac.mutation.SetAssignmentType(pt)
	return pac
}

// SetNillableAssignmentType sets the "assignment_type" field if the given value is not nil.
func (pac *PositionAssignmentCreate) SetNillableAssignmentType(pt *positionassignment.AssignmentType) *PositionAssignmentCreate {
	if pt != nil {
		pac.SetAssignmentType(*pt)
	}
	return pac
}

// SetCreatedAt sets the "created_at" field.
func (pac *PositionAssignmentCreate) SetCreatedAt(t time.Time) *PositionAssignmentCreate {
	pac.mutation.SetCreatedAt(t)
	return pac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pac *PositionAssignmentCreate) SetNillableCreatedAt(t *time.Time) *PositionAssignmentCreate {
	if t != nil {
		pac.SetCreatedAt(*t)
	}
	return pac
}

// SetUpdatedAt sets the "updated_at" field.
func (pac *PositionAssignmentCreate) SetUpdatedAt(t time.Time) *PositionAssignmentCreate {
	pac.mutation.SetUpdatedAt(t)
	return pac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pac *PositionAssignmentCreate) SetNillableUpdatedAt(t *time.Time) *PositionAssignmentCreate {
	if t != nil {
		pac.SetUpdatedAt(*t)
	}
	return pac
}

// SetID sets the "id" field.
func (pac *PositionAssignmentCreate) SetID(u uuid.UUID) *PositionAssignmentCreate {
	pac.mutation.SetID(u)
	return pac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pac *PositionAssignmentCreate) SetNillableID(u *uuid.UUID) *PositionAssignmentCreate {
	if u != nil {
		pac.SetID(*u)
	}
	return pac
}

// SetPosition sets the "position" edge to the Position entity.
func (pac *PositionAssignmentCreate) SetPosition(p *Position) *PositionAssignmentCreate {
	return pac.SetPositionID(p.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (pac *PositionAssignmentCreate) SetEmployee(e *Employee) *PositionAssignmentCreate {
	return pac.SetEmployeeID(e.ID)
}

// AddDetailIDs adds the "details" edge to the AssignmentDetails entity by IDs.
func (pac *PositionAssignmentCreate) AddDetailIDs(ids ...uuid.UUID) *PositionAssignmentCreate {
	pac.mutation.AddDetailIDs(ids...)
	return pac
}

// AddDetails adds the "details" edges to the AssignmentDetails entity.
func (pac *PositionAssignmentCreate) AddDetails(a ...*AssignmentDetails) *PositionAssignmentCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return pac.AddDetailIDs(ids...)
}

// AddHistoryIDs adds the "history" edge to the AssignmentHistory entity by IDs.
func (pac *PositionAssignmentCreate) AddHistoryIDs(ids ...uuid.UUID) *PositionAssignmentCreate {
	pac.mutation.AddHistoryIDs(ids...)
	return pac
}

// AddHistory adds the "history" edges to the AssignmentHistory entity.
func (pac *PositionAssignmentCreate) AddHistory(a ...*AssignmentHistory) *PositionAssignmentCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return pac.AddHistoryIDs(ids...)
}

// Mutation returns the PositionAssignmentMutation object of the builder.
func (pac *PositionAssignmentCreate) Mutation() *PositionAssignmentMutation {
	return pac.mutation
}

// Save creates the PositionAssignment in the database.
func (pac *PositionAssignmentCreate) Save(ctx context.Context) (*PositionAssignment, error) {
	pac.defaults()
	return withHooks(ctx, pac.sqlSave, pac.mutation, pac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pac *PositionAssignmentCreate) SaveX(ctx context.Context) *PositionAssignment {
	v, err := pac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pac *PositionAssignmentCreate) Exec(ctx context.Context) error {
	_, err := pac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pac *PositionAssignmentCreate) ExecX(ctx context.Context) {
	if err := pac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pac *PositionAssignmentCreate) defaults() {
	if _, ok := pac.mutation.IsCurrent(); !ok {
		v := positionassignment.DefaultIsCurrent
		pac.mutation.SetIsCurrent(v)
	}
	if _, ok := pac.mutation.Fte(); !ok {
		v := positionassignment.DefaultFte
		pac.mutation.SetFte(v)
	}
	if _, ok := pac.mutation.AssignmentType(); !ok {
		v := positionassignment.DefaultAssignmentType
		pac.mutation.SetAssignmentType(v)
	}
	if _, ok := pac.mutation.CreatedAt(); !ok {
		v := positionassignment.DefaultCreatedAt()
		pac.mutation.SetCreatedAt(v)
	}
	if _, ok := pac.mutation.UpdatedAt(); !ok {
		v := positionassignment.DefaultUpdatedAt()
		pac.mutation.SetUpdatedAt(v)
	}
	if _, ok := pac.mutation.ID(); !ok {
		v := positionassignment.DefaultID()
		pac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pac *PositionAssignmentCreate) check() error {
	if _, ok := pac.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PositionAssignment.tenant_id"`)}
	}
	if _, ok := pac.mutation.PositionID(); !ok {
		return &ValidationError{Name: "position_id", err: errors.New(`ent: missing required field "PositionAssignment.position_id"`)}
	}
	if _, ok := pac.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "employee_id", err: errors.New(`ent: missing required field "PositionAssignment.employee_id"`)}
	}
	if _, ok := pac.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "PositionAssignment.start_date"`)}
	}
	if _, ok := pac.mutation.IsCurrent(); !ok {
		return &ValidationError{Name: "is_current", err: errors.New(`ent: missing required field "PositionAssignment.is_current"`)}
	}
	if _, ok := pac.mutation.Fte(); !ok {
		return &ValidationError{Name: "fte", err: errors.New(`ent: missing required field "PositionAssignment.fte"`)}
	}
	if _, ok := pac.mutation.AssignmentType(); !ok {
		return &ValidationError{Name: "assignment_type", err: errors.New(`ent: missing required field "PositionAssignment.assignment_type"`)}
	}
	if v, ok := pac.mutation.AssignmentType(); ok {
		if err := positionassignment.AssignmentTypeValidator(v); err != nil {
			return &ValidationError{Name: "assignment_type", err: fmt.Errorf(`ent: validator failed for field "PositionAssignment.assignment_type": %w`, err)}
		}
	}
	if _, ok := pac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PositionAssignment.created_at"`)}
	}
	if _, ok := pac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PositionAssignment.updated_at"`)}
	}
	if len(pac.mutation.PositionIDs()) == 0 {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required edge "PositionAssignment.position"`)}
	}
	if len(pac.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`ent: missing required edge "PositionAssignment.employee"`)}
	}
	return nil
}

func (pac *PositionAssignmentCreate) sqlSave(ctx context.Context) (*PositionAssignment, error) {
	if err := pac.check(); err != nil {
		return nil, err
	}
	_node, _spec := pac.createSpec()
	if err := sqlgraph.CreateNode(ctx, pac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	pac.mutation.id = &_node.ID
	pac.mutation.done = true
	return _node, nil
}

func (pac *PositionAssignmentCreate) createSpec() (*PositionAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &PositionAssignment{config: pac.config}
		_spec = sqlgraph.NewCreateSpec(positionassignment.Table, sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID))
	)
	if id, ok := pac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pac.mutation.TenantID(); ok {
		_spec.SetField(positionassignment.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := pac.mutation.StartDate(); ok {
		_spec.SetField(positionassignment.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := pac.mutation.EndDate(); ok {
		_spec.SetField(positionassignment.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if value, ok := pac.mutation.IsCurrent(); ok {
		_spec.SetField(positionassignment.FieldIsCurrent, field.TypeBool, value)
		_node.IsCurrent = value
	}
	if value, ok := pac.mutation.Fte(); ok {
		_spec.SetField(positionassignment.FieldFte, field.TypeFloat64, value)
		_node.Fte = value
	}
	if value, ok := pac.mutation.AssignmentType(); ok {
		_spec.SetField(positionassignment.FieldAssignmentType, field.TypeEnum, value)
		_node.AssignmentType = value
	}
	if value, ok := pac.mutation.CreatedAt(); ok {
		_spec.SetField(positionassignment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pac.mutation.UpdatedAt(); ok {
		_spec.SetField(positionassignment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := pac.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionassignment.PositionTable,
			Columns: []string{positionassignment.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PositionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pac.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionassignment.EmployeeTable,
			Columns: []string{positionassignment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmployeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pac.mutation.DetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   positionassignment.DetailsTable,
			Columns: []string{positionassignment.DetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignmentdetails.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pac.mutation.HistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   positionassignment.HistoryTable,
			Columns: []string{positionassignment.HistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(assignmenthistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PositionAssignmentCreateBulk is the builder for creating many PositionAssignment entities in bulk.
type PositionAssignmentCreateBulk struct {
	config
	err      error
	builders []*PositionAssignmentCreate
}

// Save creates the PositionAssignment entities in the database.
func (pacb *PositionAssignmentCreateBulk) Save(ctx context.Context) ([]*PositionAssignment, error) {
	if pacb.err != nil {
		return nil, pacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pacb.builders))
	nodes := make([]*PositionAssignment, len(pacb.builders))
	mutators := make([]Mutator, len(pacb.builders))
	for i := range pacb.builders {
		func(i int, root context.Context) {
			builder := pacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PositionAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pacb *PositionAssignmentCreateBulk) SaveX(ctx context.Context) []*PositionAssignment {
	v, err := pacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pacb *PositionAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := pacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pacb *PositionAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := pacb.Exec(ctx); err != nil {
		panic(err)
	}
}
