// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gaogu/cube-castle/go-app/ent/employee"
	"github.com/gaogu/cube-castle/go-app/ent/position"
	"github.com/gaogu/cube-castle/go-app/ent/positionassignment"
	"github.com/google/uuid"
)

// PositionAssignment is the model entity for the PositionAssignment schema.
type PositionAssignment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// PositionID holds the value of the "position_id" field.
	PositionID uuid.UUID `json:"position_id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID uuid.UUID `json:"employee_id,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate *time.Time `json:"end_date,omitempty"`
	// IsCurrent holds the value of the "is_current" field.
	IsCurrent bool `json:"is_current,omitempty"`
	// Fte holds the value of the "fte" field.
	Fte float64 `json:"fte,omitempty"`
	// AssignmentType holds the value of the "assignment_type" field.
	AssignmentType positionassignment.AssignmentType `json:"assignment_type,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PositionAssignmentQuery when eager-loading is set.
	Edges        PositionAssignmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PositionAssignmentEdges holds the relations/edges for other nodes in the graph.
type PositionAssignmentEdges struct {
	// Position holds the value of the position edge.
	Position *Position `json:"position,omitempty"`
	// Employee holds the value of the employee edge.
	Employee *Employee `json:"employee,omitempty"`
	// Detailed assignment information
	Details []*AssignmentDetails `json:"details,omitempty"`
	// Assignment change history
	History []*AssignmentHistory `json:"history,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// PositionOrErr returns the Position value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PositionAssignmentEdges) PositionOrErr() (*Position, error) {
	if e.Position != nil {
		return e.Position, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: position.Label}
	}
	return nil, &NotLoadedError{edge: "position"}
}

// EmployeeOrErr returns the Employee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PositionAssignmentEdges) EmployeeOrErr() (*Employee, error) {
	if e.Employee != nil {
		return e.Employee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: employee.Label}
	}
	return nil, &NotLoadedError{edge: "employee"}
}

// DetailsOrErr returns the Details value or an error if the edge
// was not loaded in eager-loading.
func (e PositionAssignmentEdges) DetailsOrErr() ([]*AssignmentDetails, error) {
	if e.loadedTypes[2] {
		return e.Details, nil
	}
	return nil, &NotLoadedError{edge: "details"}
}

// HistoryOrErr returns the History value or an error if the edge
// was not loaded in eager-loading.
func (e PositionAssignmentEdges) HistoryOrErr() ([]*AssignmentHistory, error) {
	if e.loadedTypes[3] {
		return e.History, nil
	}
	return nil, &NotLoadedError{edge: "history"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PositionAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case positionassignment.FieldIsCurrent:
			values[i] = new(sql.NullBool)
		case positionassignment.FieldFte:
			values[i] = new(sql.NullFloat64)
		case positionassignment.FieldAssignmentType:
			values[i] = new(sql.NullString)
		case positionassignment.FieldStartDate, positionassignment.FieldEndDate, positionassignment.FieldCreatedAt, positionassignment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case positionassignment.FieldID, positionassignment.FieldTenantID, positionassignment.FieldPositionID, positionassignment.FieldEmployeeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PositionAssignment fields.
func (pa *PositionAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case positionassignment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pa.ID = *value
			}
		case positionassignment.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				pa.TenantID = *value
			}
		case positionassignment.FieldPositionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field position_id", values[i])
			} else if value != nil {
				pa.PositionID = *value
			}
		case positionassignment.FieldEmployeeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value != nil {
				pa.EmployeeID = *value
			}
		case positionassignment.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				pa.StartDate = value.Time
			}
		case positionassignment.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				pa.EndDate = new(time.Time)
				*pa.EndDate = value.Time
			}
		case positionassignment.FieldIsCurrent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_current", values[i])
			} else if value.Valid {
				pa.IsCurrent = value.Bool
			}
		case positionassignment.FieldFte:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fte", values[i])
			} else if value.Valid {
				pa.Fte = value.Float64
			}
		case positionassignment.FieldAssignmentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field assignment_type", values[i])
			} else if value.Valid {
				pa.AssignmentType = positionassignment.AssignmentType(value.String)
			}
		case positionassignment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pa.CreatedAt = value.Time
			}
		case positionassignment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pa.UpdatedAt = value.Time
			}
		default:
			pa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PositionAssignment.
// This includes values selected through modifiers, order, etc.
func (pa *PositionAssignment) Value(name string) (ent.Value, error) {
	return pa.selectValues.Get(name)
}

// QueryPosition queries the "position" edge of the PositionAssignment entity.
func (pa *PositionAssignment) QueryPosition() *PositionQuery {
	return NewPositionAssignmentClient(pa.config).QueryPosition(pa)
}

// QueryEmployee queries the "employee" edge of the PositionAssignment entity.
func (pa *PositionAssignment) QueryEmployee() *EmployeeQuery {
	return NewPositionAssignmentClient(pa.config).QueryEmployee(pa)
}

// QueryDetails queries the "details" edge of the PositionAssignment entity.
func (pa *PositionAssignment) QueryDetails() *AssignmentDetailsQuery {
	return NewPositionAssignmentClient(pa.config).QueryDetails(pa)
}

// QueryHistory queries the "history" edge of the PositionAssignment entity.
func (pa *PositionAssignment) QueryHistory() *AssignmentHistoryQuery {
	return NewPositionAssignmentClient(pa.config).QueryHistory(pa)
}

// Update returns a builder for updating this PositionAssignment.
// Note that you need to call PositionAssignment.Unwrap() before calling this method if this PositionAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *PositionAssignment) Update() *PositionAssignmentUpdateOne {
	return NewPositionAssignmentClient(pa.config).UpdateOne(pa)
}

// Unwrap unwraps the PositionAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pa *PositionAssignment) Unwrap() *PositionAssignment {
	_tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: PositionAssignment is not a transactional entity")
	}
	pa.config.driver = _tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *PositionAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("PositionAssignment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pa.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", pa.TenantID))
	builder.WriteString(", ")
	builder.WriteString("position_id=")
	builder.WriteString(fmt.Sprintf("%v", pa.PositionID))
	builder.WriteString(", ")
	builder.WriteString("employee_id=")
	builder.WriteString(fmt.Sprintf("%v", pa.EmployeeID))
	builder.WriteString(", ")
	builder.WriteString("start_date=")
	builder.WriteString(pa.StartDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := pa.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_current=")
	builder.WriteString(fmt.Sprintf("%v", pa.IsCurrent))
	builder.WriteString(", ")
	builder.WriteString("fte=")
	builder.WriteString(fmt.Sprintf("%v", pa.Fte))
	builder.WriteString(", ")
	builder.WriteString("assignment_type=")
	builder.WriteString(fmt.Sprintf("%v", pa.AssignmentType))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pa.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pa.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PositionAssignments is a parsable slice of PositionAssignment.
type PositionAssignments []*PositionAssignment
