// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gaogu/cube-castle/go-app/ent/position"
	"github.com/gaogu/cube-castle/go-app/ent/positionoccupancyhistory"
	"github.com/gaogu/cube-castle/go-app/ent/predicate"
	"github.com/google/uuid"
)

// PositionOccupancyHistoryQuery is the builder for querying PositionOccupancyHistory entities.
type PositionOccupancyHistoryQuery struct {
	config
	ctx          *QueryContext
	order        []positionoccupancyhistory.OrderOption
	inters       []Interceptor
	predicates   []predicate.PositionOccupancyHistory
	withPosition *PositionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PositionOccupancyHistoryQuery builder.
func (pohq *PositionOccupancyHistoryQuery) Where(ps ...predicate.PositionOccupancyHistory) *PositionOccupancyHistoryQuery {
	pohq.predicates = append(pohq.predicates, ps...)
	return pohq
}

// Limit the number of records to be returned by this query.
func (pohq *PositionOccupancyHistoryQuery) Limit(limit int) *PositionOccupancyHistoryQuery {
	pohq.ctx.Limit = &limit
	return pohq
}

// Offset to start from.
func (pohq *PositionOccupancyHistoryQuery) Offset(offset int) *PositionOccupancyHistoryQuery {
	pohq.ctx.Offset = &offset
	return pohq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pohq *PositionOccupancyHistoryQuery) Unique(unique bool) *PositionOccupancyHistoryQuery {
	pohq.ctx.Unique = &unique
	return pohq
}

// Order specifies how the records should be ordered.
func (pohq *PositionOccupancyHistoryQuery) Order(o ...positionoccupancyhistory.OrderOption) *PositionOccupancyHistoryQuery {
	pohq.order = append(pohq.order, o...)
	return pohq
}

// QueryPosition chains the current query on the "position" edge.
func (pohq *PositionOccupancyHistoryQuery) QueryPosition() *PositionQuery {
	query := (&PositionClient{config: pohq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pohq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pohq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(positionoccupancyhistory.Table, positionoccupancyhistory.FieldID, selector),
			sqlgraph.To(position.Table, position.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, positionoccupancyhistory.PositionTable, positionoccupancyhistory.PositionColumn),
		)
		fromU = sqlgraph.SetNeighbors(pohq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PositionOccupancyHistory entity from the query.
// Returns a *NotFoundError when no PositionOccupancyHistory was found.
func (pohq *PositionOccupancyHistoryQuery) First(ctx context.Context) (*PositionOccupancyHistory, error) {
	nodes, err := pohq.Limit(1).All(setContextOp(ctx, pohq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{positionoccupancyhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pohq *PositionOccupancyHistoryQuery) FirstX(ctx context.Context) *PositionOccupancyHistory {
	node, err := pohq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PositionOccupancyHistory ID from the query.
// Returns a *NotFoundError when no PositionOccupancyHistory ID was found.
func (pohq *PositionOccupancyHistoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pohq.Limit(1).IDs(setContextOp(ctx, pohq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{positionoccupancyhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pohq *PositionOccupancyHistoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pohq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PositionOccupancyHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PositionOccupancyHistory entity is found.
// Returns a *NotFoundError when no PositionOccupancyHistory entities are found.
func (pohq *PositionOccupancyHistoryQuery) Only(ctx context.Context) (*PositionOccupancyHistory, error) {
	nodes, err := pohq.Limit(2).All(setContextOp(ctx, pohq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{positionoccupancyhistory.Label}
	default:
		return nil, &NotSingularError{positionoccupancyhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pohq *PositionOccupancyHistoryQuery) OnlyX(ctx context.Context) *PositionOccupancyHistory {
	node, err := pohq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PositionOccupancyHistory ID in the query.
// Returns a *NotSingularError when more than one PositionOccupancyHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (pohq *PositionOccupancyHistoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pohq.Limit(2).IDs(setContextOp(ctx, pohq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{positionoccupancyhistory.Label}
	default:
		err = &NotSingularError{positionoccupancyhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pohq *PositionOccupancyHistoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pohq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PositionOccupancyHistories.
func (pohq *PositionOccupancyHistoryQuery) All(ctx context.Context) ([]*PositionOccupancyHistory, error) {
	ctx = setContextOp(ctx, pohq.ctx, ent.OpQueryAll)
	if err := pohq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PositionOccupancyHistory, *PositionOccupancyHistoryQuery]()
	return withInterceptors[[]*PositionOccupancyHistory](ctx, pohq, qr, pohq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pohq *PositionOccupancyHistoryQuery) AllX(ctx context.Context) []*PositionOccupancyHistory {
	nodes, err := pohq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PositionOccupancyHistory IDs.
func (pohq *PositionOccupancyHistoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if pohq.ctx.Unique == nil && pohq.path != nil {
		pohq.Unique(true)
	}
	ctx = setContextOp(ctx, pohq.ctx, ent.OpQueryIDs)
	if err = pohq.Select(positionoccupancyhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pohq *PositionOccupancyHistoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pohq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pohq *PositionOccupancyHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pohq.ctx, ent.OpQueryCount)
	if err := pohq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pohq, querierCount[*PositionOccupancyHistoryQuery](), pohq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pohq *PositionOccupancyHistoryQuery) CountX(ctx context.Context) int {
	count, err := pohq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pohq *PositionOccupancyHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pohq.ctx, ent.OpQueryExist)
	switch _, err := pohq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pohq *PositionOccupancyHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := pohq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PositionOccupancyHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pohq *PositionOccupancyHistoryQuery) Clone() *PositionOccupancyHistoryQuery {
	if pohq == nil {
		return nil
	}
	return &PositionOccupancyHistoryQuery{
		config:       pohq.config,
		ctx:          pohq.ctx.Clone(),
		order:        append([]positionoccupancyhistory.OrderOption{}, pohq.order...),
		inters:       append([]Interceptor{}, pohq.inters...),
		predicates:   append([]predicate.PositionOccupancyHistory{}, pohq.predicates...),
		withPosition: pohq.withPosition.Clone(),
		// clone intermediate query.
		sql:  pohq.sql.Clone(),
		path: pohq.path,
	}
}

// WithPosition tells the query-builder to eager-load the nodes that are connected to
// the "position" edge. The optional arguments are used to configure the query builder of the edge.
func (pohq *PositionOccupancyHistoryQuery) WithPosition(opts ...func(*PositionQuery)) *PositionOccupancyHistoryQuery {
	query := (&PositionClient{config: pohq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pohq.withPosition = query
	return pohq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PositionOccupancyHistory.Query().
//		GroupBy(positionoccupancyhistory.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pohq *PositionOccupancyHistoryQuery) GroupBy(field string, fields ...string) *PositionOccupancyHistoryGroupBy {
	pohq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PositionOccupancyHistoryGroupBy{build: pohq}
	grbuild.flds = &pohq.ctx.Fields
	grbuild.label = positionoccupancyhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//	}
//
//	client.PositionOccupancyHistory.Query().
//		Select(positionoccupancyhistory.FieldTenantID).
//		Scan(ctx, &v)
func (pohq *PositionOccupancyHistoryQuery) Select(fields ...string) *PositionOccupancyHistorySelect {
	pohq.ctx.Fields = append(pohq.ctx.Fields, fields...)
	sbuild := &PositionOccupancyHistorySelect{PositionOccupancyHistoryQuery: pohq}
	sbuild.label = positionoccupancyhistory.Label
	sbuild.flds, sbuild.scan = &pohq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PositionOccupancyHistorySelect configured with the given aggregations.
func (pohq *PositionOccupancyHistoryQuery) Aggregate(fns ...AggregateFunc) *PositionOccupancyHistorySelect {
	return pohq.Select().Aggregate(fns...)
}

func (pohq *PositionOccupancyHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pohq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pohq); err != nil {
				return err
			}
		}
	}
	for _, f := range pohq.ctx.Fields {
		if !positionoccupancyhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pohq.path != nil {
		prev, err := pohq.path(ctx)
		if err != nil {
			return err
		}
		pohq.sql = prev
	}
	return nil
}

func (pohq *PositionOccupancyHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PositionOccupancyHistory, error) {
	var (
		nodes       = []*PositionOccupancyHistory{}
		_spec       = pohq.querySpec()
		loadedTypes = [1]bool{
			pohq.withPosition != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PositionOccupancyHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PositionOccupancyHistory{config: pohq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pohq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pohq.withPosition; query != nil {
		if err := pohq.loadPosition(ctx, query, nodes, nil,
			func(n *PositionOccupancyHistory, e *Position) { n.Edges.Position = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pohq *PositionOccupancyHistoryQuery) loadPosition(ctx context.Context, query *PositionQuery, nodes []*PositionOccupancyHistory, init func(*PositionOccupancyHistory), assign func(*PositionOccupancyHistory, *Position)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PositionOccupancyHistory)
	for i := range nodes {
		fk := nodes[i].PositionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(position.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "position_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pohq *PositionOccupancyHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pohq.querySpec()
	_spec.Node.Columns = pohq.ctx.Fields
	if len(pohq.ctx.Fields) > 0 {
		_spec.Unique = pohq.ctx.Unique != nil && *pohq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pohq.driver, _spec)
}

func (pohq *PositionOccupancyHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(positionoccupancyhistory.Table, positionoccupancyhistory.Columns, sqlgraph.NewFieldSpec(positionoccupancyhistory.FieldID, field.TypeUUID))
	_spec.From = pohq.sql
	if unique := pohq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pohq.path != nil {
		_spec.Unique = true
	}
	if fields := pohq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, positionoccupancyhistory.FieldID)
		for i := range fields {
			if fields[i] != positionoccupancyhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if pohq.withPosition != nil {
			_spec.Node.AddColumnOnce(positionoccupancyhistory.FieldPositionID)
		}
	}
	if ps := pohq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pohq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pohq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pohq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pohq *PositionOccupancyHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pohq.driver.Dialect())
	t1 := builder.Table(positionoccupancyhistory.Table)
	columns := pohq.ctx.Fields
	if len(columns) == 0 {
		columns = positionoccupancyhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pohq.sql != nil {
		selector = pohq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pohq.ctx.Unique != nil && *pohq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pohq.predicates {
		p(selector)
	}
	for _, p := range pohq.order {
		p(selector)
	}
	if offset := pohq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pohq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PositionOccupancyHistoryGroupBy is the group-by builder for PositionOccupancyHistory entities.
type PositionOccupancyHistoryGroupBy struct {
	selector
	build *PositionOccupancyHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pohgb *PositionOccupancyHistoryGroupBy) Aggregate(fns ...AggregateFunc) *PositionOccupancyHistoryGroupBy {
	pohgb.fns = append(pohgb.fns, fns...)
	return pohgb
}

// Scan applies the selector query and scans the result into the given value.
func (pohgb *PositionOccupancyHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pohgb.build.ctx, ent.OpQueryGroupBy)
	if err := pohgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PositionOccupancyHistoryQuery, *PositionOccupancyHistoryGroupBy](ctx, pohgb.build, pohgb, pohgb.build.inters, v)
}

func (pohgb *PositionOccupancyHistoryGroupBy) sqlScan(ctx context.Context, root *PositionOccupancyHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pohgb.fns))
	for _, fn := range pohgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pohgb.flds)+len(pohgb.fns))
		for _, f := range *pohgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pohgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pohgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PositionOccupancyHistorySelect is the builder for selecting fields of PositionOccupancyHistory entities.
type PositionOccupancyHistorySelect struct {
	*PositionOccupancyHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pohs *PositionOccupancyHistorySelect) Aggregate(fns ...AggregateFunc) *PositionOccupancyHistorySelect {
	pohs.fns = append(pohs.fns, fns...)
	return pohs
}

// Scan applies the selector query and scans the result into the given value.
func (pohs *PositionOccupancyHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pohs.ctx, ent.OpQuerySelect)
	if err := pohs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PositionOccupancyHistoryQuery, *PositionOccupancyHistorySelect](ctx, pohs.PositionOccupancyHistoryQuery, pohs, pohs.inters, v)
}

func (pohs *PositionOccupancyHistorySelect) sqlScan(ctx context.Context, root *PositionOccupancyHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pohs.fns))
	for _, fn := range pohs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pohs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pohs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
