// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gaogu/cube-castle/go-app/ent/employee"
	"github.com/gaogu/cube-castle/go-app/ent/organizationunit"
	"github.com/gaogu/cube-castle/go-app/ent/position"
	"github.com/gaogu/cube-castle/go-app/ent/positionassignment"
	"github.com/gaogu/cube-castle/go-app/ent/positionattributehistory"
	"github.com/gaogu/cube-castle/go-app/ent/positionoccupancyhistory"
	"github.com/gaogu/cube-castle/go-app/ent/predicate"
	"github.com/google/uuid"
)

// PositionUpdate is the builder for updating Position entities.
type PositionUpdate struct {
	config
	hooks    []Hook
	mutation *PositionMutation
}

// Where appends a list predicates to the PositionUpdate builder.
func (pu *PositionUpdate) Where(ps ...predicate.Position) *PositionUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetBusinessID sets the "business_id" field.
func (pu *PositionUpdate) SetBusinessID(s string) *PositionUpdate {
	pu.mutation.SetBusinessID(s)
	return pu
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (pu *PositionUpdate) SetNillableBusinessID(s *string) *PositionUpdate {
	if s != nil {
		pu.SetBusinessID(*s)
	}
	return pu
}

// SetPositionType sets the "position_type" field.
func (pu *PositionUpdate) SetPositionType(pt position.PositionType) *PositionUpdate {
	pu.mutation.SetPositionType(pt)
	return pu
}

// SetNillablePositionType sets the "position_type" field if the given value is not nil.
func (pu *PositionUpdate) SetNillablePositionType(pt *position.PositionType) *PositionUpdate {
	if pt != nil {
		pu.SetPositionType(*pt)
	}
	return pu
}

// SetJobProfileID sets the "job_profile_id" field.
func (pu *PositionUpdate) SetJobProfileID(u uuid.UUID) *PositionUpdate {
	pu.mutation.SetJobProfileID(u)
	return pu
}

// SetNillableJobProfileID sets the "job_profile_id" field if the given value is not nil.
func (pu *PositionUpdate) SetNillableJobProfileID(u *uuid.UUID) *PositionUpdate {
	if u != nil {
		pu.SetJobProfileID(*u)
	}
	return pu
}

// SetDepartmentID sets the "department_id" field.
func (pu *PositionUpdate) SetDepartmentID(u uuid.UUID) *PositionUpdate {
	pu.mutation.SetDepartmentID(u)
	return pu
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (pu *PositionUpdate) SetNillableDepartmentID(u *uuid.UUID) *PositionUpdate {
	if u != nil {
		pu.SetDepartmentID(*u)
	}
	return pu
}

// SetManagerPositionID sets the "manager_position_id" field.
func (pu *PositionUpdate) SetManagerPositionID(u uuid.UUID) *PositionUpdate {
	pu.mutation.SetManagerPositionID(u)
	return pu
}

// SetNillableManagerPositionID sets the "manager_position_id" field if the given value is not nil.
func (pu *PositionUpdate) SetNillableManagerPositionID(u *uuid.UUID) *PositionUpdate {
	if u != nil {
		pu.SetManagerPositionID(*u)
	}
	return pu
}

// ClearManagerPositionID clears the value of the "manager_position_id" field.
func (pu *PositionUpdate) ClearManagerPositionID() *PositionUpdate {
	pu.mutation.ClearManagerPositionID()
	return pu
}

// SetStatus sets the "status" field.
func (pu *PositionUpdate) SetStatus(po position.Status) *PositionUpdate {
	pu.mutation.SetStatus(po)
	return pu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pu *PositionUpdate) SetNillableStatus(po *position.Status) *PositionUpdate {
	if po != nil {
		pu.SetStatus(*po)
	}
	return pu
}

// SetBudgetedFte sets the "budgeted_fte" field.
func (pu *PositionUpdate) SetBudgetedFte(f float64) *PositionUpdate {
	pu.mutation.ResetBudgetedFte()
	pu.mutation.SetBudgetedFte(f)
	return pu
}

// SetNillableBudgetedFte sets the "budgeted_fte" field if the given value is not nil.
func (pu *PositionUpdate) SetNillableBudgetedFte(f *float64) *PositionUpdate {
	if f != nil {
		pu.SetBudgetedFte(*f)
	}
	return pu
}

// AddBudgetedFte adds f to the "budgeted_fte" field.
func (pu *PositionUpdate) AddBudgetedFte(f float64) *PositionUpdate {
	pu.mutation.AddBudgetedFte(f)
	return pu
}

// SetDetails sets the "details" field.
func (pu *PositionUpdate) SetDetails(m map[string]interface{}) *PositionUpdate {
	pu.mutation.SetDetails(m)
	return pu
}

// ClearDetails clears the value of the "details" field.
func (pu *PositionUpdate) ClearDetails() *PositionUpdate {
	pu.mutation.ClearDetails()
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PositionUpdate) SetUpdatedAt(t time.Time) *PositionUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetManagerID sets the "manager" edge to the Position entity by ID.
func (pu *PositionUpdate) SetManagerID(id uuid.UUID) *PositionUpdate {
	pu.mutation.SetManagerID(id)
	return pu
}

// SetNillableManagerID sets the "manager" edge to the Position entity by ID if the given value is not nil.
func (pu *PositionUpdate) SetNillableManagerID(id *uuid.UUID) *PositionUpdate {
	if id != nil {
		pu = pu.SetManagerID(*id)
	}
	return pu
}

// SetManager sets the "manager" edge to the Position entity.
func (pu *PositionUpdate) SetManager(p *Position) *PositionUpdate {
	return pu.SetManagerID(p.ID)
}

// AddDirectReportIDs adds the "direct_reports" edge to the Position entity by IDs.
func (pu *PositionUpdate) AddDirectReportIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.AddDirectReportIDs(ids...)
	return pu
}

// AddDirectReports adds the "direct_reports" edges to the Position entity.
func (pu *PositionUpdate) AddDirectReports(p ...*Position) *PositionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddDirectReportIDs(ids...)
}

// SetDepartment sets the "department" edge to the OrganizationUnit entity.
func (pu *PositionUpdate) SetDepartment(o *OrganizationUnit) *PositionUpdate {
	return pu.SetDepartmentID(o.ID)
}

// AddCurrentIncumbentIDs adds the "current_incumbents" edge to the Employee entity by IDs.
func (pu *PositionUpdate) AddCurrentIncumbentIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.AddCurrentIncumbentIDs(ids...)
	return pu
}

// AddCurrentIncumbents adds the "current_incumbents" edges to the Employee entity.
func (pu *PositionUpdate) AddCurrentIncumbents(e ...*Employee) *PositionUpdate {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return pu.AddCurrentIncumbentIDs(ids...)
}

// AddOccupancyHistoryIDs adds the "occupancy_history" edge to the PositionOccupancyHistory entity by IDs.
func (pu *PositionUpdate) AddOccupancyHistoryIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.AddOccupancyHistoryIDs(ids...)
	return pu
}

// AddOccupancyHistory adds the "occupancy_history" edges to the PositionOccupancyHistory entity.
func (pu *PositionUpdate) AddOccupancyHistory(p ...*PositionOccupancyHistory) *PositionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddOccupancyHistoryIDs(ids...)
}

// AddAttributeHistoryIDs adds the "attribute_history" edge to the PositionAttributeHistory entity by IDs.
func (pu *PositionUpdate) AddAttributeHistoryIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.AddAttributeHistoryIDs(ids...)
	return pu
}

// AddAttributeHistory adds the "attribute_history" edges to the PositionAttributeHistory entity.
func (pu *PositionUpdate) AddAttributeHistory(p ...*PositionAttributeHistory) *PositionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddAttributeHistoryIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the PositionAssignment entity by IDs.
func (pu *PositionUpdate) AddAssignmentIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.AddAssignmentIDs(ids...)
	return pu
}

// AddAssignments adds the "assignments" edges to the PositionAssignment entity.
func (pu *PositionUpdate) AddAssignments(p ...*PositionAssignment) *PositionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddAssignmentIDs(ids...)
}

// Mutation returns the PositionMutation object of the builder.
func (pu *PositionUpdate) Mutation() *PositionMutation {
	return pu.mutation
}

// ClearManager clears the "manager" edge to the Position entity.
func (pu *PositionUpdate) ClearManager() *PositionUpdate {
	pu.mutation.ClearManager()
	return pu
}

// ClearDirectReports clears all "direct_reports" edges to the Position entity.
func (pu *PositionUpdate) ClearDirectReports() *PositionUpdate {
	pu.mutation.ClearDirectReports()
	return pu
}

// RemoveDirectReportIDs removes the "direct_reports" edge to Position entities by IDs.
func (pu *PositionUpdate) RemoveDirectReportIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.RemoveDirectReportIDs(ids...)
	return pu
}

// RemoveDirectReports removes "direct_reports" edges to Position entities.
func (pu *PositionUpdate) RemoveDirectReports(p ...*Position) *PositionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemoveDirectReportIDs(ids...)
}

// ClearDepartment clears the "department" edge to the OrganizationUnit entity.
func (pu *PositionUpdate) ClearDepartment() *PositionUpdate {
	pu.mutation.ClearDepartment()
	return pu
}

// ClearCurrentIncumbents clears all "current_incumbents" edges to the Employee entity.
func (pu *PositionUpdate) ClearCurrentIncumbents() *PositionUpdate {
	pu.mutation.ClearCurrentIncumbents()
	return pu
}

// RemoveCurrentIncumbentIDs removes the "current_incumbents" edge to Employee entities by IDs.
func (pu *PositionUpdate) RemoveCurrentIncumbentIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.RemoveCurrentIncumbentIDs(ids...)
	return pu
}

// RemoveCurrentIncumbents removes "current_incumbents" edges to Employee entities.
func (pu *PositionUpdate) RemoveCurrentIncumbents(e ...*Employee) *PositionUpdate {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return pu.RemoveCurrentIncumbentIDs(ids...)
}

// ClearOccupancyHistory clears all "occupancy_history" edges to the PositionOccupancyHistory entity.
func (pu *PositionUpdate) ClearOccupancyHistory() *PositionUpdate {
	pu.mutation.ClearOccupancyHistory()
	return pu
}

// RemoveOccupancyHistoryIDs removes the "occupancy_history" edge to PositionOccupancyHistory entities by IDs.
func (pu *PositionUpdate) RemoveOccupancyHistoryIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.RemoveOccupancyHistoryIDs(ids...)
	return pu
}

// RemoveOccupancyHistory removes "occupancy_history" edges to PositionOccupancyHistory entities.
func (pu *PositionUpdate) RemoveOccupancyHistory(p ...*PositionOccupancyHistory) *PositionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemoveOccupancyHistoryIDs(ids...)
}

// ClearAttributeHistory clears all "attribute_history" edges to the PositionAttributeHistory entity.
func (pu *PositionUpdate) ClearAttributeHistory() *PositionUpdate {
	pu.mutation.ClearAttributeHistory()
	return pu
}

// RemoveAttributeHistoryIDs removes the "attribute_history" edge to PositionAttributeHistory entities by IDs.
func (pu *PositionUpdate) RemoveAttributeHistoryIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.RemoveAttributeHistoryIDs(ids...)
	return pu
}

// RemoveAttributeHistory removes "attribute_history" edges to PositionAttributeHistory entities.
func (pu *PositionUpdate) RemoveAttributeHistory(p ...*PositionAttributeHistory) *PositionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemoveAttributeHistoryIDs(ids...)
}

// ClearAssignments clears all "assignments" edges to the PositionAssignment entity.
func (pu *PositionUpdate) ClearAssignments() *PositionUpdate {
	pu.mutation.ClearAssignments()
	return pu
}

// RemoveAssignmentIDs removes the "assignments" edge to PositionAssignment entities by IDs.
func (pu *PositionUpdate) RemoveAssignmentIDs(ids ...uuid.UUID) *PositionUpdate {
	pu.mutation.RemoveAssignmentIDs(ids...)
	return pu
}

// RemoveAssignments removes "assignments" edges to PositionAssignment entities.
func (pu *PositionUpdate) RemoveAssignments(p ...*PositionAssignment) *PositionUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemoveAssignmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PositionUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PositionUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PositionUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PositionUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PositionUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := position.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PositionUpdate) check() error {
	if v, ok := pu.mutation.BusinessID(); ok {
		if err := position.BusinessIDValidator(v); err != nil {
			return &ValidationError{Name: "business_id", err: fmt.Errorf(`ent: validator failed for field "Position.business_id": %w`, err)}
		}
	}
	if v, ok := pu.mutation.PositionType(); ok {
		if err := position.PositionTypeValidator(v); err != nil {
			return &ValidationError{Name: "position_type", err: fmt.Errorf(`ent: validator failed for field "Position.position_type": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Status(); ok {
		if err := position.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Position.status": %w`, err)}
		}
	}
	if pu.mutation.DepartmentCleared() && len(pu.mutation.DepartmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Position.department"`)
	}
	return nil
}

func (pu *PositionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(position.Table, position.Columns, sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.BusinessID(); ok {
		_spec.SetField(position.FieldBusinessID, field.TypeString, value)
	}
	if value, ok := pu.mutation.PositionType(); ok {
		_spec.SetField(position.FieldPositionType, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.JobProfileID(); ok {
		_spec.SetField(position.FieldJobProfileID, field.TypeUUID, value)
	}
	if value, ok := pu.mutation.Status(); ok {
		_spec.SetField(position.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.BudgetedFte(); ok {
		_spec.SetField(position.FieldBudgetedFte, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedBudgetedFte(); ok {
		_spec.AddField(position.FieldBudgetedFte, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.Details(); ok {
		_spec.SetField(position.FieldDetails, field.TypeJSON, value)
	}
	if pu.mutation.DetailsCleared() {
		_spec.ClearField(position.FieldDetails, field.TypeJSON)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(position.FieldUpdatedAt, field.TypeTime, value)
	}
	if pu.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.ManagerTable,
			Columns: []string{position.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.ManagerTable,
			Columns: []string{position.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.DirectReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.DirectReportsTable,
			Columns: []string{position.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedDirectReportsIDs(); len(nodes) > 0 && !pu.mutation.DirectReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.DirectReportsTable,
			Columns: []string{position.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.DirectReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.DirectReportsTable,
			Columns: []string{position.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.DepartmentTable,
			Columns: []string{position.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.DepartmentTable,
			Columns: []string{position.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.CurrentIncumbentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.CurrentIncumbentsTable,
			Columns: []string{position.CurrentIncumbentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedCurrentIncumbentsIDs(); len(nodes) > 0 && !pu.mutation.CurrentIncumbentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.CurrentIncumbentsTable,
			Columns: []string{position.CurrentIncumbentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.CurrentIncumbentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.CurrentIncumbentsTable,
			Columns: []string{position.CurrentIncumbentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.OccupancyHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.OccupancyHistoryTable,
			Columns: []string{position.OccupancyHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionoccupancyhistory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedOccupancyHistoryIDs(); len(nodes) > 0 && !pu.mutation.OccupancyHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.OccupancyHistoryTable,
			Columns: []string{position.OccupancyHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionoccupancyhistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.OccupancyHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.OccupancyHistoryTable,
			Columns: []string{position.OccupancyHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionoccupancyhistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.AttributeHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AttributeHistoryTable,
			Columns: []string{position.AttributeHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionattributehistory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedAttributeHistoryIDs(); len(nodes) > 0 && !pu.mutation.AttributeHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AttributeHistoryTable,
			Columns: []string{position.AttributeHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionattributehistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.AttributeHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AttributeHistoryTable,
			Columns: []string{position.AttributeHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionattributehistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AssignmentsTable,
			Columns: []string{position.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !pu.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AssignmentsTable,
			Columns: []string{position.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AssignmentsTable,
			Columns: []string{position.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{position.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PositionUpdateOne is the builder for updating a single Position entity.
type PositionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PositionMutation
}

// SetBusinessID sets the "business_id" field.
func (puo *PositionUpdateOne) SetBusinessID(s string) *PositionUpdateOne {
	puo.mutation.SetBusinessID(s)
	return puo
}

// SetNillableBusinessID sets the "business_id" field if the given value is not nil.
func (puo *PositionUpdateOne) SetNillableBusinessID(s *string) *PositionUpdateOne {
	if s != nil {
		puo.SetBusinessID(*s)
	}
	return puo
}

// SetPositionType sets the "position_type" field.
func (puo *PositionUpdateOne) SetPositionType(pt position.PositionType) *PositionUpdateOne {
	puo.mutation.SetPositionType(pt)
	return puo
}

// SetNillablePositionType sets the "position_type" field if the given value is not nil.
func (puo *PositionUpdateOne) SetNillablePositionType(pt *position.PositionType) *PositionUpdateOne {
	if pt != nil {
		puo.SetPositionType(*pt)
	}
	return puo
}

// SetJobProfileID sets the "job_profile_id" field.
func (puo *PositionUpdateOne) SetJobProfileID(u uuid.UUID) *PositionUpdateOne {
	puo.mutation.SetJobProfileID(u)
	return puo
}

// SetNillableJobProfileID sets the "job_profile_id" field if the given value is not nil.
func (puo *PositionUpdateOne) SetNillableJobProfileID(u *uuid.UUID) *PositionUpdateOne {
	if u != nil {
		puo.SetJobProfileID(*u)
	}
	return puo
}

// SetDepartmentID sets the "department_id" field.
func (puo *PositionUpdateOne) SetDepartmentID(u uuid.UUID) *PositionUpdateOne {
	puo.mutation.SetDepartmentID(u)
	return puo
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (puo *PositionUpdateOne) SetNillableDepartmentID(u *uuid.UUID) *PositionUpdateOne {
	if u != nil {
		puo.SetDepartmentID(*u)
	}
	return puo
}

// SetManagerPositionID sets the "manager_position_id" field.
func (puo *PositionUpdateOne) SetManagerPositionID(u uuid.UUID) *PositionUpdateOne {
	puo.mutation.SetManagerPositionID(u)
	return puo
}

// SetNillableManagerPositionID sets the "manager_position_id" field if the given value is not nil.
func (puo *PositionUpdateOne) SetNillableManagerPositionID(u *uuid.UUID) *PositionUpdateOne {
	if u != nil {
		puo.SetManagerPositionID(*u)
	}
	return puo
}

// ClearManagerPositionID clears the value of the "manager_position_id" field.
func (puo *PositionUpdateOne) ClearManagerPositionID() *PositionUpdateOne {
	puo.mutation.ClearManagerPositionID()
	return puo
}

// SetStatus sets the "status" field.
func (puo *PositionUpdateOne) SetStatus(po position.Status) *PositionUpdateOne {
	puo.mutation.SetStatus(po)
	return puo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (puo *PositionUpdateOne) SetNillableStatus(po *position.Status) *PositionUpdateOne {
	if po != nil {
		puo.SetStatus(*po)
	}
	return puo
}

// SetBudgetedFte sets the "budgeted_fte" field.
func (puo *PositionUpdateOne) SetBudgetedFte(f float64) *PositionUpdateOne {
	puo.mutation.ResetBudgetedFte()
	puo.mutation.SetBudgetedFte(f)
	return puo
}

// SetNillableBudgetedFte sets the "budgeted_fte" field if the given value is not nil.
func (puo *PositionUpdateOne) SetNillableBudgetedFte(f *float64) *PositionUpdateOne {
	if f != nil {
		puo.SetBudgetedFte(*f)
	}
	return puo
}

// AddBudgetedFte adds f to the "budgeted_fte" field.
func (puo *PositionUpdateOne) AddBudgetedFte(f float64) *PositionUpdateOne {
	puo.mutation.AddBudgetedFte(f)
	return puo
}

// SetDetails sets the "details" field.
func (puo *PositionUpdateOne) SetDetails(m map[string]interface{}) *PositionUpdateOne {
	puo.mutation.SetDetails(m)
	return puo
}

// ClearDetails clears the value of the "details" field.
func (puo *PositionUpdateOne) ClearDetails() *PositionUpdateOne {
	puo.mutation.ClearDetails()
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PositionUpdateOne) SetUpdatedAt(t time.Time) *PositionUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetManagerID sets the "manager" edge to the Position entity by ID.
func (puo *PositionUpdateOne) SetManagerID(id uuid.UUID) *PositionUpdateOne {
	puo.mutation.SetManagerID(id)
	return puo
}

// SetNillableManagerID sets the "manager" edge to the Position entity by ID if the given value is not nil.
func (puo *PositionUpdateOne) SetNillableManagerID(id *uuid.UUID) *PositionUpdateOne {
	if id != nil {
		puo = puo.SetManagerID(*id)
	}
	return puo
}

// SetManager sets the "manager" edge to the Position entity.
func (puo *PositionUpdateOne) SetManager(p *Position) *PositionUpdateOne {
	return puo.SetManagerID(p.ID)
}

// AddDirectReportIDs adds the "direct_reports" edge to the Position entity by IDs.
func (puo *PositionUpdateOne) AddDirectReportIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.AddDirectReportIDs(ids...)
	return puo
}

// AddDirectReports adds the "direct_reports" edges to the Position entity.
func (puo *PositionUpdateOne) AddDirectReports(p ...*Position) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddDirectReportIDs(ids...)
}

// SetDepartment sets the "department" edge to the OrganizationUnit entity.
func (puo *PositionUpdateOne) SetDepartment(o *OrganizationUnit) *PositionUpdateOne {
	return puo.SetDepartmentID(o.ID)
}

// AddCurrentIncumbentIDs adds the "current_incumbents" edge to the Employee entity by IDs.
func (puo *PositionUpdateOne) AddCurrentIncumbentIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.AddCurrentIncumbentIDs(ids...)
	return puo
}

// AddCurrentIncumbents adds the "current_incumbents" edges to the Employee entity.
func (puo *PositionUpdateOne) AddCurrentIncumbents(e ...*Employee) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return puo.AddCurrentIncumbentIDs(ids...)
}

// AddOccupancyHistoryIDs adds the "occupancy_history" edge to the PositionOccupancyHistory entity by IDs.
func (puo *PositionUpdateOne) AddOccupancyHistoryIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.AddOccupancyHistoryIDs(ids...)
	return puo
}

// AddOccupancyHistory adds the "occupancy_history" edges to the PositionOccupancyHistory entity.
func (puo *PositionUpdateOne) AddOccupancyHistory(p ...*PositionOccupancyHistory) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddOccupancyHistoryIDs(ids...)
}

// AddAttributeHistoryIDs adds the "attribute_history" edge to the PositionAttributeHistory entity by IDs.
func (puo *PositionUpdateOne) AddAttributeHistoryIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.AddAttributeHistoryIDs(ids...)
	return puo
}

// AddAttributeHistory adds the "attribute_history" edges to the PositionAttributeHistory entity.
func (puo *PositionUpdateOne) AddAttributeHistory(p ...*PositionAttributeHistory) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddAttributeHistoryIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the PositionAssignment entity by IDs.
func (puo *PositionUpdateOne) AddAssignmentIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.AddAssignmentIDs(ids...)
	return puo
}

// AddAssignments adds the "assignments" edges to the PositionAssignment entity.
func (puo *PositionUpdateOne) AddAssignments(p ...*PositionAssignment) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddAssignmentIDs(ids...)
}

// Mutation returns the PositionMutation object of the builder.
func (puo *PositionUpdateOne) Mutation() *PositionMutation {
	return puo.mutation
}

// ClearManager clears the "manager" edge to the Position entity.
func (puo *PositionUpdateOne) ClearManager() *PositionUpdateOne {
	puo.mutation.ClearManager()
	return puo
}

// ClearDirectReports clears all "direct_reports" edges to the Position entity.
func (puo *PositionUpdateOne) ClearDirectReports() *PositionUpdateOne {
	puo.mutation.ClearDirectReports()
	return puo
}

// RemoveDirectReportIDs removes the "direct_reports" edge to Position entities by IDs.
func (puo *PositionUpdateOne) RemoveDirectReportIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.RemoveDirectReportIDs(ids...)
	return puo
}

// RemoveDirectReports removes "direct_reports" edges to Position entities.
func (puo *PositionUpdateOne) RemoveDirectReports(p ...*Position) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemoveDirectReportIDs(ids...)
}

// ClearDepartment clears the "department" edge to the OrganizationUnit entity.
func (puo *PositionUpdateOne) ClearDepartment() *PositionUpdateOne {
	puo.mutation.ClearDepartment()
	return puo
}

// ClearCurrentIncumbents clears all "current_incumbents" edges to the Employee entity.
func (puo *PositionUpdateOne) ClearCurrentIncumbents() *PositionUpdateOne {
	puo.mutation.ClearCurrentIncumbents()
	return puo
}

// RemoveCurrentIncumbentIDs removes the "current_incumbents" edge to Employee entities by IDs.
func (puo *PositionUpdateOne) RemoveCurrentIncumbentIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.RemoveCurrentIncumbentIDs(ids...)
	return puo
}

// RemoveCurrentIncumbents removes "current_incumbents" edges to Employee entities.
func (puo *PositionUpdateOne) RemoveCurrentIncumbents(e ...*Employee) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return puo.RemoveCurrentIncumbentIDs(ids...)
}

// ClearOccupancyHistory clears all "occupancy_history" edges to the PositionOccupancyHistory entity.
func (puo *PositionUpdateOne) ClearOccupancyHistory() *PositionUpdateOne {
	puo.mutation.ClearOccupancyHistory()
	return puo
}

// RemoveOccupancyHistoryIDs removes the "occupancy_history" edge to PositionOccupancyHistory entities by IDs.
func (puo *PositionUpdateOne) RemoveOccupancyHistoryIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.RemoveOccupancyHistoryIDs(ids...)
	return puo
}

// RemoveOccupancyHistory removes "occupancy_history" edges to PositionOccupancyHistory entities.
func (puo *PositionUpdateOne) RemoveOccupancyHistory(p ...*PositionOccupancyHistory) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemoveOccupancyHistoryIDs(ids...)
}

// ClearAttributeHistory clears all "attribute_history" edges to the PositionAttributeHistory entity.
func (puo *PositionUpdateOne) ClearAttributeHistory() *PositionUpdateOne {
	puo.mutation.ClearAttributeHistory()
	return puo
}

// RemoveAttributeHistoryIDs removes the "attribute_history" edge to PositionAttributeHistory entities by IDs.
func (puo *PositionUpdateOne) RemoveAttributeHistoryIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.RemoveAttributeHistoryIDs(ids...)
	return puo
}

// RemoveAttributeHistory removes "attribute_history" edges to PositionAttributeHistory entities.
func (puo *PositionUpdateOne) RemoveAttributeHistory(p ...*PositionAttributeHistory) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemoveAttributeHistoryIDs(ids...)
}

// ClearAssignments clears all "assignments" edges to the PositionAssignment entity.
func (puo *PositionUpdateOne) ClearAssignments() *PositionUpdateOne {
	puo.mutation.ClearAssignments()
	return puo
}

// RemoveAssignmentIDs removes the "assignments" edge to PositionAssignment entities by IDs.
func (puo *PositionUpdateOne) RemoveAssignmentIDs(ids ...uuid.UUID) *PositionUpdateOne {
	puo.mutation.RemoveAssignmentIDs(ids...)
	return puo
}

// RemoveAssignments removes "assignments" edges to PositionAssignment entities.
func (puo *PositionUpdateOne) RemoveAssignments(p ...*PositionAssignment) *PositionUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemoveAssignmentIDs(ids...)
}

// Where appends a list predicates to the PositionUpdate builder.
func (puo *PositionUpdateOne) Where(ps ...predicate.Position) *PositionUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PositionUpdateOne) Select(field string, fields ...string) *PositionUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Position entity.
func (puo *PositionUpdateOne) Save(ctx context.Context) (*Position, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PositionUpdateOne) SaveX(ctx context.Context) *Position {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PositionUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PositionUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PositionUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := position.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PositionUpdateOne) check() error {
	if v, ok := puo.mutation.BusinessID(); ok {
		if err := position.BusinessIDValidator(v); err != nil {
			return &ValidationError{Name: "business_id", err: fmt.Errorf(`ent: validator failed for field "Position.business_id": %w`, err)}
		}
	}
	if v, ok := puo.mutation.PositionType(); ok {
		if err := position.PositionTypeValidator(v); err != nil {
			return &ValidationError{Name: "position_type", err: fmt.Errorf(`ent: validator failed for field "Position.position_type": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Status(); ok {
		if err := position.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Position.status": %w`, err)}
		}
	}
	if puo.mutation.DepartmentCleared() && len(puo.mutation.DepartmentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Position.department"`)
	}
	return nil
}

func (puo *PositionUpdateOne) sqlSave(ctx context.Context) (_node *Position, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(position.Table, position.Columns, sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Position.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, position.FieldID)
		for _, f := range fields {
			if !position.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != position.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.BusinessID(); ok {
		_spec.SetField(position.FieldBusinessID, field.TypeString, value)
	}
	if value, ok := puo.mutation.PositionType(); ok {
		_spec.SetField(position.FieldPositionType, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.JobProfileID(); ok {
		_spec.SetField(position.FieldJobProfileID, field.TypeUUID, value)
	}
	if value, ok := puo.mutation.Status(); ok {
		_spec.SetField(position.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.BudgetedFte(); ok {
		_spec.SetField(position.FieldBudgetedFte, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedBudgetedFte(); ok {
		_spec.AddField(position.FieldBudgetedFte, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.Details(); ok {
		_spec.SetField(position.FieldDetails, field.TypeJSON, value)
	}
	if puo.mutation.DetailsCleared() {
		_spec.ClearField(position.FieldDetails, field.TypeJSON)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(position.FieldUpdatedAt, field.TypeTime, value)
	}
	if puo.mutation.ManagerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.ManagerTable,
			Columns: []string{position.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ManagerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.ManagerTable,
			Columns: []string{position.ManagerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.DirectReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.DirectReportsTable,
			Columns: []string{position.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedDirectReportsIDs(); len(nodes) > 0 && !puo.mutation.DirectReportsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.DirectReportsTable,
			Columns: []string{position.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.DirectReportsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.DirectReportsTable,
			Columns: []string{position.DirectReportsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(position.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.DepartmentTable,
			Columns: []string{position.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   position.DepartmentTable,
			Columns: []string{position.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationunit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.CurrentIncumbentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.CurrentIncumbentsTable,
			Columns: []string{position.CurrentIncumbentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedCurrentIncumbentsIDs(); len(nodes) > 0 && !puo.mutation.CurrentIncumbentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.CurrentIncumbentsTable,
			Columns: []string{position.CurrentIncumbentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.CurrentIncumbentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.CurrentIncumbentsTable,
			Columns: []string{position.CurrentIncumbentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.OccupancyHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.OccupancyHistoryTable,
			Columns: []string{position.OccupancyHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionoccupancyhistory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedOccupancyHistoryIDs(); len(nodes) > 0 && !puo.mutation.OccupancyHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.OccupancyHistoryTable,
			Columns: []string{position.OccupancyHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionoccupancyhistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.OccupancyHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.OccupancyHistoryTable,
			Columns: []string{position.OccupancyHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionoccupancyhistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.AttributeHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AttributeHistoryTable,
			Columns: []string{position.AttributeHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionattributehistory.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedAttributeHistoryIDs(); len(nodes) > 0 && !puo.mutation.AttributeHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AttributeHistoryTable,
			Columns: []string{position.AttributeHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionattributehistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.AttributeHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AttributeHistoryTable,
			Columns: []string{position.AttributeHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionattributehistory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AssignmentsTable,
			Columns: []string{position.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !puo.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AssignmentsTable,
			Columns: []string{position.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   position.AssignmentsTable,
			Columns: []string{position.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Position{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{position.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
