// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/gaogu/cube-castle/go-app/ent/employee"
	"github.com/gaogu/cube-castle/go-app/ent/positionhistory"
	"github.com/gaogu/cube-castle/go-app/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	employeeFields := schema.Employee{}.Fields()
	_ = employeeFields
	// employeeDescCreatedAt is the schema descriptor for created_at field.
	employeeDescCreatedAt := employeeFields[4].Descriptor()
	// employee.DefaultCreatedAt holds the default value on creation for the created_at field.
	employee.DefaultCreatedAt = employeeDescCreatedAt.Default.(func() time.Time)
	// employeeDescUpdatedAt is the schema descriptor for updated_at field.
	employeeDescUpdatedAt := employeeFields[5].Descriptor()
	// employee.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employee.DefaultUpdatedAt = employeeDescUpdatedAt.Default.(func() time.Time)
	// employee.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	employee.UpdateDefaultUpdatedAt = employeeDescUpdatedAt.UpdateDefault.(func() time.Time)
	positionhistoryFields := schema.PositionHistory{}.Fields()
	_ = positionhistoryFields
	// positionhistoryDescIsActive is the schema descriptor for is_active field.
	positionhistoryDescIsActive := positionhistoryFields[7].Descriptor()
	// positionhistory.DefaultIsActive holds the default value on creation for the is_active field.
	positionhistory.DefaultIsActive = positionhistoryDescIsActive.Default.(bool)
	// positionhistoryDescIsRetroactive is the schema descriptor for is_retroactive field.
	positionhistoryDescIsRetroactive := positionhistoryFields[8].Descriptor()
	// positionhistory.DefaultIsRetroactive holds the default value on creation for the is_retroactive field.
	positionhistory.DefaultIsRetroactive = positionhistoryDescIsRetroactive.Default.(bool)
	// positionhistoryDescApprovalStatus is the schema descriptor for approval_status field.
	positionhistoryDescApprovalStatus := positionhistoryFields[11].Descriptor()
	// positionhistory.DefaultApprovalStatus holds the default value on creation for the approval_status field.
	positionhistory.DefaultApprovalStatus = positionhistoryDescApprovalStatus.Default.(string)
	// positionhistoryDescCreatedAt is the schema descriptor for created_at field.
	positionhistoryDescCreatedAt := positionhistoryFields[12].Descriptor()
	// positionhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	positionhistory.DefaultCreatedAt = positionhistoryDescCreatedAt.Default.(func() time.Time)
	// positionhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	positionhistoryDescUpdatedAt := positionhistoryFields[13].Descriptor()
	// positionhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	positionhistory.DefaultUpdatedAt = positionhistoryDescUpdatedAt.Default.(func() time.Time)
	// positionhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	positionhistory.UpdateDefaultUpdatedAt = positionhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
}
