// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/gaogu/cube-castle/go-app/ent/employee"
	"github.com/gaogu/cube-castle/go-app/ent/organizationunit"
	"github.com/gaogu/cube-castle/go-app/ent/position"
	"github.com/gaogu/cube-castle/go-app/ent/positionattributehistory"
	"github.com/gaogu/cube-castle/go-app/ent/positionhistory"
	"github.com/gaogu/cube-castle/go-app/ent/positionoccupancyhistory"
	"github.com/gaogu/cube-castle/go-app/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	employeeFields := schema.Employee{}.Fields()
	_ = employeeFields
	// employeeDescCreatedAt is the schema descriptor for created_at field.
	employeeDescCreatedAt := employeeFields[4].Descriptor()
	// employee.DefaultCreatedAt holds the default value on creation for the created_at field.
	employee.DefaultCreatedAt = employeeDescCreatedAt.Default.(func() time.Time)
	// employeeDescUpdatedAt is the schema descriptor for updated_at field.
	employeeDescUpdatedAt := employeeFields[5].Descriptor()
	// employee.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	employee.DefaultUpdatedAt = employeeDescUpdatedAt.Default.(func() time.Time)
	// employee.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	employee.UpdateDefaultUpdatedAt = employeeDescUpdatedAt.UpdateDefault.(func() time.Time)
	organizationunitFields := schema.OrganizationUnit{}.Fields()
	_ = organizationunitFields
	// organizationunitDescName is the schema descriptor for name field.
	organizationunitDescName := organizationunitFields[3].Descriptor()
	// organizationunit.NameValidator is a validator for the "name" field. It is called by the builders before save.
	organizationunit.NameValidator = func() func(string) error {
		validators := organizationunitDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// organizationunitDescDescription is the schema descriptor for description field.
	organizationunitDescDescription := organizationunitFields[4].Descriptor()
	// organizationunit.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	organizationunit.DescriptionValidator = organizationunitDescDescription.Validators[0].(func(string) error)
	// organizationunitDescCreatedAt is the schema descriptor for created_at field.
	organizationunitDescCreatedAt := organizationunitFields[8].Descriptor()
	// organizationunit.DefaultCreatedAt holds the default value on creation for the created_at field.
	organizationunit.DefaultCreatedAt = organizationunitDescCreatedAt.Default.(func() time.Time)
	// organizationunitDescUpdatedAt is the schema descriptor for updated_at field.
	organizationunitDescUpdatedAt := organizationunitFields[9].Descriptor()
	// organizationunit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	organizationunit.DefaultUpdatedAt = organizationunitDescUpdatedAt.Default.(func() time.Time)
	// organizationunit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	organizationunit.UpdateDefaultUpdatedAt = organizationunitDescUpdatedAt.UpdateDefault.(func() time.Time)
	// organizationunitDescID is the schema descriptor for id field.
	organizationunitDescID := organizationunitFields[0].Descriptor()
	// organizationunit.DefaultID holds the default value on creation for the id field.
	organizationunit.DefaultID = organizationunitDescID.Default.(func() uuid.UUID)
	positionFields := schema.Position{}.Fields()
	_ = positionFields
	// positionDescBudgetedFte is the schema descriptor for budgeted_fte field.
	positionDescBudgetedFte := positionFields[7].Descriptor()
	// position.DefaultBudgetedFte holds the default value on creation for the budgeted_fte field.
	position.DefaultBudgetedFte = positionDescBudgetedFte.Default.(float64)
	// positionDescCreatedAt is the schema descriptor for created_at field.
	positionDescCreatedAt := positionFields[9].Descriptor()
	// position.DefaultCreatedAt holds the default value on creation for the created_at field.
	position.DefaultCreatedAt = positionDescCreatedAt.Default.(func() time.Time)
	// positionDescUpdatedAt is the schema descriptor for updated_at field.
	positionDescUpdatedAt := positionFields[10].Descriptor()
	// position.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	position.DefaultUpdatedAt = positionDescUpdatedAt.Default.(func() time.Time)
	// position.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	position.UpdateDefaultUpdatedAt = positionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// positionDescID is the schema descriptor for id field.
	positionDescID := positionFields[0].Descriptor()
	// position.DefaultID holds the default value on creation for the id field.
	position.DefaultID = positionDescID.Default.(func() uuid.UUID)
	positionattributehistoryFields := schema.PositionAttributeHistory{}.Fields()
	_ = positionattributehistoryFields
	// positionattributehistoryDescCreatedAt is the schema descriptor for created_at field.
	positionattributehistoryDescCreatedAt := positionattributehistoryFields[16].Descriptor()
	// positionattributehistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	positionattributehistory.DefaultCreatedAt = positionattributehistoryDescCreatedAt.Default.(func() time.Time)
	// positionattributehistoryDescID is the schema descriptor for id field.
	positionattributehistoryDescID := positionattributehistoryFields[0].Descriptor()
	// positionattributehistory.DefaultID holds the default value on creation for the id field.
	positionattributehistory.DefaultID = positionattributehistoryDescID.Default.(func() uuid.UUID)
	positionhistoryFields := schema.PositionHistory{}.Fields()
	_ = positionhistoryFields
	// positionhistoryDescIsActive is the schema descriptor for is_active field.
	positionhistoryDescIsActive := positionhistoryFields[7].Descriptor()
	// positionhistory.DefaultIsActive holds the default value on creation for the is_active field.
	positionhistory.DefaultIsActive = positionhistoryDescIsActive.Default.(bool)
	// positionhistoryDescIsRetroactive is the schema descriptor for is_retroactive field.
	positionhistoryDescIsRetroactive := positionhistoryFields[8].Descriptor()
	// positionhistory.DefaultIsRetroactive holds the default value on creation for the is_retroactive field.
	positionhistory.DefaultIsRetroactive = positionhistoryDescIsRetroactive.Default.(bool)
	// positionhistoryDescApprovalStatus is the schema descriptor for approval_status field.
	positionhistoryDescApprovalStatus := positionhistoryFields[11].Descriptor()
	// positionhistory.DefaultApprovalStatus holds the default value on creation for the approval_status field.
	positionhistory.DefaultApprovalStatus = positionhistoryDescApprovalStatus.Default.(string)
	// positionhistoryDescCreatedAt is the schema descriptor for created_at field.
	positionhistoryDescCreatedAt := positionhistoryFields[12].Descriptor()
	// positionhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	positionhistory.DefaultCreatedAt = positionhistoryDescCreatedAt.Default.(func() time.Time)
	// positionhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	positionhistoryDescUpdatedAt := positionhistoryFields[13].Descriptor()
	// positionhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	positionhistory.DefaultUpdatedAt = positionhistoryDescUpdatedAt.Default.(func() time.Time)
	// positionhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	positionhistory.UpdateDefaultUpdatedAt = positionhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	positionoccupancyhistoryFields := schema.PositionOccupancyHistory{}.Fields()
	_ = positionoccupancyhistoryFields
	// positionoccupancyhistoryDescIsActive is the schema descriptor for is_active field.
	positionoccupancyhistoryDescIsActive := positionoccupancyhistoryFields[6].Descriptor()
	// positionoccupancyhistory.DefaultIsActive holds the default value on creation for the is_active field.
	positionoccupancyhistory.DefaultIsActive = positionoccupancyhistoryDescIsActive.Default.(bool)
	// positionoccupancyhistoryDescFtePercentage is the schema descriptor for fte_percentage field.
	positionoccupancyhistoryDescFtePercentage := positionoccupancyhistoryFields[9].Descriptor()
	// positionoccupancyhistory.DefaultFtePercentage holds the default value on creation for the fte_percentage field.
	positionoccupancyhistory.DefaultFtePercentage = positionoccupancyhistoryDescFtePercentage.Default.(float64)
	// positionoccupancyhistoryDescCreatedAt is the schema descriptor for created_at field.
	positionoccupancyhistoryDescCreatedAt := positionoccupancyhistoryFields[17].Descriptor()
	// positionoccupancyhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	positionoccupancyhistory.DefaultCreatedAt = positionoccupancyhistoryDescCreatedAt.Default.(func() time.Time)
	// positionoccupancyhistoryDescUpdatedAt is the schema descriptor for updated_at field.
	positionoccupancyhistoryDescUpdatedAt := positionoccupancyhistoryFields[18].Descriptor()
	// positionoccupancyhistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	positionoccupancyhistory.DefaultUpdatedAt = positionoccupancyhistoryDescUpdatedAt.Default.(func() time.Time)
	// positionoccupancyhistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	positionoccupancyhistory.UpdateDefaultUpdatedAt = positionoccupancyhistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// positionoccupancyhistoryDescID is the schema descriptor for id field.
	positionoccupancyhistoryDescID := positionoccupancyhistoryFields[0].Descriptor()
	// positionoccupancyhistory.DefaultID holds the default value on creation for the id field.
	positionoccupancyhistory.DefaultID = positionoccupancyhistoryDescID.Default.(func() uuid.UUID)
}
