// Code generated by ent, DO NOT EDIT.

package positionattributehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the positionattributehistory type in the database.
	Label = "position_attribute_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldPositionID holds the string denoting the position_id field in the database.
	FieldPositionID = "position_id"
	// FieldPositionType holds the string denoting the position_type field in the database.
	FieldPositionType = "position_type"
	// FieldJobProfileID holds the string denoting the job_profile_id field in the database.
	FieldJobProfileID = "job_profile_id"
	// FieldDepartmentID holds the string denoting the department_id field in the database.
	FieldDepartmentID = "department_id"
	// FieldManagerPositionID holds the string denoting the manager_position_id field in the database.
	FieldManagerPositionID = "manager_position_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBudgetedFte holds the string denoting the budgeted_fte field in the database.
	FieldBudgetedFte = "budgeted_fte"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldEffectiveDate holds the string denoting the effective_date field in the database.
	FieldEffectiveDate = "effective_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldChangeReason holds the string denoting the change_reason field in the database.
	FieldChangeReason = "change_reason"
	// FieldChangedBy holds the string denoting the changed_by field in the database.
	FieldChangedBy = "changed_by"
	// FieldChangeType holds the string denoting the change_type field in the database.
	FieldChangeType = "change_type"
	// FieldSourceEventID holds the string denoting the source_event_id field in the database.
	FieldSourceEventID = "source_event_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgePosition holds the string denoting the position edge name in mutations.
	EdgePosition = "position"
	// Table holds the table name of the positionattributehistory in the database.
	Table = "position_attribute_histories"
	// PositionTable is the table that holds the position relation/edge.
	PositionTable = "position_attribute_histories"
	// PositionInverseTable is the table name for the Position entity.
	// It exists in this package in order to avoid circular dependency with the "position" package.
	PositionInverseTable = "positions"
	// PositionColumn is the table column denoting the position relation/edge.
	PositionColumn = "position_id"
)

// Columns holds all SQL columns for positionattributehistory fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldPositionID,
	FieldPositionType,
	FieldJobProfileID,
	FieldDepartmentID,
	FieldManagerPositionID,
	FieldStatus,
	FieldBudgetedFte,
	FieldDetails,
	FieldEffectiveDate,
	FieldEndDate,
	FieldChangeReason,
	FieldChangedBy,
	FieldChangeType,
	FieldSourceEventID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PositionAttributeHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByPositionID orders the results by the position_id field.
func ByPositionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionID, opts...).ToFunc()
}

// ByPositionType orders the results by the position_type field.
func ByPositionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositionType, opts...).ToFunc()
}

// ByJobProfileID orders the results by the job_profile_id field.
func ByJobProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobProfileID, opts...).ToFunc()
}

// ByDepartmentID orders the results by the department_id field.
func ByDepartmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartmentID, opts...).ToFunc()
}

// ByManagerPositionID orders the results by the manager_position_id field.
func ByManagerPositionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagerPositionID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBudgetedFte orders the results by the budgeted_fte field.
func ByBudgetedFte(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBudgetedFte, opts...).ToFunc()
}

// ByEffectiveDate orders the results by the effective_date field.
func ByEffectiveDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByChangeReason orders the results by the change_reason field.
func ByChangeReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangeReason, opts...).ToFunc()
}

// ByChangedBy orders the results by the changed_by field.
func ByChangedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedBy, opts...).ToFunc()
}

// ByChangeType orders the results by the change_type field.
func ByChangeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangeType, opts...).ToFunc()
}

// BySourceEventID orders the results by the source_event_id field.
func BySourceEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceEventID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPositionField orders the results by position field.
func ByPositionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPositionStep(), sql.OrderByField(field, opts...))
	}
}
func newPositionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PositionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PositionTable, PositionColumn),
	)
}
