// Code generated by ent, DO NOT EDIT.

package positionattributehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gaogu/cube-castle/go-app/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldTenantID, v))
}

// PositionID applies equality check predicate on the "position_id" field. It's identical to PositionIDEQ.
func PositionID(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldPositionID, v))
}

// PositionType applies equality check predicate on the "position_type" field. It's identical to PositionTypeEQ.
func PositionType(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldPositionType, v))
}

// JobProfileID applies equality check predicate on the "job_profile_id" field. It's identical to JobProfileIDEQ.
func JobProfileID(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldJobProfileID, v))
}

// DepartmentID applies equality check predicate on the "department_id" field. It's identical to DepartmentIDEQ.
func DepartmentID(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldDepartmentID, v))
}

// ManagerPositionID applies equality check predicate on the "manager_position_id" field. It's identical to ManagerPositionIDEQ.
func ManagerPositionID(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldManagerPositionID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldStatus, v))
}

// BudgetedFte applies equality check predicate on the "budgeted_fte" field. It's identical to BudgetedFteEQ.
func BudgetedFte(v float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldBudgetedFte, v))
}

// EffectiveDate applies equality check predicate on the "effective_date" field. It's identical to EffectiveDateEQ.
func EffectiveDate(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldEffectiveDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldEndDate, v))
}

// ChangeReason applies equality check predicate on the "change_reason" field. It's identical to ChangeReasonEQ.
func ChangeReason(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldChangeReason, v))
}

// ChangedBy applies equality check predicate on the "changed_by" field. It's identical to ChangedByEQ.
func ChangedBy(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangeType applies equality check predicate on the "change_type" field. It's identical to ChangeTypeEQ.
func ChangeType(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldChangeType, v))
}

// SourceEventID applies equality check predicate on the "source_event_id" field. It's identical to SourceEventIDEQ.
func SourceEventID(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldSourceEventID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldTenantID, v))
}

// PositionIDEQ applies the EQ predicate on the "position_id" field.
func PositionIDEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldPositionID, v))
}

// PositionIDNEQ applies the NEQ predicate on the "position_id" field.
func PositionIDNEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldPositionID, v))
}

// PositionIDIn applies the In predicate on the "position_id" field.
func PositionIDIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldPositionID, vs...))
}

// PositionIDNotIn applies the NotIn predicate on the "position_id" field.
func PositionIDNotIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldPositionID, vs...))
}

// PositionTypeEQ applies the EQ predicate on the "position_type" field.
func PositionTypeEQ(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldPositionType, v))
}

// PositionTypeNEQ applies the NEQ predicate on the "position_type" field.
func PositionTypeNEQ(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldPositionType, v))
}

// PositionTypeIn applies the In predicate on the "position_type" field.
func PositionTypeIn(vs ...string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldPositionType, vs...))
}

// PositionTypeNotIn applies the NotIn predicate on the "position_type" field.
func PositionTypeNotIn(vs ...string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldPositionType, vs...))
}

// PositionTypeGT applies the GT predicate on the "position_type" field.
func PositionTypeGT(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldPositionType, v))
}

// PositionTypeGTE applies the GTE predicate on the "position_type" field.
func PositionTypeGTE(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldPositionType, v))
}

// PositionTypeLT applies the LT predicate on the "position_type" field.
func PositionTypeLT(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldPositionType, v))
}

// PositionTypeLTE applies the LTE predicate on the "position_type" field.
func PositionTypeLTE(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldPositionType, v))
}

// PositionTypeContains applies the Contains predicate on the "position_type" field.
func PositionTypeContains(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldContains(FieldPositionType, v))
}

// PositionTypeHasPrefix applies the HasPrefix predicate on the "position_type" field.
func PositionTypeHasPrefix(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldHasPrefix(FieldPositionType, v))
}

// PositionTypeHasSuffix applies the HasSuffix predicate on the "position_type" field.
func PositionTypeHasSuffix(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldHasSuffix(FieldPositionType, v))
}

// PositionTypeEqualFold applies the EqualFold predicate on the "position_type" field.
func PositionTypeEqualFold(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEqualFold(FieldPositionType, v))
}

// PositionTypeContainsFold applies the ContainsFold predicate on the "position_type" field.
func PositionTypeContainsFold(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldContainsFold(FieldPositionType, v))
}

// JobProfileIDEQ applies the EQ predicate on the "job_profile_id" field.
func JobProfileIDEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldJobProfileID, v))
}

// JobProfileIDNEQ applies the NEQ predicate on the "job_profile_id" field.
func JobProfileIDNEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldJobProfileID, v))
}

// JobProfileIDIn applies the In predicate on the "job_profile_id" field.
func JobProfileIDIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldJobProfileID, vs...))
}

// JobProfileIDNotIn applies the NotIn predicate on the "job_profile_id" field.
func JobProfileIDNotIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldJobProfileID, vs...))
}

// JobProfileIDGT applies the GT predicate on the "job_profile_id" field.
func JobProfileIDGT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldJobProfileID, v))
}

// JobProfileIDGTE applies the GTE predicate on the "job_profile_id" field.
func JobProfileIDGTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldJobProfileID, v))
}

// JobProfileIDLT applies the LT predicate on the "job_profile_id" field.
func JobProfileIDLT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldJobProfileID, v))
}

// JobProfileIDLTE applies the LTE predicate on the "job_profile_id" field.
func JobProfileIDLTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldJobProfileID, v))
}

// DepartmentIDEQ applies the EQ predicate on the "department_id" field.
func DepartmentIDEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldDepartmentID, v))
}

// DepartmentIDNEQ applies the NEQ predicate on the "department_id" field.
func DepartmentIDNEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldDepartmentID, v))
}

// DepartmentIDIn applies the In predicate on the "department_id" field.
func DepartmentIDIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldDepartmentID, vs...))
}

// DepartmentIDNotIn applies the NotIn predicate on the "department_id" field.
func DepartmentIDNotIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldDepartmentID, vs...))
}

// DepartmentIDGT applies the GT predicate on the "department_id" field.
func DepartmentIDGT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldDepartmentID, v))
}

// DepartmentIDGTE applies the GTE predicate on the "department_id" field.
func DepartmentIDGTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldDepartmentID, v))
}

// DepartmentIDLT applies the LT predicate on the "department_id" field.
func DepartmentIDLT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldDepartmentID, v))
}

// DepartmentIDLTE applies the LTE predicate on the "department_id" field.
func DepartmentIDLTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldDepartmentID, v))
}

// ManagerPositionIDEQ applies the EQ predicate on the "manager_position_id" field.
func ManagerPositionIDEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldManagerPositionID, v))
}

// ManagerPositionIDNEQ applies the NEQ predicate on the "manager_position_id" field.
func ManagerPositionIDNEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldManagerPositionID, v))
}

// ManagerPositionIDIn applies the In predicate on the "manager_position_id" field.
func ManagerPositionIDIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldManagerPositionID, vs...))
}

// ManagerPositionIDNotIn applies the NotIn predicate on the "manager_position_id" field.
func ManagerPositionIDNotIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldManagerPositionID, vs...))
}

// ManagerPositionIDGT applies the GT predicate on the "manager_position_id" field.
func ManagerPositionIDGT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldManagerPositionID, v))
}

// ManagerPositionIDGTE applies the GTE predicate on the "manager_position_id" field.
func ManagerPositionIDGTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldManagerPositionID, v))
}

// ManagerPositionIDLT applies the LT predicate on the "manager_position_id" field.
func ManagerPositionIDLT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldManagerPositionID, v))
}

// ManagerPositionIDLTE applies the LTE predicate on the "manager_position_id" field.
func ManagerPositionIDLTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldManagerPositionID, v))
}

// ManagerPositionIDIsNil applies the IsNil predicate on the "manager_position_id" field.
func ManagerPositionIDIsNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIsNull(FieldManagerPositionID))
}

// ManagerPositionIDNotNil applies the NotNil predicate on the "manager_position_id" field.
func ManagerPositionIDNotNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotNull(FieldManagerPositionID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldContainsFold(FieldStatus, v))
}

// BudgetedFteEQ applies the EQ predicate on the "budgeted_fte" field.
func BudgetedFteEQ(v float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldBudgetedFte, v))
}

// BudgetedFteNEQ applies the NEQ predicate on the "budgeted_fte" field.
func BudgetedFteNEQ(v float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldBudgetedFte, v))
}

// BudgetedFteIn applies the In predicate on the "budgeted_fte" field.
func BudgetedFteIn(vs ...float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldBudgetedFte, vs...))
}

// BudgetedFteNotIn applies the NotIn predicate on the "budgeted_fte" field.
func BudgetedFteNotIn(vs ...float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldBudgetedFte, vs...))
}

// BudgetedFteGT applies the GT predicate on the "budgeted_fte" field.
func BudgetedFteGT(v float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldBudgetedFte, v))
}

// BudgetedFteGTE applies the GTE predicate on the "budgeted_fte" field.
func BudgetedFteGTE(v float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldBudgetedFte, v))
}

// BudgetedFteLT applies the LT predicate on the "budgeted_fte" field.
func BudgetedFteLT(v float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldBudgetedFte, v))
}

// BudgetedFteLTE applies the LTE predicate on the "budgeted_fte" field.
func BudgetedFteLTE(v float64) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldBudgetedFte, v))
}

// DetailsIsNil applies the IsNil predicate on the "details" field.
func DetailsIsNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIsNull(FieldDetails))
}

// DetailsNotNil applies the NotNil predicate on the "details" field.
func DetailsNotNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotNull(FieldDetails))
}

// EffectiveDateEQ applies the EQ predicate on the "effective_date" field.
func EffectiveDateEQ(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldEffectiveDate, v))
}

// EffectiveDateNEQ applies the NEQ predicate on the "effective_date" field.
func EffectiveDateNEQ(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldEffectiveDate, v))
}

// EffectiveDateIn applies the In predicate on the "effective_date" field.
func EffectiveDateIn(vs ...time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldEffectiveDate, vs...))
}

// EffectiveDateNotIn applies the NotIn predicate on the "effective_date" field.
func EffectiveDateNotIn(vs ...time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldEffectiveDate, vs...))
}

// EffectiveDateGT applies the GT predicate on the "effective_date" field.
func EffectiveDateGT(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldEffectiveDate, v))
}

// EffectiveDateGTE applies the GTE predicate on the "effective_date" field.
func EffectiveDateGTE(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldEffectiveDate, v))
}

// EffectiveDateLT applies the LT predicate on the "effective_date" field.
func EffectiveDateLT(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldEffectiveDate, v))
}

// EffectiveDateLTE applies the LTE predicate on the "effective_date" field.
func EffectiveDateLTE(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldEffectiveDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotNull(FieldEndDate))
}

// ChangeReasonEQ applies the EQ predicate on the "change_reason" field.
func ChangeReasonEQ(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldChangeReason, v))
}

// ChangeReasonNEQ applies the NEQ predicate on the "change_reason" field.
func ChangeReasonNEQ(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldChangeReason, v))
}

// ChangeReasonIn applies the In predicate on the "change_reason" field.
func ChangeReasonIn(vs ...string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldChangeReason, vs...))
}

// ChangeReasonNotIn applies the NotIn predicate on the "change_reason" field.
func ChangeReasonNotIn(vs ...string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldChangeReason, vs...))
}

// ChangeReasonGT applies the GT predicate on the "change_reason" field.
func ChangeReasonGT(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldChangeReason, v))
}

// ChangeReasonGTE applies the GTE predicate on the "change_reason" field.
func ChangeReasonGTE(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldChangeReason, v))
}

// ChangeReasonLT applies the LT predicate on the "change_reason" field.
func ChangeReasonLT(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldChangeReason, v))
}

// ChangeReasonLTE applies the LTE predicate on the "change_reason" field.
func ChangeReasonLTE(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldChangeReason, v))
}

// ChangeReasonContains applies the Contains predicate on the "change_reason" field.
func ChangeReasonContains(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldContains(FieldChangeReason, v))
}

// ChangeReasonHasPrefix applies the HasPrefix predicate on the "change_reason" field.
func ChangeReasonHasPrefix(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldHasPrefix(FieldChangeReason, v))
}

// ChangeReasonHasSuffix applies the HasSuffix predicate on the "change_reason" field.
func ChangeReasonHasSuffix(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldHasSuffix(FieldChangeReason, v))
}

// ChangeReasonIsNil applies the IsNil predicate on the "change_reason" field.
func ChangeReasonIsNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIsNull(FieldChangeReason))
}

// ChangeReasonNotNil applies the NotNil predicate on the "change_reason" field.
func ChangeReasonNotNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotNull(FieldChangeReason))
}

// ChangeReasonEqualFold applies the EqualFold predicate on the "change_reason" field.
func ChangeReasonEqualFold(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEqualFold(FieldChangeReason, v))
}

// ChangeReasonContainsFold applies the ContainsFold predicate on the "change_reason" field.
func ChangeReasonContainsFold(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldContainsFold(FieldChangeReason, v))
}

// ChangedByEQ applies the EQ predicate on the "changed_by" field.
func ChangedByEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangedByNEQ applies the NEQ predicate on the "changed_by" field.
func ChangedByNEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldChangedBy, v))
}

// ChangedByIn applies the In predicate on the "changed_by" field.
func ChangedByIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldChangedBy, vs...))
}

// ChangedByNotIn applies the NotIn predicate on the "changed_by" field.
func ChangedByNotIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldChangedBy, vs...))
}

// ChangedByGT applies the GT predicate on the "changed_by" field.
func ChangedByGT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldChangedBy, v))
}

// ChangedByGTE applies the GTE predicate on the "changed_by" field.
func ChangedByGTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldChangedBy, v))
}

// ChangedByLT applies the LT predicate on the "changed_by" field.
func ChangedByLT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldChangedBy, v))
}

// ChangedByLTE applies the LTE predicate on the "changed_by" field.
func ChangedByLTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldChangedBy, v))
}

// ChangeTypeEQ applies the EQ predicate on the "change_type" field.
func ChangeTypeEQ(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldChangeType, v))
}

// ChangeTypeNEQ applies the NEQ predicate on the "change_type" field.
func ChangeTypeNEQ(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldChangeType, v))
}

// ChangeTypeIn applies the In predicate on the "change_type" field.
func ChangeTypeIn(vs ...string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldChangeType, vs...))
}

// ChangeTypeNotIn applies the NotIn predicate on the "change_type" field.
func ChangeTypeNotIn(vs ...string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldChangeType, vs...))
}

// ChangeTypeGT applies the GT predicate on the "change_type" field.
func ChangeTypeGT(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldChangeType, v))
}

// ChangeTypeGTE applies the GTE predicate on the "change_type" field.
func ChangeTypeGTE(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldChangeType, v))
}

// ChangeTypeLT applies the LT predicate on the "change_type" field.
func ChangeTypeLT(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldChangeType, v))
}

// ChangeTypeLTE applies the LTE predicate on the "change_type" field.
func ChangeTypeLTE(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldChangeType, v))
}

// ChangeTypeContains applies the Contains predicate on the "change_type" field.
func ChangeTypeContains(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldContains(FieldChangeType, v))
}

// ChangeTypeHasPrefix applies the HasPrefix predicate on the "change_type" field.
func ChangeTypeHasPrefix(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldHasPrefix(FieldChangeType, v))
}

// ChangeTypeHasSuffix applies the HasSuffix predicate on the "change_type" field.
func ChangeTypeHasSuffix(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldHasSuffix(FieldChangeType, v))
}

// ChangeTypeIsNil applies the IsNil predicate on the "change_type" field.
func ChangeTypeIsNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIsNull(FieldChangeType))
}

// ChangeTypeNotNil applies the NotNil predicate on the "change_type" field.
func ChangeTypeNotNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotNull(FieldChangeType))
}

// ChangeTypeEqualFold applies the EqualFold predicate on the "change_type" field.
func ChangeTypeEqualFold(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEqualFold(FieldChangeType, v))
}

// ChangeTypeContainsFold applies the ContainsFold predicate on the "change_type" field.
func ChangeTypeContainsFold(v string) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldContainsFold(FieldChangeType, v))
}

// SourceEventIDEQ applies the EQ predicate on the "source_event_id" field.
func SourceEventIDEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldSourceEventID, v))
}

// SourceEventIDNEQ applies the NEQ predicate on the "source_event_id" field.
func SourceEventIDNEQ(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldSourceEventID, v))
}

// SourceEventIDIn applies the In predicate on the "source_event_id" field.
func SourceEventIDIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldSourceEventID, vs...))
}

// SourceEventIDNotIn applies the NotIn predicate on the "source_event_id" field.
func SourceEventIDNotIn(vs ...uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldSourceEventID, vs...))
}

// SourceEventIDGT applies the GT predicate on the "source_event_id" field.
func SourceEventIDGT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldSourceEventID, v))
}

// SourceEventIDGTE applies the GTE predicate on the "source_event_id" field.
func SourceEventIDGTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldSourceEventID, v))
}

// SourceEventIDLT applies the LT predicate on the "source_event_id" field.
func SourceEventIDLT(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldSourceEventID, v))
}

// SourceEventIDLTE applies the LTE predicate on the "source_event_id" field.
func SourceEventIDLTE(v uuid.UUID) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldSourceEventID, v))
}

// SourceEventIDIsNil applies the IsNil predicate on the "source_event_id" field.
func SourceEventIDIsNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIsNull(FieldSourceEventID))
}

// SourceEventIDNotNil applies the NotNil predicate on the "source_event_id" field.
func SourceEventIDNotNil() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotNull(FieldSourceEventID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPosition applies the HasEdge predicate on the "position" edge.
func HasPosition() predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PositionTable, PositionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPositionWith applies the HasEdge predicate on the "position" edge with a given conditions (other predicates).
func HasPositionWith(preds ...predicate.Position) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(func(s *sql.Selector) {
		step := newPositionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PositionAttributeHistory) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PositionAttributeHistory) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PositionAttributeHistory) predicate.PositionAttributeHistory {
	return predicate.PositionAttributeHistory(sql.NotPredicates(p))
}
