export const POSITION_FIXTURE_CODE = 'P1234567';

export const POSITION_GRAPHQL_FIXTURES = {
  positions: {
    data: {
      positions: {
        data: [
          {
            code: POSITION_FIXTURE_CODE,
            title: '生命周期演示岗位',
            jobFamilyGroupCode: 'OPER',
            jobFamilyGroupName: '运营管理',
            jobFamilyCode: 'OPER-OPS',
            jobFamilyName: '运营支持',
            jobRoleCode: 'OPER-OPS-SUPV',
            jobRoleName: '运营主管',
            jobLevelCode: 'M2',
            jobLevelName: '经理二级',
            organizationCode: 'ORG-A',
            organizationName: '生命周期演示组织',
            positionType: 'REGULAR',
            employmentType: 'FULL_TIME',
            headcountCapacity: 2,
            headcountInUse: 1,
            availableHeadcount: 1,
            gradeLevel: null,
            reportsToPositionCode: 'P-LEAD-001',
            status: 'ACTIVE',
            effectiveDate: '2024-01-01',
            endDate: null,
            isCurrent: true,
            isFuture: false,
            createdAt: '2024-01-01T00:00:00.000Z',
            updatedAt: '2024-03-15T10:00:00.000Z',
          },
        ],
        pagination: {
          total: 1,
          page: 1,
          pageSize: 25,
          hasNext: false,
          hasPrevious: false,
        },
        totalCount: 1,
      },
    },
  },
  positionDetail: {
    data: {
      position: {
        code: POSITION_FIXTURE_CODE,
        recordId: 'POS-REC-001',
        title: '生命周期演示岗位',
        jobFamilyGroupCode: 'OPER',
        jobFamilyGroupName: '运营管理',
        jobFamilyCode: 'OPER-OPS',
        jobFamilyName: '运营支持',
        jobRoleCode: 'OPER-OPS-SUPV',
        jobRoleName: '运营主管',
        jobLevelCode: 'M2',
        jobLevelName: '经理二级',
        organizationCode: 'ORG-A',
        organizationName: '生命周期演示组织',
        positionType: 'REGULAR',
        employmentType: 'FULL_TIME',
        headcountCapacity: 2,
        headcountInUse: 1,
        availableHeadcount: 1,
        gradeLevel: null,
        reportsToPositionCode: 'P-LEAD-001',
        status: 'ACTIVE',
        effectiveDate: '2024-01-01',
        endDate: null,
        isCurrent: true,
        isFuture: false,
        createdAt: '2024-01-01T00:00:00.000Z',
        updatedAt: '2024-03-15T10:00:00.000Z',
        currentAssignment: {
          assignmentId: 'ASSIGN-001',
          positionCode: POSITION_FIXTURE_CODE,
          positionRecordId: 'POS-REC-001',
          employeeId: 'EMP-001',
          employeeName: '张三',
          employeeNumber: 'E001',
          assignmentType: 'PRIMARY',
          assignmentStatus: 'ACTIVE',
          fte: 1,
          effectiveDate: '2024-03-01',
          endDate: null,
          isCurrent: true,
          notes: '夜班负责人',
          createdAt: '2024-03-01T08:00:00.000Z',
          updatedAt: '2024-03-05T09:00:00.000Z',
        },
      },
      positionTimeline: [
        {
          recordId: 'TIMELINE-001',
          status: 'ACTIVE',
          title: '岗位创建',
          effectiveDate: '2024-01-01',
          endDate: null,
          changeReason: '年度人力预算批准',
          isCurrent: false,
        },
        {
          recordId: 'TIMELINE-002',
          status: 'ACTIVE',
          title: '岗位扩编',
          effectiveDate: '2024-03-01',
          endDate: null,
          changeReason: '夜班运营需求增加',
          isCurrent: true,
        },
      ],
      positionAssignments: {
        data: [
          {
            assignmentId: 'ASSIGN-001',
            positionCode: POSITION_FIXTURE_CODE,
            positionRecordId: 'POS-REC-001',
            employeeId: 'EMP-001',
            employeeName: '张三',
            employeeNumber: 'E001',
            assignmentType: 'PRIMARY',
            assignmentStatus: 'ACTIVE',
            fte: 1,
            effectiveDate: '2024-03-01',
            endDate: null,
            isCurrent: true,
            notes: '夜班负责人',
            createdAt: '2024-03-01T08:00:00.000Z',
            updatedAt: '2024-03-05T09:00:00.000Z',
          },
          {
            assignmentId: 'ASSIGN-000',
            positionCode: POSITION_FIXTURE_CODE,
            positionRecordId: 'POS-REC-000',
            employeeId: 'EMP-000',
            employeeName: '李四',
            employeeNumber: 'E000',
            assignmentType: 'PRIMARY',
            assignmentStatus: 'ENDED',
            fte: 1,
            effectiveDate: '2023-01-01',
            endDate: '2024-02-28',
            isCurrent: false,
            notes: '内部轮岗结束',
            createdAt: '2023-01-01T08:00:00.000Z',
            updatedAt: '2024-02-28T09:00:00.000Z',
          },
        ],
      },
      positionTransfers: {
        data: [
          {
            transferId: 'TRANSFER-001',
            positionCode: POSITION_FIXTURE_CODE,
            fromOrganizationCode: 'ORG-A',
            toOrganizationCode: 'ORG-B',
            effectiveDate: '2024-05-01',
            initiatedBy: {
              id: 'USER-001',
              name: '王五',
            },
            operationReason: '业务线整合',
            createdAt: '2024-04-25T12:30:00.000Z',
          },
        ],
      },
      positionVersions: [
        {
          recordId: 'POS-REC-001',
          code: POSITION_FIXTURE_CODE,
          title: '生命周期演示岗位',
          jobFamilyGroupCode: 'OPER',
          jobFamilyCode: 'OPER-OPS',
          jobRoleCode: 'OPER-OPS-SUPV',
          jobLevelCode: 'M2',
          organizationCode: 'ORG-A',
          organizationName: '生命周期演示组织',
          positionType: 'REGULAR',
          employmentType: 'FULL_TIME',
          gradeLevel: null,
          headcountCapacity: 2,
          headcountInUse: 1,
          availableHeadcount: 1,
          reportsToPositionCode: 'P-LEAD-001',
          status: 'ACTIVE',
          effectiveDate: '2024-01-01',
          endDate: null,
          isCurrent: true,
          createdAt: '2024-01-01T00:00:00.000Z',
          updatedAt: '2024-03-15T10:00:00.000Z',
        },
        {
          recordId: 'POS-REC-002',
          code: POSITION_FIXTURE_CODE,
          title: '生命周期演示岗位（规划）',
          jobFamilyGroupCode: 'OPER',
          jobFamilyCode: 'OPER-OPS',
          jobRoleCode: 'OPER-OPS-SUPV',
          jobLevelCode: 'M2',
          organizationCode: 'ORG-A',
          organizationName: '生命周期演示组织',
          positionType: 'REGULAR',
          employmentType: 'FULL_TIME',
          gradeLevel: null,
          headcountCapacity: 3,
          headcountInUse: 1,
          availableHeadcount: 2,
          reportsToPositionCode: 'P-LEAD-001',
          status: 'PLANNED',
          effectiveDate: '2024-06-01',
          endDate: null,
          isCurrent: false,
          createdAt: '2024-05-01T00:00:00.000Z',
          updatedAt: '2024-05-01T00:00:00.000Z',
        },
      ],
    },
  },
  vacantPositions: {
    data: {
      vacantPositions: {
        data: [
          {
            positionCode: 'P-VAC-001',
            organizationCode: 'ORG-B',
            organizationName: '缺编演示组织',
            jobFamilyCode: 'OPER-OPS',
            jobRoleCode: 'OPER-OPS-SUPV',
            jobLevelCode: 'S1',
            vacantSince: '2024-06-01',
            headcountCapacity: 3,
            headcountAvailable: 2,
            totalAssignments: 5,
          },
        ],
        pagination: {
          total: 1,
          page: 1,
          pageSize: 25,
          hasNext: false,
          hasPrevious: false,
        },
        totalCount: 1,
      },
    },
  },
  headcountStats: {
    data: {
      positionHeadcountStats: {
        organizationCode: 'ORG-A',
        organizationName: '生命周期演示组织',
        totalCapacity: 5,
        totalFilled: 3,
        totalAvailable: 2,
        fillRate: 0.6,
        byLevel: [
          {
            jobLevelCode: 'S1',
            capacity: 2,
            utilized: 1,
            available: 1,
          },
          {
            jobLevelCode: 'M2',
            capacity: 3,
            utilized: 2,
            available: 1,
          },
        ],
        byType: [
          {
            positionType: 'REGULAR',
            capacity: 4,
            filled: 3,
            available: 1,
          },
          {
            positionType: 'CONTRACT',
            capacity: 1,
            filled: 0,
            available: 1,
          },
        ],
        byFamily: [
          {
            jobFamilyCode: 'OPER-OPS',
            jobFamilyName: '运营支持',
            capacity: 5,
            utilized: 3,
            available: 2,
          },
        ],
      },
    },
  },
};

export const POSITIONS_QUERY_NAME = 'EnterprisePositions';
export const POSITION_DETAIL_QUERY_NAME = 'PositionDetail';
export const VACANT_POSITIONS_QUERY_NAME = 'VacantPositions';
export const POSITION_HEADCOUNT_STATS_QUERY_NAME = 'PositionHeadcountStats';
