// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// PositionHistory is the predicate function for positionhistory builders.
type PositionHistory func(*sql.Selector)
