// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AssignmentDetailsColumns holds the columns for the "assignment_details" table.
	AssignmentDetailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "pay_grade_id", Type: field.TypeUUID, Nullable: true},
		{Name: "compensation_plan_id", Type: field.TypeUUID, Nullable: true},
		{Name: "work_location", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "work_arrangement", Type: field.TypeEnum, Nullable: true, Enums: []string{"ON_SITE", "REMOTE", "HYBRID"}},
		{Name: "assignment_reason", Type: field.TypeEnum, Nullable: true, Enums: []string{"NEW_HIRE", "PROMOTION", "TRANSFER", "DEMOTION", "LATERAL_MOVE", "TEMPORARY_ASSIGNMENT", "RETURN_FROM_LEAVE"}},
		{Name: "change_reason", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "approved_by", Type: field.TypeUUID, Nullable: true},
		{Name: "approved_at", Type: field.TypeTime, Nullable: true},
		{Name: "approval_status", Type: field.TypeEnum, Enums: []string{"PENDING", "APPROVED", "REJECTED"}, Default: "APPROVED"},
		{Name: "custom_fields", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "assignment_id", Type: field.TypeUUID},
	}
	// AssignmentDetailsTable holds the schema information for the "assignment_details" table.
	AssignmentDetailsTable = &schema.Table{
		Name:       "assignment_details",
		Columns:    AssignmentDetailsColumns,
		PrimaryKey: []*schema.Column{AssignmentDetailsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "assignment_details_position_assignments_details",
				Columns:    []*schema.Column{AssignmentDetailsColumns[15]},
				RefColumns: []*schema.Column{PositionAssignmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AssignmentHistoriesColumns holds the columns for the "assignment_histories" table.
	AssignmentHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeEnum, Enums: []string{"CREATED", "UPDATED", "ENDED", "EXTENDED"}},
		{Name: "event_date", Type: field.TypeTime},
		{Name: "previous_values", Type: field.TypeJSON, Nullable: true},
		{Name: "new_values", Type: field.TypeJSON, Nullable: true},
		{Name: "reason", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "changed_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "assignment_id", Type: field.TypeUUID},
	}
	// AssignmentHistoriesTable holds the schema information for the "assignment_histories" table.
	AssignmentHistoriesTable = &schema.Table{
		Name:       "assignment_histories",
		Columns:    AssignmentHistoriesColumns,
		PrimaryKey: []*schema.Column{AssignmentHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "assignment_histories_position_assignments_history",
				Columns:    []*schema.Column{AssignmentHistoriesColumns[9]},
				RefColumns: []*schema.Column{PositionAssignmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "business_id", Type: field.TypeString, Unique: true, Size: 8},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "employee_type", Type: field.TypeEnum, Enums: []string{"FULL_TIME", "PART_TIME", "CONTRACTOR", "INTERN"}},
		{Name: "employee_number", Type: field.TypeString, Size: 50},
		{Name: "first_name", Type: field.TypeString, Size: 100},
		{Name: "last_name", Type: field.TypeString, Size: 100},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "personal_email", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "phone_number", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "employment_status", Type: field.TypeEnum, Enums: []string{"ACTIVE", "ON_LEAVE", "TERMINATED", "SUSPENDED", "PENDING_START"}, Default: "PENDING_START"},
		{Name: "hire_date", Type: field.TypeTime},
		{Name: "termination_date", Type: field.TypeTime, Nullable: true},
		{Name: "employee_details", Type: field.TypeJSON, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "position", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "current_position_id", Type: field.TypeUUID, Nullable: true},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:       "employees",
		Columns:    EmployeesColumns,
		PrimaryKey: []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "employees_positions_current_incumbents",
				Columns:    []*schema.Column{EmployeesColumns[18]},
				RefColumns: []*schema.Column{PositionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "employee_tenant_id_employee_type",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[2], EmployeesColumns[3]},
			},
			{
				Name:    "employee_business_id",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[1]},
			},
			{
				Name:    "employee_tenant_id_business_id",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[2], EmployeesColumns[1]},
			},
			{
				Name:    "employee_tenant_id_employee_number",
				Unique:  true,
				Columns: []*schema.Column{EmployeesColumns[2], EmployeesColumns[4]},
			},
			{
				Name:    "employee_tenant_id_email",
				Unique:  true,
				Columns: []*schema.Column{EmployeesColumns[2], EmployeesColumns[7]},
			},
			{
				Name:    "employee_tenant_id_employment_status",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[2], EmployeesColumns[10]},
			},
			{
				Name:    "employee_current_position_id",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[18]},
			},
			{
				Name:    "employee_tenant_id_hire_date",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[2], EmployeesColumns[11]},
			},
			{
				Name:    "employee_tenant_id_employment_status_employee_type",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[2], EmployeesColumns[10], EmployeesColumns[3]},
			},
			{
				Name:    "employee_email",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[7]},
			},
			{
				Name:    "employee_name",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[14]},
			},
		},
	}
	// OrganizationUnitsColumns holds the columns for the "organization_units" table.
	OrganizationUnitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "business_id", Type: field.TypeString, Unique: true, Size: 6},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "unit_type", Type: field.TypeEnum, Enums: []string{"DEPARTMENT", "COST_CENTER", "COMPANY", "PROJECT_TEAM"}},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "level", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ACTIVE", "INACTIVE", "PLANNED"}, Default: "ACTIVE"},
		{Name: "profile", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "parent_unit_id", Type: field.TypeUUID, Nullable: true},
	}
	// OrganizationUnitsTable holds the schema information for the "organization_units" table.
	OrganizationUnitsTable = &schema.Table{
		Name:       "organization_units",
		Columns:    OrganizationUnitsColumns,
		PrimaryKey: []*schema.Column{OrganizationUnitsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_units_organization_units_children",
				Columns:    []*schema.Column{OrganizationUnitsColumns[11]},
				RefColumns: []*schema.Column{OrganizationUnitsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationunit_tenant_id_unit_type",
				Unique:  false,
				Columns: []*schema.Column{OrganizationUnitsColumns[2], OrganizationUnitsColumns[3]},
			},
			{
				Name:    "organizationunit_business_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationUnitsColumns[1]},
			},
			{
				Name:    "organizationunit_tenant_id_business_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationUnitsColumns[2], OrganizationUnitsColumns[1]},
			},
			{
				Name:    "organizationunit_parent_unit_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationUnitsColumns[11]},
			},
			{
				Name:    "organizationunit_tenant_id_name",
				Unique:  false,
				Columns: []*schema.Column{OrganizationUnitsColumns[2], OrganizationUnitsColumns[4]},
			},
			{
				Name:    "organizationunit_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{OrganizationUnitsColumns[2], OrganizationUnitsColumns[7]},
			},
			{
				Name:    "organizationunit_tenant_id_unit_type_status",
				Unique:  false,
				Columns: []*schema.Column{OrganizationUnitsColumns[2], OrganizationUnitsColumns[3], OrganizationUnitsColumns[7]},
			},
		},
	}
	// PositionsColumns holds the columns for the "positions" table.
	PositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "business_id", Type: field.TypeString, Unique: true, Size: 7},
		{Name: "position_type", Type: field.TypeEnum, Enums: []string{"FULL_TIME", "PART_TIME", "CONTINGENT_WORKER", "INTERN"}},
		{Name: "job_profile_id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"OPEN", "FILLED", "FROZEN", "PENDING_ELIMINATION"}, Default: "OPEN"},
		{Name: "budgeted_fte", Type: field.TypeFloat64, Default: 1},
		{Name: "details", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "department_id", Type: field.TypeUUID},
		{Name: "manager_position_id", Type: field.TypeUUID, Nullable: true},
	}
	// PositionsTable holds the schema information for the "positions" table.
	PositionsTable = &schema.Table{
		Name:       "positions",
		Columns:    PositionsColumns,
		PrimaryKey: []*schema.Column{PositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "positions_organization_units_positions",
				Columns:    []*schema.Column{PositionsColumns[10]},
				RefColumns: []*schema.Column{OrganizationUnitsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "positions_positions_direct_reports",
				Columns:    []*schema.Column{PositionsColumns[11]},
				RefColumns: []*schema.Column{PositionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "position_tenant_id_position_type",
				Unique:  false,
				Columns: []*schema.Column{PositionsColumns[1], PositionsColumns[3]},
			},
			{
				Name:    "position_department_id",
				Unique:  false,
				Columns: []*schema.Column{PositionsColumns[10]},
			},
			{
				Name:    "position_manager_position_id",
				Unique:  false,
				Columns: []*schema.Column{PositionsColumns[11]},
			},
			{
				Name:    "position_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{PositionsColumns[1], PositionsColumns[5]},
			},
			{
				Name:    "position_job_profile_id",
				Unique:  false,
				Columns: []*schema.Column{PositionsColumns[4]},
			},
			{
				Name:    "position_tenant_id_budgeted_fte",
				Unique:  false,
				Columns: []*schema.Column{PositionsColumns[1], PositionsColumns[6]},
			},
			{
				Name:    "position_tenant_id_department_id_status",
				Unique:  false,
				Columns: []*schema.Column{PositionsColumns[1], PositionsColumns[10], PositionsColumns[5]},
			},
		},
	}
	// PositionAssignmentsColumns holds the columns for the "position_assignments" table.
	PositionAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "is_current", Type: field.TypeBool, Default: false},
		{Name: "fte", Type: field.TypeFloat64, Default: 1},
		{Name: "assignment_type", Type: field.TypeEnum, Enums: []string{"PRIMARY", "SECONDARY", "ACTING"}, Default: "PRIMARY"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "employee_id", Type: field.TypeUUID},
		{Name: "position_id", Type: field.TypeUUID},
	}
	// PositionAssignmentsTable holds the schema information for the "position_assignments" table.
	PositionAssignmentsTable = &schema.Table{
		Name:       "position_assignments",
		Columns:    PositionAssignmentsColumns,
		PrimaryKey: []*schema.Column{PositionAssignmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "position_assignments_employees_assignments",
				Columns:    []*schema.Column{PositionAssignmentsColumns[9]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "position_assignments_positions_assignments",
				Columns:    []*schema.Column{PositionAssignmentsColumns[10]},
				RefColumns: []*schema.Column{PositionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "positionassignment_tenant_id_employee_id_is_current",
				Unique:  false,
				Columns: []*schema.Column{PositionAssignmentsColumns[1], PositionAssignmentsColumns[9], PositionAssignmentsColumns[4]},
			},
			{
				Name:    "positionassignment_tenant_id_position_id_is_current",
				Unique:  false,
				Columns: []*schema.Column{PositionAssignmentsColumns[1], PositionAssignmentsColumns[10], PositionAssignmentsColumns[4]},
			},
			{
				Name:    "positionassignment_tenant_id_employee_id_is_current_assignment_type",
				Unique:  true,
				Columns: []*schema.Column{PositionAssignmentsColumns[1], PositionAssignmentsColumns[9], PositionAssignmentsColumns[4], PositionAssignmentsColumns[6]},
			},
		},
	}
	// PositionAttributeHistoriesColumns holds the columns for the "position_attribute_histories" table.
	PositionAttributeHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "position_type", Type: field.TypeString},
		{Name: "job_profile_id", Type: field.TypeUUID},
		{Name: "department_id", Type: field.TypeUUID},
		{Name: "manager_position_id", Type: field.TypeUUID, Nullable: true},
		{Name: "status", Type: field.TypeString},
		{Name: "budgeted_fte", Type: field.TypeFloat64},
		{Name: "details", Type: field.TypeJSON, Nullable: true},
		{Name: "effective_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "change_reason", Type: field.TypeString, Nullable: true},
		{Name: "changed_by", Type: field.TypeUUID},
		{Name: "change_type", Type: field.TypeString, Nullable: true},
		{Name: "source_event_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "position_id", Type: field.TypeUUID},
	}
	// PositionAttributeHistoriesTable holds the schema information for the "position_attribute_histories" table.
	PositionAttributeHistoriesTable = &schema.Table{
		Name:       "position_attribute_histories",
		Columns:    PositionAttributeHistoriesColumns,
		PrimaryKey: []*schema.Column{PositionAttributeHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "position_attribute_histories_positions_attribute_history",
				Columns:    []*schema.Column{PositionAttributeHistoriesColumns[16]},
				RefColumns: []*schema.Column{PositionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "positionattributehistory_position_id_effective_date",
				Unique:  false,
				Columns: []*schema.Column{PositionAttributeHistoriesColumns[16], PositionAttributeHistoriesColumns[9]},
			},
			{
				Name:    "positionattributehistory_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PositionAttributeHistoriesColumns[1]},
			},
			{
				Name:    "positionattributehistory_effective_date_end_date",
				Unique:  false,
				Columns: []*schema.Column{PositionAttributeHistoriesColumns[9], PositionAttributeHistoriesColumns[10]},
			},
			{
				Name:    "positionattributehistory_changed_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{PositionAttributeHistoriesColumns[12], PositionAttributeHistoriesColumns[15]},
			},
			{
				Name:    "positionattributehistory_source_event_id",
				Unique:  false,
				Columns: []*schema.Column{PositionAttributeHistoriesColumns[14]},
			},
			{
				Name:    "positionattributehistory_department_id_effective_date",
				Unique:  false,
				Columns: []*schema.Column{PositionAttributeHistoriesColumns[4], PositionAttributeHistoriesColumns[9]},
			},
			{
				Name:    "positionattributehistory_position_id_status_effective_date",
				Unique:  false,
				Columns: []*schema.Column{PositionAttributeHistoriesColumns[16], PositionAttributeHistoriesColumns[6], PositionAttributeHistoriesColumns[9]},
			},
		},
	}
	// PositionHistoriesColumns holds the columns for the "position_histories" table.
	PositionHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "employee_id", Type: field.TypeString},
		{Name: "organization_id", Type: field.TypeString},
		{Name: "position_title", Type: field.TypeString},
		{Name: "department", Type: field.TypeString},
		{Name: "effective_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_retroactive", Type: field.TypeBool, Default: false},
		{Name: "salary_data", Type: field.TypeJSON, Nullable: true},
		{Name: "change_reason", Type: field.TypeString, Nullable: true},
		{Name: "approval_status", Type: field.TypeString, Default: "approved"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PositionHistoriesTable holds the schema information for the "position_histories" table.
	PositionHistoriesTable = &schema.Table{
		Name:       "position_histories",
		Columns:    PositionHistoriesColumns,
		PrimaryKey: []*schema.Column{PositionHistoriesColumns[0]},
	}
	// PositionOccupancyHistoriesColumns holds the columns for the "position_occupancy_histories" table.
	PositionOccupancyHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "end_date", Type: field.TypeTime, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "assignment_type", Type: field.TypeEnum, Enums: []string{"REGULAR", "INTERIM", "ACTING", "TEMPORARY", "SECONDMENT"}, Default: "REGULAR"},
		{Name: "assignment_reason", Type: field.TypeString, Nullable: true},
		{Name: "fte_percentage", Type: field.TypeFloat64, Default: 1},
		{Name: "work_arrangement", Type: field.TypeEnum, Nullable: true, Enums: []string{"ON_SITE", "REMOTE", "HYBRID"}},
		{Name: "approved_by", Type: field.TypeUUID, Nullable: true},
		{Name: "approval_date", Type: field.TypeTime, Nullable: true},
		{Name: "approval_reference", Type: field.TypeString, Nullable: true},
		{Name: "compensation_data", Type: field.TypeJSON, Nullable: true},
		{Name: "performance_review_cycle", Type: field.TypeString, Nullable: true},
		{Name: "source_event_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "employee_id", Type: field.TypeUUID},
		{Name: "position_id", Type: field.TypeUUID},
	}
	// PositionOccupancyHistoriesTable holds the schema information for the "position_occupancy_histories" table.
	PositionOccupancyHistoriesTable = &schema.Table{
		Name:       "position_occupancy_histories",
		Columns:    PositionOccupancyHistoriesColumns,
		PrimaryKey: []*schema.Column{PositionOccupancyHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "position_occupancy_histories_employees_position_history",
				Columns:    []*schema.Column{PositionOccupancyHistoriesColumns[17]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "position_occupancy_histories_positions_occupancy_history",
				Columns:    []*schema.Column{PositionOccupancyHistoriesColumns[18]},
				RefColumns: []*schema.Column{PositionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "positionoccupancyhistory_position_id_start_date",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[18], PositionOccupancyHistoriesColumns[2]},
			},
			{
				Name:    "positionoccupancyhistory_employee_id_start_date",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[17], PositionOccupancyHistoriesColumns[2]},
			},
			{
				Name:    "positionoccupancyhistory_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[1]},
			},
			{
				Name:    "positionoccupancyhistory_start_date_end_date",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[2], PositionOccupancyHistoriesColumns[3]},
			},
			{
				Name:    "positionoccupancyhistory_assignment_type_start_date",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[5], PositionOccupancyHistoriesColumns[2]},
			},
			{
				Name:    "positionoccupancyhistory_position_id_fte_percentage_start_date",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[18], PositionOccupancyHistoriesColumns[7], PositionOccupancyHistoriesColumns[2]},
			},
			{
				Name:    "positionoccupancyhistory_approved_by_approval_date",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[9], PositionOccupancyHistoriesColumns[10]},
			},
			{
				Name:    "positionoccupancyhistory_source_event_id",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[14]},
			},
			{
				Name:    "positionoccupancyhistory_employee_id_start_date_end_date",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[17], PositionOccupancyHistoriesColumns[2], PositionOccupancyHistoriesColumns[3]},
			},
			{
				Name:    "positionoccupancyhistory_performance_review_cycle_start_date",
				Unique:  false,
				Columns: []*schema.Column{PositionOccupancyHistoriesColumns[13], PositionOccupancyHistoriesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AssignmentDetailsTable,
		AssignmentHistoriesTable,
		EmployeesTable,
		OrganizationUnitsTable,
		PositionsTable,
		PositionAssignmentsTable,
		PositionAttributeHistoriesTable,
		PositionHistoriesTable,
		PositionOccupancyHistoriesTable,
	}
)

func init() {
	AssignmentDetailsTable.ForeignKeys[0].RefTable = PositionAssignmentsTable
	AssignmentHistoriesTable.ForeignKeys[0].RefTable = PositionAssignmentsTable
	EmployeesTable.ForeignKeys[0].RefTable = PositionsTable
	OrganizationUnitsTable.ForeignKeys[0].RefTable = OrganizationUnitsTable
	PositionsTable.ForeignKeys[0].RefTable = OrganizationUnitsTable
	PositionsTable.ForeignKeys[1].RefTable = PositionsTable
	PositionAssignmentsTable.ForeignKeys[0].RefTable = EmployeesTable
	PositionAssignmentsTable.ForeignKeys[1].RefTable = PositionsTable
	PositionAttributeHistoriesTable.ForeignKeys[0].RefTable = PositionsTable
	PositionOccupancyHistoriesTable.ForeignKeys[0].RefTable = EmployeesTable
	PositionOccupancyHistoriesTable.ForeignKeys[1].RefTable = PositionsTable
}
