# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intelligence.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'intelligence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12intelligence.proto\x12\x0cintelligence\"9\n\x10InterpretRequest\x12\x11\n\tuser_text\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"A\n\x11InterpretResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x1c\n\x14structured_data_json\x18\x02 \x01(\t2g\n\x13IntelligenceService\x12P\n\rInterpretText\x12\x1e.intelligence.InterpretRequest\x1a\x1f.intelligence.InterpretResponseBf\n#com.sydney.cube_castle.intelligenceZ?github.com/gaogu/cube-castle/go-app/generated/grpc/intelligenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intelligence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.sydney.cube_castle.intelligenceZ?github.com/gaogu/cube-castle/go-app/generated/grpc/intelligence'
  _globals['_INTERPRETREQUEST']._serialized_start=36
  _globals['_INTERPRETREQUEST']._serialized_end=93
  _globals['_INTERPRETRESPONSE']._serialized_start=95
  _globals['_INTERPRETRESPONSE']._serialized_end=160
  _globals['_INTELLIGENCESERVICE']._serialized_start=162
  _globals['_INTELLIGENCESERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
